### ISSUE TITLE
use dynamic route throw error

### ISSUE THREAD

**Issue by ckken** [ctrlplusb/react-universally#101]
{
    path: '/',
    component: App,
    indexRoute: {getComponent: resolveIndexComponent},
    childRoutes: [
        //使用到公共模块的时候用到
        {path: ':module', getComponent(location,cb){
            System.import(`../components/${location.params.module}`)
                .then(module => cb(null, module.default))
                .catch(handleError);
        }},
    ]
}

Error occurred loading dynamic route
index.js:25 Error: Cannot find module './about'.(…)

**Comment by ckken** [comment]
this is my other project and it work for me ,but no universal render

export default function createRoutes() {
    injectAsyncReducer('config', configReducer)
    injectAsyncReducer('HOME_INDEX_INDEX', HomeReducer)
    return {
        path: '/mc',
        component: main,
        indexRoute: {component: Home},
        childRoutes: [
            //使用到公共模块的时候用到
            {path: ':module/:controller', getComponent(location,cb){
                const key = `${location.params.module}/${location.params.controller}`
                System.import(`app/${key}/index`).then(loadRoute(location,cb,key)).catch(errorLoading)
            }},
            //独立子页面
            {path: ':module/:controller/:action', getComponent(location,cb){
                const key = `${location.params.module}/${location.params.controller}/${location.params.action}`
                System.import(`app/${key}/index`).then(loadRoute(location,cb,key)).catch(errorLoading)
            }},
            {path: '*', component: nomatch}
        ]
    }
}

**Comment by ctrlplusb** [comment]
Hmmm, it's a slightly different configuration to my own.  I will play around with this concept soon as I plan to make some updates to the routing configuration.

**Comment by ctrlplusb** [comment]
I have a working solution :)

Just patching it up.  It should be available soon on the [`next`](https://github.com/ctrlplusb/react-universally/tree/next) branch.

**Comment by ctrlplusb** [comment]
@ckken I have made a push that to the next branch that includes a working model for what you are after. :)

**Comment by ctrlplusb** [comment]
Released :)

**Comment by ckken** [comment]
thx , all react in github your demo is best
