### ISSUE TITLE
hot to use redux

### ISSUE THREAD

**Issue by ckken** [ctrlplusb/react-universally#103]
can show me some example for redux

**Comment by ckken** [comment]
how to use it by redux 😂😂😂😂

**Comment by ctrlplusb** [comment]
Hi @ckken 

You can definitely add redux.  I have done so on an extended version myself, however, this is still in private development for now.

Looking at the forks of this project there are a couple which have implemented redux.  For example:
https://github.com/varmil/react-universally/tree/redux

I hope this helps.

**Comment by ckken** [comment]
thanks
