### ISSUE TITLE
Add HappyPack and DLL configuration to the webpack config

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#105]
I achieved a 78% build performance increase when I did so on a personal project.  DEFINITELY worth it.

**Comment by strues** [comment]
Are you still hoping to see this implemented? If so I might submit a PR.

**Comment by ctrlplusb** [comment]
That would be lovely. :-)

Thanks @strues!

**Comment by EugeneHlushko** [comment]
Hi @strues, are you on it?

**Comment by ctrlplusb** [comment]
Coming soon... #135

**Comment by ctrlplusb** [comment]
Released!
