### ISSUE TITLE
Hot reloading acts weird?

### ISSUE THREAD

**Issue by BerndWessels** [ctrlplusb/react-universally#107]
Seems that the hot reloading is not quite working.

1. navigate to 'about'
2. change something in 'Home.js' and save
3. navigate to 'home'
4. change something in 'Home.js' and save
5. change is not reflected :(

I also get

    Warning: [react-router] You cannot change <Router history>; it will be ignored

and

    [HMR] unexpected require(413) from disposed module 59

and in some cases (randomly) even exceptions in the server console.

I guess this is due to the fact that `React Hot Loader 3` is still in beta?

I hope its not another `windows thing`.

**Comment by ctrlplusb** [comment]
Hi @BerndWessels 

This will be partially affected by your previous issue (#104).  The latest configuration allowed me to get around a previous workaround we had to put in place for the hot reloading of the async routes.  As you have had to revert your routing configuration you are experiencing this problem again.

You can fix your HMR across navigation by putting the following workaround in your routes.js:

```javascript
if (IS_HOT_DEVELOPMENT) {
  // HMR does not work 100% if you are using the dynamic component resolution
  // properties (i.e. getComponent or getComponents). Specifically, HMR will
  // work initially but if you change your route (i.e. browse to another part
  // of your app) then the HMR will stop working.
  // As a workaround for this scenario; for any of your components that are
  // resolved dynamically please require them below. If you don't want to
  // maintain this list then you could remove it and instead do a manual browser
  // refresh after changing the route.
  require('../components/Home'); // eslint-disable-line global-require
  require('../components/About'); // eslint-disable-line global-require
}
```

You will have to add each route manually.  Sucks I know, but hopefully the webpack guys sort the Windows issue out soon.

In regards to the `Warning: [react-router] You cannot change <Router history>; it will be ignored`.  Don't worry about that.  It's a harmless warning that the RHL team know about, but it has no negative effect besides for filling up your console.

**Comment by BerndWessels** [comment]
Thanks @ctrlplusb 

This seems to work

    if (IS_HOT_DEVELOPMENT) {
        // HMR does not work 100% if you are using the dynamic component resolution
        // properties (i.e. getComponent or getComponents). Specifically, HMR will
        // work initially but if you change your route (i.e. browse to another part
        // of your app) then the HMR will stop working.
        // As a workaround for this scenario; for any of your components that are
        // resolved dynamically please require them below. If you don't want to
        // maintain this list then you could remove it and instead do a manual browser
        // refresh after changing the route.
        require('../components/App/views/Home'); // eslint-disable-line global-require
        require('../components/App/views/About'); // eslint-disable-line global-require
    }

I hope webpack will make these workarounds go away soon, since they really mess up the code.

**Comment by ctrlplusb** [comment]
Reverted back to our verbose way in v5.0.0

I am creating a new issue to track the System.import issue and then we can hopefully get rid of this.
