### ISSUE TITLE
Stabilising hot development

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#109]
I have a fairly large project built on top of this and I've exposed a lot of frailty with the current implementation.  I am in the process of coming up with a more solid implementation based on experience now.

**Comment by ctrlplusb** [comment]
One idea...

Instead of bundling the full server source, instead seperate the server code into a standalone folder, and then use webpack to bundle a `universalReactAppMiddleware` instance that the server code would reference.  

This would avoid all the complication in tearing down and bringing the server back up, which is fraught with peril in trying to maintain/destroy existing connections in a balanced manner.

**Comment by ctrlplusb** [comment]
Ok, I am trying to have 3 bundles now:

 - server
 - universalMiddleware
 - client

I believe this may give us the best of both worlds, and provide us with the capability to much better webpack/babel targeting for each bundle.

I have mode progress on the [`next`](https://github.com/ctrlplusb/react-universally/tree/next) branch.  Track this there.

**Comment by ctrlplusb** [comment]
Got the new development configuration working.  It's amazing!  Working crazy smoothly at the moment!  Stoked. 

I haven't pushed to the branch yet - I am gonna transfer this config to my larger project and see how it handles some real worldness.  But all in all it is looking pretty awesome.

**Comment by BerndWessels** [comment]
@ctrlplusb Great work. Can't wait to see your latest improvements. I'd like to contribute in future if needed/wanted.

**Comment by ctrlplusb** [comment]
@BerndWessels - great to hear! Contributiona, of any kind, are greatly appreciated. I would love for the project to grow.

I'll keep you posted with progress . Doing some beta testing from your side would be awesome.

And please feel free to being up any criticisms or general recommendations or anything really.

**Comment by ctrlplusb** [comment]
Mobile typos. :-)

**Comment by ctrlplusb** [comment]
@BerndWessels - The `next` branch is pretty stable now.  Are you happy to try and use this version?  I would love some feedback in terms of how stable the hot development feels.

```
git clone -b next https://github.com/ctrlplusb/react-universally
```

**Comment by ctrlplusb** [comment]
Released. 6.0.0

**Comment by BerndWessels** [comment]
@ctrlplusb thanks, great work.

Latest `master` `6.0.0` seems to be very stable even on Windows 10.

I have a few comments:

- When updating code I see things like this `[HMR] unexpected require(411) from disposed module 60` in the browsers console. It is just a warning, but I am not sure if that can be suppressed or points to an actual problem?
- Still seeing this error `Warning: [react-router] You cannot change <Router history>; it will be ignored` which you already mentioned is a `RHL` issue but can be ignored. I still think it would be great if we could get rid of it. Errors in the console are always upsetting ;)
- A clean NPM install on Windows succeeds with the following warnings:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
```
I don't worry about the first 2 warnings since they are Windows related and no problem, but the others point out that there are some missing peer dependencies, which is usually not good.

- I have one more question. Is there a technical reason that you have a `index.js` that points to the main js file in each folder (like `Home/index.js` pointing to `Home/Home.js`) rather than having the main code right away in the `index.js` file itself?

That's all I've got for now.

Thanks again for the great work.

**Comment by carsonperrotti** [comment]
Sorry to comment on a closed issue, but it seemed related. Since 6.0.0 I am getting two errors:
`Warning: [react-router] You cannot change <Router history>; it will be ignored`
`Warning: [react-router] You cannot change <Router routes>; it will be ignored`
during a hot reload.

**Comment by ctrlplusb** [comment]
@BerndWessels 

> I have one more question. Is there a technical reason that you have a index.js that points to the main js file in each folder (like Home/index.js pointing to Home/Home.js) rather than having the main code right away in the index.js file itself?

I like to structure my components into folders so that I can collate other files with them (e.g. tests/css/images etc).  In lots of cases I don't necessarily have additional files but I feel like it's better to do the work upfront rather than refactor them down the line.  Complete personal preference though, so please don't be afraid to break away from this.

> When updating code I see things like this [HMR] unexpected require(411) from disposed module 60 in the browsers console. It is just a warning, but I am not sure if that can be suppressed or points to an actual problem?
> Still seeing this error Warning: [react-router] You cannot change <Router history>; it will be ignored which you already mentioned is a RHL issue but can be ignored. I still think it would be great if we could get rid of it. Errors in the console are always upsetting ;)

These are known issues when using react router < v4 with react hot loader. Hopefully the upgrade to react router v4 will sort them all.

> I don't worry about the first 2 warnings since they are Windows related and no problem, but the others point out that there are some missing peer dependencies, which is usually not good.

I agree this can be a bit disconcerting.  In this case there is no break.  It's just the eslint configurations.  Unfortunately the airbnb config still pointed to an older version of one of the plugins. I'll try be more careful with this type of thing in the future though.  I definitely don't want people worrying that the starter kit is broken.

---

Thanks for all of this feedback! :)
