### ISSUE TITLE
ensureEnvVariablesExist +Unable to use runtime process.env

### ISSUE THREAD

**Issue by omerts** [ctrlplusb/react-universally#111]
We would like to be able to use runtime process.env variables. The problem is that when Webpack DefinePlugin, is used like this:
```javascript
'process.env': merge(
  {
    NODE_ENV: JSON.stringify(mode)
```
It overrides the full process.env object, causing all runtime variables to be unusable. If you try to use an env variable, for example BASE, webpack will bundle it into something like (since it replace process.env with the actual DefinePlugin value):
```javascript
{NODE_ENV: 'development', ....}.BASE // undefined
```

To fix this we could, use the DefinePlugin like:
```javascript
  new webpack.DefinePlugin({
        // NOTE: The NODE_ENV key is especially important for production
        // builds as React relies on process.env.NODE_ENV for optimizations.
        'process.env.NODE_ENV': JSON.stringify(mode),
```
But then `ensureEnvVariablesExist ` starts throwing errors, since the DefinePlugin finds and replaces the key with the value, and it is not really a process.env variable.

**Comment by ctrlplusb** [comment]
Hi @omerts 

I am in the middle of a huge upgrade/refactoring. I will take this onboard.

**Comment by ctrlplusb** [comment]
Implemented on `next` branch.
