### ISSUE TITLE
Build does not create client only index.html

### ISSUE THREAD

**Issue by BerndWessels** [ctrlplusb/react-universally#112]
In many projects I don't need server side rendering, but rather want to host the site on a CDN.

But I would still like to use react-universally as my base project.

To be able to use the production output without server side rendering it needs to create the index.html too. Then I can just copy the production output to a CDN.

Could you please add this?

**Comment by ctrlplusb** [comment]
Hi @BerndWessels 

Interesting to hear that you would like to use this boilerplate as a base for "standard" react apps.  Have you considered using [`create-react-app`](https://github.com/facebookincubator/create-react-app)? Dan has done an amazing job on this and it has community support.  I would recommend that you consider it.  :)

If you would like an html file to be output along with your client bundle, you can do so by adding the   [`html-webpack-plugin`](https://github.com/ampedandwired/html-webpack-plugin).  Try it out. :)

I am apprehensive to add this as a standard feature of this boilerplate as I do want to keep it focused on being a base for universal applications, but perhaps we could as this to the FAQ section.

Let me know how it goes.

**Comment by ctrlplusb** [comment]
Closing this for now, hope the above helped.

**Comment by BerndWessels** [comment]
@ctrlplusb thanks for the info.

I'd rather have my own fork of `react-universal` with some of my opinionated extensions (like sass and redux) as the basis for all (server side rendered AND client side only) of my future react projects.

I had my own solutions before but think that your boilerplate is the most mature and clean I have seen so far. And it matches pretty much my personal preferences on style and comments.

Having the same code base for server side rendered and client side only projects also keeps things together and doesn't force me and others working on it to switch their minds when switching between those types of projects.

I really love your work and will extend it with the `html-webpack-plugin` in my fork then.

Thanks again for the great work.

**Comment by ctrlplusb** [comment]
That's great to here!  Please do keep me posted with progress on your fork.  I am always happy to add extended versions of this boilerplate to the readme.

And thanks for the thumbs up.  I really appreciate it! :)

**Comment by BerndWessels** [comment]
@ctrlplusb Hi
I have added this feature now and would love you to review and consider it.
[Here is the PR](https://github.com/ctrlplusb/react-universally/pull/118)
