### ISSUE TITLE
Page loads without CSS for a split second

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#113]
On the first page load, the HTML renders before the CSS, then after a split second, the styles are applied. This causes a quick flash on page load where the content shifts. This happens after a fresh checkout as well.

Chrome 55
macOS 10.11

**Comment by ctrlplusb** [comment]
Is it happening on your production build?

**Comment by ctrlplusb** [comment]
To be clear.  This should only happen in development mode as far as I know.

**Comment by carsonperrotti** [comment]
... Well. I feel silly. Going to close this issue and pretend that I didn't make such a silly mistake.

![](http://i.giphy.com/l0HlOiN4swXGV5zaw.gif)

**Comment by ctrlplusb** [comment]
Haha, don't worry about it.  We all make them! :)

Thanks for caring enough to report an issue anyways. :)

P.S. I recently pushed the v6.0.0 release.  Are you using this version?  I would appreciate any feedback on your development experience. :)

**Comment by carsonperrotti** [comment]
I just merged it into my repo. So smooooooooth. I love the improvements to the console logging. 

My repo uses [Apollo and GraphQL](http://www.apollostack.com/) and it's [SSR support](http://dev.apollodata.com/react/server-side-rendering.html#getDataFromTree) seems to be having an issue with the async component loading, but that's not an issue with this repo.
