### ISSUE TITLE
Add basic ServiceWorker configuration - caching and offline support

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#114]

**Comment by EugeneHlushko** [comment]
@ctrlplusb Hi man, are you looking into this enhancement?

**Comment by ctrlplusb** [comment]
Hi @EugeneHlushko 

Yep, definitely plan to.  Last couple of weeks was all about React Router v4 and the redux branch.  The outstanding issues will be up next now, including this.

Addy Osmani has a great series I want to go through in relation to this.

https://addyosmani.com/blog/progressive-web-apps-with-react/

**Comment by ctrlplusb** [comment]
This will be slowly implemented with the [`pwa`](https://github.com/ctrlplusb/react-universally/tree/pwa) branch.

**Comment by EugeneHlushko** [comment]
Hi @ctrlplusb! Great news!
I am willing to help but still cannot find time :/ if by any means i will find time - expect some help asap

**Comment by ctrlplusb** [comment]
Adding a service worker was actually really easy! :D

With this being a universal application I already had everything I needed in place.  Just patching up a few things and then this is ready to roll. :)

**Comment by ctrlplusb** [comment]
Results thus far when testing with Lighthouse:
https://www.dropbox.com/s/zy6ssgcciz141ih/Screenshot%202016-10-26%2017.25.45.png?dl=0

87/100

Need offline support, then all good. :)

**Comment by kikoanis** [comment]
You could consider using this webpack plugin [offline-plugin](https://github.com/NekR/offline-plugin)

Great project BTW

**Comment by kikoanis** [comment]
The numbers of the Lighthouse extension are really high. I think this is partially to the code-split and tree-shaking that resulted in smaller chunks. I expect the number to hit 100 when implement the offline support.

**Comment by ctrlplusb** [comment]
Yep, the SSR helps too. I reckon you are right

**Comment by EugeneHlushko** [comment]
@ctrlplusb Does sw-precache-webpack-plugin take care of asset versioning?

**Comment by ctrlplusb** [comment]
The webpackmd5hash plugin takes care of that.

**Comment by ctrlplusb** [comment]
@EugeneHlushko sorry for the terse response. On mobile. Let me know if the cache busting needs explaining.

**Comment by ctrlplusb** [comment]
I think I have a solution for offline support too. :-)
Sleep first.

**Comment by EugeneHlushko** [comment]
@ctrlplusb didnt notice md5 at first glance on pwa 👍 This is awesome setup

**Comment by ctrlplusb** [comment]
Yeah, I definitely find doing the md5 hashing based on file contents is simplest approach.  There are a few others, but md5 hash of a file is easy for anyone to understand.  :)  
Works really well too, only the files that actually change will have cache invalidation. So a code change won't result in all assets being invalidated, only the chunks that changed (e.g. vendor, image, code split route chunk etc)

**Comment by ctrlplusb** [comment]
We are in business. :)

https://www.dropbox.com/s/yl8m783vtsambdz/Screenshot%202016-10-27%2016.23.45.png?dl=0

**Comment by EugeneHlushko** [comment]
Awesomeness! Good job man! @ctrlplusb

**Comment by ctrlplusb** [comment]
Released!

**Comment by kikoanis** [comment]
Great job. Impressive!

Not sure if the version of the Lighthouse extension you are using is old but my take on generating the report yielded a missing item in your report --> Cache contains start_url from manifest (alpha)
[https://www.dropbox.com/s/fsy3m3cp6q9k5ne/Capture.PNG?dl=0](https://www.dropbox.com/s/fsy3m3cp6q9k5ne/Capture.PNG?dl=0) 

I think all you need to do is to provide a manifest JSON file ([Specification is here](http://html5doctor.com/web-manifest-specification/))
that you can reference in your html like so
``` <link rel="manifest" href="/swmanifest.json" />```

**Comment by ctrlplusb** [comment]
Awesome thanks @kikoanis 

I'll double check my extension is up to date. :-)

**Comment by kikoanis** [comment]
Something similar to this would work
```
{
  "name": "React Universally",
  "short_name": "react-universally",
  "icons": [
    {
      "src": "/images/android-icon-48x48.png",
      "sizes": "48x48",
      "type": "image/png",
      "density": 1.0
    },
    {
      "src": "/images/android-icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png",
      "density": 2.0
    },
    {
      "src": "/images/android-icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png",
      "density": 3.0
    },
    {
      "src": "/images/android-icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png",
      "density": 4.0
    }
  ],
  "start_url": "/",
  "display": "standalone",
  "orientation": "portrait",
  "background_color": "#ffffff",
  "theme_color": "#222222"
}
```

of course, you need to change to match your images path.

**Comment by kikoanis** [comment]
I see you already added a manifest file in an earlier commit.
For the missing item in the Lighthouse report, I think the reason is that you are running the extension on a local site where I was running it on a non-local site.
