### ISSUE TITLE
[Question] Recommended route structure

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#116]
I have a question with how to structure the routes for a complex application using this async system and code splitting along routes:

Should each route be set up as a top level view? For example:

Legend: path - (component)

```
<Route path="/" component={App}>
  <IndexRoute getComponent={asyncAppViewResolver('Home')} />
  <Route path="login" getComponent={asyncAppViewResolver('Login')} />
  <Route path="dashboard" getComponent={asyncAppViewResolver('Dashboard')} />
  <Route path="dashboard/user" getComponent={asyncAppViewResolver('User')} />
  <Route path="dashboard/feed" getComponent={asyncAppViewResolver('Feed')} />
</Route>
```

OR - can I nest routes beneath each view using the normal component={} system

```
<Route path="/" component={App}>
  <IndexRoute getComponent={asyncAppViewResolver('Home')} />
  <Route path="login" getComponent={asyncAppViewResolver('Login')} />
  <Route path="dashboard" getComponent={asyncAppViewResolver('Dashboard')}>
    <Route path="user" component={User} />
    <Route path="feed" component={Feed} />
  </Route>
</Route>
```

My goal here is to keep code splitting to reduce initial load times here as well as support a complex app structure where there are many routes inside the /dashboard route that all load components inside it's component which has a navbar and sidebar. I also want to avoid reloading or re-rendering the same components when a user changes a route. 

Any thoughts or suggestions to point me in the right direction here would be most helpful.

**Comment by ctrlplusb** [comment]
Hi @carsonperrotti 

Hmmm, lots of questions in there.  I am not sure if there is a blanket answer to the structuring of your routes.  Please don't be afraid to break away from the base structure I provided.  My intentions with the boilerplate are not to dictate how you should structure your routes, but rather show you some of the tools you have at your disposal (i.e. code splitting via async routes). 

Something that may be helpful to you.  I believe you can pass a path to `asyncAppViewResolver`. 

e.g.

```js
asyncAppViewResolver('Dashboard/User')
```

Which would resolve to `src/shared/universal/components/App/views/Dashboard/User/index.js`.

You could also just add your own System.import statements as and where you feel it's the most useful.

I plan to do a big restructure into react router v4 soon, which may provide us with a lot more tools and things to consider in terms of application structure.

Sorry if that isn't particularly helpful.

Oh, another comment.  Don't be afraid to "re-render" a component (e.g. your navbar/sidebar).  Remember React's diffing algorithm is there to help! Pre-optimisation is the root of all evil and all of that... :)

**Comment by carsonperrotti** [comment]
Thanks a lot for fielding a question that doesn't quite fall under the scope of this project. It's great to see how other people handle these kinds of things. I think I've got what I need in order to keep a good structure and scale up the app.
