### ISSUE TITLE
Add a "preact" branch

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#122]
Will then make the build use `preact` and `preact-compat`, which provides you with some great bundle size savings.  The default would be to use the native `react` lib.

**Comment by ctrlplusb** [comment]
Closing in favour of #156

**Comment by SunnyGurnani** [comment]
@ctrlplusb can you point me to preact branch please?

**Comment by ctrlplusb** [comment]
Sorry, it doesn't exist.  But adding preact is easy. :)

Just need to set the webpack alias's.

Check the deprecated [`react-universally-skinny`](https://github.com/ctrlplusb/react-universally-skinny)
