### ISSUE TITLE
Consider adding an example logger/trace service?

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#124]
[`rollbar`](https://github.com/rollbar/node_rollbar) is pretty awesome and they have a free tier.

**Comment by carsonperrotti** [comment]
I would like to throw [Trace](https://trace.risingstack.com) into the ring for consideration.

**Comment by enten** [comment]
I never use that kind of error tracking service. Is that really useful? I'm interesting to know your experience with them.
