### ISSUE TITLE
You cannot change <Router history> it will be ignored

### ISSUE THREAD

**Issue by vimniky** [ctrlplusb/react-universally#126]
Hi !  what is this warning ? When I run `npm start development` and start to make some change  I got this warning .
<img width="569" alt="screen shot 2016-10-12 at 5 44 12 pm" src="https://cloud.githubusercontent.com/assets/11426875/19305515/d59ae9a2-90a3-11e6-9e87-f3e82f7abbfc.png">

**Comment by ctrlplusb** [comment]
It's a know issue with using react hot loader with react router <v4. Don't worry it's just a warning. The only harm it's doing is filling up your console. I have an update coming which migrates us on to react router 4 where these warnings are no longer an issue and hot reloading works far more reliabily.

**Comment by vimniky** [comment]
Thanks ! I'll waiting for your update .
