### ISSUE TITLE
[Next] Match not passing props in render

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#127]
When using the `render` API for Match, you need to pass props to the component, otherwise they will miss out on things like `location` or `params`.

Heres an example solution:
```
<Match
  exactly
  pattern="/"
  render={(props) =>
    <CodeSplit module={require('../../views/Home')}>
      { Home => (Home ? <Home {...props} /> : <div>Loading...</div>) }
    </CodeSplit>
  }
/>
```

Edit: typos

**Comment by ctrlplusb** [comment]
Much appreciated.

**Comment by ctrlplusb** [comment]
Implemented in next branch... coming soon.
