### ISSUE TITLE
Can't we import es6 component ?

### ISSUE THREAD

**Issue by devdlabs** [ctrlplusb/react-universally#132]
@ctrlplusb in dynamic routes how to import es6 component ? Am I missing something there?

**Comment by ctrlplusb** [comment]
@devdlabs You should be able to import an es6 component.  Can you please give me an example of your code?

**Comment by devdlabs** [comment]
I mean can't we make dynamic  Views as es6 rather stateless functions ? When I try to change Home function to es6 like `class Home extends React.Component` I get 

> TypeError: Super expression must either be null or a function, not undefined

**Comment by ctrlplusb** [comment]
🤔

This shouldn't make a difference.  Is this based on react-universally v6 or the newer v7? i.e. react-router v2 or react-router v4?

**Comment by devdlabs** [comment]
I tested both react-universally and react-universally@next

**Comment by ctrlplusb** [comment]
There is no `next` branch at the moment, so you may be working on an older clone.

Please check your package.json and let me know what version of react-router your clone is using.  I want to make sure I am trying to debug on the same version of the code you are using.

**Comment by devdlabs** [comment]
Yeah, sorry I mean redux branch v7 my react-router@4.0.0-alpha.4

**Comment by ctrlplusb** [comment]
Ok.

I changed my Home component to the following:

```jsx
/* @flow */

import React, { Component } from 'react';
import Helmet from 'react-helmet';

class Home extends Component {
  render() {
    return (
      <article>
        <Helmet title="Home" />

        <p>
          This starter kit contains all the build tooling and configuration you
          need to kick off your next universal react project, whilst containing a
          minimal project set up allowing you to make your own architecture
          decisions (redux/mobx etc).
        </p>
      </article>
    );
  }
}

export default Home;
```

It worked for development and production builds.

Can you try deleting your node_modules and do fresh npm install?

**Comment by devdlabs** [comment]
Oh Yeah, It worked. Don't know which one mess with my node_modules. Thank you @ctrlplusb

**Comment by ctrlplusb** [comment]
No problem. :)

If in doubt, always delete the node_modules first. :)
