### ISSUE TITLE
'copyfiles' used on npm script 'removetypes' is not on dependencies

### ISSUE THREAD

**Issue by williamoliveira** [ctrlplusb/react-universally#134]

**Comment by williamoliveira** [comment]
Another problem with this command by the way: it compiles JSX

**Comment by ctrlplusb** [comment]
😥

**Comment by ctrlplusb** [comment]
Thanks for the report @williamoliveira 

All sorted in latest release.

**Comment by williamoliveira** [comment]
No problem.
I am loving this starter kit, it's the most sane and well made have seem so far (and I have tested many)
Thank you for all the work :)

**Comment by ctrlplusb** [comment]
I am so happy you are finding it useful.

Thanks for the feedback. I really appreciate it!
