### ISSUE TITLE
Plans to support mobx?

### ISSUE THREAD

**Issue by evgenyboxer** [ctrlplusb/react-universally#138]
Hi :)

Good job on the repo!

Any plans to make a mobx branch too?

**Comment by ctrlplusb** [comment]
I'm definitely open to have a mobx ready branch, but no immediate plans, so if you feel comfortable with converting the `redux` branch into a `mobx` variant that would be greatly appreciated. :)

**Comment by ctrlplusb** [comment]
Closing in favour of #156
