### ISSUE TITLE
Vendor DLLS cache not being updated

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#143]
I noticed that when I removed a few packages from my project that during a build I was still seeing them listed in console during the vendor DLL build process. Running the clean script and removing the node_modules folder made no difference. Eventually I realized that it may still be caching vendor DLLs. 

It should probably be included in the clean process or have better removal of libs when one removes a package from their package.json file.

Edit: wording for clarity.

**Comment by carsonperrotti** [comment]
Nevermind. It turns out that just having an import for a package in a file that isn't in use is enough to have it show up in the list of vendor DLLS, even if the dependency isn't in my package.json file.

There goes a lot of wasted time. Haha.

**Comment by ctrlplusb** [comment]
This is an interesting point though.  Perhaps I should validate the dependencies against those from the package.json? Then at least provide a warning.
