### ISSUE TITLE
favicon is pinged for every location change in Chrome.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#145]
Getting network pulls with every render caused by client side route change.

I am not sure how react-helmet handles diff's/renders, but I may need to pull the script and link declarations out of the jsx and let them sit as constants.

**Comment by ctrlplusb** [comment]
Not a react-helmet issue.

Think the favicons need to be listed in the manifest.json

**Comment by ctrlplusb** [comment]
Argh, can't figure this one out.  It appears to happen when using Chrome only.  Any location change causes a network ping on the favicon.  It comes back with a 304 response, but it's still an unnecessary network request.  I can't seem to find anything that discusses what problem this is a symptom of.

**Comment by elodszopos** [comment]
Hey - I can see you closed this one down. How do you now it's not a react-helmet issue? For all I can tell, it is. Shouldn't react-helmet know the favicon didn't change and not make the request at all?

![image](https://cloud.githubusercontent.com/assets/4669986/21507883/08d6b234-cc85-11e6-9115-ca61c5b2b805.png)

A little off-topic, but relating to unnecessary api requests - in your redux feature branch navigating between posts kept reloading each post even if already loaded. Was that only me or was that happening for you as well @ctrlplusb?

**Comment by elodszopos** [comment]
Maybe this has something to do with it?

https://github.com/nfl/react-helmet/issues/149

**Comment by Doeke** [comment]
For anyone running into the same issue (with react or another framework, I'm using VueJS):

Try reordering the favicon link tags. For me, putting the 16x16 link before 32x32 fixed this issue. As for why this works... I have no idea.
