### ISSUE TITLE
Redux/ Apollo initial state issue with queries

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#146]
On my fork with Apollo I ran into quite a weird bug that turns out to be related to storing the whole initial state in the redux store when doing SSR. 

It turns out that when dehydrating the state from the server, you need to make sure that it only contains the data field. Read more on the issue [here](https://github.com/apollostack/apollo-client/issues/845).

I would have just submitted a PR, but my fork is quite heavily modified at this point. I'll try to maintain a public fork for PRs in the future.

**Comment by carsonperrotti** [comment]
I'll just make a new fork and submit a PR. There's one other quick fix that I ran into. Let me know if that's cool with you and I'll submit one.

**Comment by ctrlplusb** [comment]
That's awesome, thanks for the heads up. 

That branch still needs a lot of work.  I am thinking of removing the router tasks and keeping it as vanilla apollo as possible.  You seem to have much more experience with apollo so I would greatly appreciate your help/input here. :)

**Comment by carsonperrotti** [comment]
I'll go ahead and start submitting some PRs then. I'm learning a lot of this through 'trial by fire'. 

I personally kept Redux around since I ended up using Redux-Forms in my project.

**Comment by ctrlplusb** [comment]
Yep, I think its great to keep redux, but not sure if the router tasks implementation I added is specifically needed as apollo takes care of all the data prefetching needs.

**Comment by ctrlplusb** [comment]
@carsonperrotti I've added you as a collaborator to this project.  This is something I am really keen on having more of.

I'll consider you the master of the `apollo` branch. :)

**Comment by carsonperrotti** [comment]
Going to go ahead and close this since #148 was merged in.
