### ISSUE TITLE
react-toolbox out?

### ISSUE THREAD

**Issue by janusch** [ctrlplusb/react-universally#149]
Hey,
I just fell over an issue you raised in July about wp2 with react-toolbox. Did you ever get that solved, or did you kick react-toolbox?

Did you find a similar ui framework that integrates with webpack 2?
I am facing the same issue, also trying react-toolbox@2 and cannot seem to get it to work.

Cheers

**Comment by ctrlplusb** [comment]
Hi @janusch 

I've since dropped `react-toolbox` from the project I was using it on as I wanted a lot more control over the UI elements.

If memory serves me correctly it wasn't an issue with webpack 2 per se, but rather that I needed to have a sass loader configured correctly.  They were using sass at the time, so I needed to include the react-toolbox folder from node_modules into the sass loader.

**Comment by strues** [comment]
I've been meaning to sit down with React-Toolbox again and play with it. I'll take a look tonight or tomorrow morning at work. I remember the styling being an issue, but at one point I had it working properly.

**Comment by ctrlplusb** [comment]
Awesome @strues - kind of you!

**Comment by ctrlplusb** [comment]
We could consider making a branch for it?

**Comment by janusch** [comment]
Thanks for your replies. I hope it is not such a bumpy road for you @strues as in my tries. Looking much forward to see if you can get it to work!

**Comment by strues** [comment]
Running into more trouble than I expected with React Toolbox. Going to spend a while longer

**Comment by joehua87** [comment]
I've found a workaround to config this repo to works with react-toolbox in this commit https://github.com/joehua87/react-universally/commit/9246a4680b2c6efbe543634b49ca4413eaca6abc
 
This commit solves:
* Integrate react-toolbox
* use sassLoader for theming react-toolbox

Production here: https://react-universally-pozqmcanav.now.sh/

P.S. I've remove react-toolbox in dll builds to let it works with `isDev` mode

**Comment by strues** [comment]
This is where I went wrong. https://github.com/joehua87/react-universally/commit/9246a4680b2c6efbe543634b49ca4413eaca6abc#diff-55fab3537aa3ffa13b2a907d688ce224R407

I was configuring sass-loader within the LoaderOptions plugin, where logically you would think it belongs. Nice solve!

**Comment by joehua87** [comment]
For postcss, we cannot path the options that ways because it contains an object (not string). So I think we should have a postcss.config.js file. @strues, how about your thinking?

**Comment by ctrlplusb** [comment]
Also interesting case in wanting to skip the vendor dll.  I will have to consider providing a configuration override for this.

**Comment by ctrlplusb** [comment]
@joehua87 The latest release allows you to set libraries to be ignored within the vendor dll.  May be helpful. :)

I am going to close this issue for now, but will reference it in the branches issue.
