### ISSUE TITLE
Add a default url-loader configuration for common asset types

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#15]
I have always needed this in my projects, and in the rare case it isn't needed it just silently sits there without impact.

**Comment by KeKs0r** [comment]
Currently trying to achieve something similar. Not sure if its completely related.

I am using fontgen loader to generate an own icon font:

```javascript
        merge(
          // { test: /\.font\.(js|json)$/ },
          { test: /\.font$/ },
          ifServer({
            loaders: [
              'fake-style-loader',
              'css',
              'fontgen'
            ]
          }),
          ifClient({
            loaders: [
              'style',
              'css',
              'fontgen'
            ]
          })
        ),
```
This works like a charm for actual building, but not in "development" due to the publicPath
```javascript
      publicPath: ifDev(
        // As we run a seperate server for our client and server bundles we
        // need to use an absolute http path for our assets public path.
        `http://localhost:${process.env.CLIENT_DEVSERVER_PORT}/assets/`,
        // Otherwise we expect our bundled output to be served from this path.
        '/assets/'
      ),
```

This causes errors in webpack trying to load in development:
```
ERROR in ./~/css-loader!./~/fontgen-loader!./src/style/awesomecons.font
Module not found: Error: Can't resolve './http:/localhost:8006/assets/24f28e5640d6697dce825a7a13eb1a26-Awesomecons.eot' in '/Users/marc/Sites/react-universally/src/style'
 @ ./~/css-loader!./~/fontgen-loader!./src/style/awesomecons.font 6:88-177
 @ ./src/style/awesomecons.font
 @ ./src/components/App/App.js
 @ ./src/components/App/index.js
 @ ./src/routes/index.js
 @ ./src/index.js
 @ multi main
```

I am not 100% sure how to handle static assets such as fonts with universal rendering.

**Comment by ctrlplusb** [comment]
For font's I just use a straight up [`url-loader`](https://github.com/webpack/url-loader).  

For example, in the loaders config:

```javascript
     loaders: [
        // Images and Fonts
        {
          test: /\.(jpg|jpeg|png|eot|svg|ttf|woff|woff2)$/,
          loader: 'url-loader',
          query: {
            limit: 10000,
          },
        },
```

And then you can import fonts/images/etc in your components or CSS.  Webpack will convert them into URLs.  This works on the server too.

For example:

```javascript
import myImage from './myImage.png';
import React from 'react';

function Foo() {
  return (
    <img src={myImage} />
  );
}
```

It works for fonts too, and within your CSS, for example:

```css
.img {
  background: url('./myImage.png');
}
```

It's great as you can colocate your images/fonts with your css.

In my project I import my fonts manually in my CSS:
```
@font-face {
  font-family: 'YanoneKaffeesatz';
  src: url('./fonts/YanoneKaffeesatz.eot?#iefix') format('embedded-opentype'),  url('./fonts/YanoneKaffeesatz.woff') format('woff'), url('./fonts/YanoneKaffeesatz.ttf')  format('truetype'), url('./fonts/YanoneKaffeesatz.svg#YanoneKaffeesatz') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by oyeanuj** [comment]
@ctrlplusb Quick question on this old thread: If my image is colocated in the same folder, should I expect the following to work in my CSS file without any imports, etc:
```css
.img {
  background: url('./myImage.png');
}
```

And should I then expect it to be bundled in `public` folder?

I ask since I can't get this to work and I wasn't sure if I was misunderstanding the usage?
