### ISSUE TITLE
helmet configuration

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#150]
ORIGINAL TITLE: helmet v3.0.0 breaking changes update

**Comment by ctrlplusb** [comment]
I don't think it was actually a breaking change, I think my old configuration was always incorrect so it never ran.  It looks like the v3 api includes validation of the config which alerted me to the issue.  I have had to make some adjustments to the CSP config to allow the app to run. The one area of concern is allowing the executing of inline-scripts - which is needed for redux/mobx/apollo data rehydration via the `<script>window.APP_STATE...` technique. If security is paramount to you then you will need to move this state into a javascript file which can be referenced and executed by the client.  I am not sure how practical/easy that is to do though, so would appreciate anyones thoughts on this.

**Comment by carsonperrotti** [comment]
I'll pass the question along in the Apollo slack group.

**Comment by ctrlplusb** [comment]
Brilliant @carsonperrotti thanks for that.  Interesting problem.

I suspect the CSP configuration may trip up a few people.  Especially those not use to them.  I'll have to consider adding a helpful section with the README.md to really highlight this.

**Comment by ctrlplusb** [comment]
Ok, so the answer to this is to use nonces.

Described here:
 - https://scotthelme.co.uk/csp-cheat-sheet/

Implementation example here:
 - https://helmetjs.github.io/docs/csp/

**Comment by ctrlplusb** [comment]
Okay, I have this working.  Just cleaning it up and prepping a new release.

I've also noticed the CSP has broken the service worker.  I've had to relax the CSP `connect-src` directive to allow "*".  I'm not entirely sure of the repercussions here.  If someone knows of a better way to support service workers via CSP then please let me know.

**Comment by strues** [comment]
I believe setting the directive like this will fix the CSP issue

```
Content-Security-Policy: default-src 'self' http://localhost:PORT https://*.PRODUCTION_DOMAIN.tld
```

You probably would want to set the non-self value to an environment variable. Then let Webpack take care of inlining it.

**Comment by ctrlplusb** [comment]
Thanks @strues I'll try and see what I can do there.

I've made another update, which includes nonces for our inline scripts.  So we can now safely rehydrate our application state.
