### ISSUE TITLE
Branch ideas

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#156]
Here are a few of the branch ideas I would like to have implemented:

- [ ] glamor
- [x] jest (w/enzyme)
- [ ] mocha (w/enzyme)
- [ ] mobx
- [ ] preact
- [ ] postcss (seems like an easy one to trip over, so may be useful to have a working branch)

**Comment by evgenyboxer** [comment]
I might take the mobx + postcss.
I've already got a project using it. Basically, I used the redux branch as a start, and worked my way from there.

**Comment by lucianlature** [comment]
What about a mix between `jest (w/enzyme)` and [style-components](https://github.com/styled-components/styled-components)?

**Comment by strues** [comment]
I'm using jest w/ enzyme in my personal projects. Hell, I've even been using Jest to test my Node APIs

**Comment by ctrlplusb** [comment]
@streus wow! Jest plays nicely with the nodejs side too? That is awesome. I definitely need to give it a bash! :-)

**Comment by ctrlplusb** [comment]
@lucianlature I would prefer if we didn't mix concerns in the branches. That way a styled-components/css-modules/glamor branch could be merged with a jest/mocha branch quite easily when required. :-)

**Comment by strues** [comment]
It works really nicely. I was surprised. Got rid of all the mocha, mocha-chai, sinon-chai, etc and now am slowly migrating all of my tests to just using jest.

**Comment by strues** [comment]
This https://github.com/adriantoine/enzyme-to-json allows you to even use Jest snapshots with Enzyme. Glorious.

**Comment by ctrlplusb** [comment]
I would love it if you added a branch here 😇

**Comment by strues** [comment]
Not a problem. I'll get to it tonight over a beer or two.

**Comment by strues** [comment]
Jest w/ Enzyme https://github.com/ctrlplusb/react-universally/tree/feature/jest-enzyme

**Comment by ctrlplusb** [comment]
React Toolbox branch example: #149

**Comment by ctrlplusb** [comment]
Thanks @strues!

**Comment by strues** [comment]
Koa instead of Express is an idea. 

Another idea is a more plug-and-play / mix-and-match with plugins and loaders.

**Comment by ctrlplusb** [comment]
Some solid ideas.

I'm also considering removing the mocha option out of respect to the awesomeness that is Jest. 😆

**Comment by lucianlature** [comment]
@strues: I have an working example of using koa2. Interested?

**Comment by strues** [comment]
Sure @lucianlature.

@ctrlplusb Im going to play around with Redis caching the server rendered pages. Ive heard performance gained can be quite massive

**Comment by strues** [comment]
Ive got styled-components working flawlessly. I can create a branch if you'd like.

**Comment by ctrlplusb** [comment]
Awesome man! You are on a roll. Yes please!

Been meaning to speak to you about naming strategies for the branches.  We have a disconnect between your git-flow styled "feature/x" branch names, and the others which are standalone.  I don't really have a preference for one or the other, but we should probably all decided on a standard moving forward.

@carsonperrotti is pretty much the master of the apollo branch, so would be good to coordinate with him.

I'll leave this coordination up to the two of you in my absence. :)

Chat again after the 26th.

Peace.

**Comment by strues** [comment]
Go ahead and rename the two branches with feature/ in them? I'll drop the habit for this project ;)

**Comment by LorbusChris** [comment]
What about a Branch using the Found lib for routing?

Found is designed to work with Relay (found-relay), so in the longer run my aim will be to get that working.

For now, I've created a WIP PR that implements Client Side Rendering with Found. SSR isn't working with Found, yet, but support will hopefully follow soon.

**Comment by ctrlplusb** [comment]
Closing in favour of #201
