### ISSUE TITLE
HappyPack and Universal Middleware

### ISSUE THREAD

**Issue by strues** [ctrlplusb/react-universally#160]
This error occurs randomly upon starting the development task. I've ran into it on two separate projects now so I'm bringing attention to it as I search for the underlying cause and a solution.

Things to note
- I'm running this alongside an api (irrelevant to this issue, for the most part)
- Occurs upon startup
- Everything from React Universally is the same, minus a few folder names, and Sass/PostCSS added.
- It seems like this is almost entirely HappyPack related or has to do with the bundling isnt entirely in sync with whats going on.

Another thing to note is, occasionally on page load, I'll come across an invariant error from the vendor bundle. This error mysteriously goes away after a refresh or four, or a full restart of the task. Really just putting this out there to see if someone else has experience something similar.

```
==> UNIVERSALMIDDLEWARE -> Build failed, please check the console for more information.
Hash: 02205a13916dfcd5641c
Version: webpack 2.1.0-beta.25
Time: 1701ms
       Asset     Size  Chunks       Chunk Names
    index.js  3.49 kB       0       index
index.js.map  2.56 kB       0       index
chunk    {0} index.js, index.js.map (index) 768 bytes [entry] [rendered]
    [0] ./src/cms/universalMiddleware/index.js 740 bytes {0} [built] [failed] [1 error]
    [1] multi index 28 bytes {0} [built]

ERROR in ./src/cms/universalMiddleware/index.js
Module build failed: AssertionError: You must launch a compilation thread before attemping to use it!!!
    at Object.compile (/Users/steventruesdell/Code/RedHot/site/node_modules/happypack/lib/HappyThread.js:121:7)
    at HappyPlugin._performCompilationRequest (/Users/steventruesdell/Code/RedHot/site/node_modules/happypack/lib/HappyPlugin.js:311:10)
    at HappyPlugin.compileInBackground (/Users/steventruesdell/Code/RedHot/site/node_modules/happypack/lib/HappyPlugin.js:280:8)
    at HappyPlugin.compile (/Users/steventruesdell/Code/RedHot/site/node_modules/happypack/lib/HappyPlugin.js:262:17)
    at Object.HappyLoader (/Users/steventruesdell/Code/RedHot/site/node_modules/happypack/lib/HappyLoader.js:27:15)
 @ multi index
```

**Comment by ctrlplusb** [comment]
Thanks @strues :)

I've also experienced the happy pack issue. :(

Appreciate you looking into this.  I am making the code splitting optimisation my priority for now, but can step in to help thereafter.

**Comment by strues** [comment]
No problem. I'll keep adding to the issue as I uncover things.

**Comment by strues** [comment]
@ctrlplusb I'm thinking this issue applies https://github.com/amireh/happypack/issues/72

**Comment by ctrlplusb** [comment]
One possible solution:
Nice the happy pack config and thread pool init to live within the webpack config factory. Perhaps a new instances needs to be created between teardowns?

**Comment by strues** [comment]
Confirming this is the cause. Two projects, one with thread pooling and one without, the thread pooling project has experienced the issue a couple times. The one without, hasnt had a single hiccup.

**Comment by ctrlplusb** [comment]
Thanks @strues - I have implemented this!

**Comment by code-punkt** [comment]
This is happening to me again quite often with version 10 :(

**Comment by ctrlplusb** [comment]
Yeah I tried to introduce the thread pool again after they did v3 release. Gonna roll that back soon.
