### ISSUE TITLE
Question about index.js exports (for components)

### ISSUE THREAD

**Issue by evgenyboxer** [ctrlplusb/react-universally#161]
I've noticed that the index.js usually looks like this:

```
import ComponentName from './ComponentName';
export default ComponentName;
```

We can use a shorter one liner:
```
export { default } from './ComponentName';
```

I can send a PR for this, if you like this too :)

**Comment by ctrlplusb** [comment]
Thanks @evgenyboxer! Any and all improvements are appreciated.  The simpler the better. :)

**Comment by evgenyboxer** [comment]
I created PR for this:
https://github.com/ctrlplusb/react-universally/pull/172 (master)
https://github.com/ctrlplusb/react-universally/pull/173 (redux)
https://github.com/ctrlplusb/react-universally/pull/174 (apollo)

Enjoy your holiday! I love this starter kit! 👍 

We should probably make a website for it!

**Comment by ctrlplusb** [comment]
Thanks @evgenyboxer !!

Something seemed strange with the Apollo PR. I think github had a hiccup. I will check in when I am back.

Thanks for your help and interest. Much appreciated!!

**Comment by ctrlplusb** [comment]
P.S. I wonder what we could.use to build the website with? 🤔

😜

**Comment by ctrlplusb** [comment]
Looks like this made it through.

Thanks everyone for helping make it happen in my absence.

x
