### ISSUE TITLE
Use .babelrc to support tooling

### ISSUE THREAD

**Issue by cyberwombat** [ctrlplusb/react-universally#163]
Right now I have to replicate the webpack babel config in order to support things like IDE linters and formatters. Wouldn't it make more sense to just use .babelrc?

**Comment by strues** [comment]
@cyberwombat I agree with you for the most part. It makes more sense to use a babelrc when you factor in tests, IDEs and the like. I personally use a babelrc broken down by env.

**Comment by ctrlplusb** [comment]
I am open to refactoring this, and then making use of the BABEL_ENV setting to specify configuration.  I don't like using NODE_ENV, especially in this context, because I want to be able to define a production/development server/client configuration. :)

**Comment by strues** [comment]
I normally use NODE_ENV for environment stuff and then specify BABEL_ENV=whatever. This way Im able to specifically target and customize to my hearts content. Also makes testing easier since usually a babelrc is necessary.

**Comment by ctrlplusb** [comment]
@strues how do you avoid duplicate between the nodes?  Does .babelrc do a better job of merging/overriding configs these days?

**Comment by strues** [comment]
@ctrlplusb My configuration at the moment is a cross between how things are currently setup as well as a .babelrc. See below. Reasoning is using Jest, I dont want to run the code through webpack. I've also got an environment for my api, which doesnt need all the stuff that React requires.

```
{
  "env": {
    "api": {
      "presets": ["latest"],
      "plugins": [
        "lodash",
        "transform-async-to-generator",
        "transform-object-rest-spread",
        "transform-class-properties",
        "transform-flow-strip-types",
       ["transform-runtime", {
         "helpers": false,
         "polyfill": false,
         "regenerator": true
       }]
      ]
    },
    "test": {
      "presets": [["latest", { "es2015": { "modules": "commonjs" }}], "react"],
      "plugins": [
        ["istanbul", {
          "exclude": [
            "**/*.test.js"
          ]
        }],
        "transform-async-to-generator",
        "transform-class-properties",
        "transform-flow-strip-types",
        "transform-decorators-legacy",
        "transform-object-rest-spread",
        ["module-resolver", {
          "root": ["./src/cms/common"]
        }],
        ["transform-runtime", {
          "helpers": false,
          "polyfill": false,
          "regenerator": true
        }]
      ]
    }
  }
}
```

**Comment by ctrlplusb** [comment]
Thanks @strues 

@cyberwombat  - I am also interested in the IDE case.  Can you select a target env for the IDE? Or can it only rely on the defaults?

**Comment by cyberwombat** [comment]
@ctrlplusb I don't have one specific thing in mind. It's more of a usage with things like mocha, work scripts that I run with babel-node, occasional Sublime plugin etc...  I use basic envs without issues with my setup.

**Comment by ctrlplusb** [comment]
@strues I am apprehensive to use the `.babelrc` as it is a json format and hides away the power of javascript from us. 

I am thinking of creating a `babelConfigFactory.js` that will allow us to output various forms of our babel config based on environments etc.

One thing I have been thinking about, could we create a wrapping script that executes `jest`, and then within the wrapping script we call `babel-register` passing in the required babel config from our `babelConfigFactory.js` call?

Does that make sense?

I am looking to make all of our tooling get processed via `babel` too, allowing us to use the exact same level of javascript across ALL of the code within the project (src and tooling).

**Comment by ctrlplusb** [comment]
@strues never mind. It becomes quite a hack.

I am gonna stick with a standard .babelrc which we will use for tooling.

**Comment by ctrlplusb** [comment]
On `next` branch.
