### ISSUE TITLE
Difference between shared/node and server

### ISSUE THREAD

**Issue by cyberwombat** [ctrlplusb/react-universally#164]
Is there a difference between the `src/server` and `src/shared/node` folders as to how Webpack handles it?  I am placing my API code in server folder. Not totally clear on what the `node` folder is for either. All I can think of is potential code for SSR that is server only. Is this correct?  Thanks for clarifying.

**Comment by ctrlplusb** [comment]
Hi @cyberwombat 

Yeah, you are completely right to put your API code in your server folder.  The `node` folder exists in the case that there is some code that is shared between the `server` and the `universalMiddlware` bundles.  Both of which are node target bundles. 

I hope that makes sense. :)
