### ISSUE TITLE
React Hot Loader error

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#165]
It looks like the latest change moving react-hot-loader initialization to [here](https://github.com/ctrlplusb/react-universally/blob/master/tools/webpack/configFactory.js#L380) has caused some issues. 

I'm getting an error on first load:
```
React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app
started. Make sure that it runs before any other code. For example, if you use Webpack, you can
add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively,
you can add require("react-hot-loader/patch") as the very first line in the application code, before
any other imports.
```

**Comment by ctrlplusb** [comment]
Woops! I accidentally checked a mess around session where I commented out the patch. It should exist in both places. I.e. the entry patch and the Babel plugin.

**Comment by ctrlplusb** [comment]
Sorted. Thanks for the report! :)

If you have upgraded to the latest version please let me know how things go for you. It's all very alpha the new code split module, but its already far more efficient that the previous one.

**Comment by carsonperrotti** [comment]
Already on the latest stuff on my personal project and working great so far. 

I'm also about to open a PR updating the apollo branch to the latest.

**Comment by carsonperrotti** [comment]
Just noticed there is now a double inclusion of react-hot-loader patch at [Line 134](https://github.com/ctrlplusb/react-universally/blob/51f788f3fa2febf5327fa7d7e50901976358809d/tools/webpack/configFactory.js#L134) and [Line 380](https://github.com/ctrlplusb/react-universally/blob/51f788f3fa2febf5327fa7d7e50901976358809d/tools/webpack/configFactory.js#L380). Is that correct or is there an extra in there?

**Comment by ctrlplusb** [comment]
Yep, I believe they have seperate responsibilities in the RHL workflow.
