### ISSUE TITLE
NOTICE: Holiday'ing for 3 weeks

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#168]
Some much needed family quality time.

I'll be leaving the laptop at home.

I still care, I just won't be able to reply until the 26th.

x

**Comment by evgenyboxer** [comment]
Have fun!

**Comment by ctrlplusb** [comment]
Back. What a vibe we had. :)

**Comment by carsonperrotti** [comment]
Welcome back @ctrlplusb!
