### ISSUE TITLE
DllPlugin: the .jsx files are they bundled?

### ISSUE THREAD

**Issue by enten** [ctrlplusb/react-universally#169]
File: [tools/development/ensureVendorDLLExists.js](https://github.com/ctrlplusb/react-universally/blob/master/tools/development/ensureVendorDLLExists.js)

I think **there is a mistake when the modules list** is computed.

Indeed, `jsx` extension [is allowed](https://github.com/ctrlplusb/react-universally/blob/51f788f3fa2febf5327fa7d7e50901976358809d/tools/webpack/configFactory.js#L177) by the [tools/webpack/configFactory](https://github.com/ctrlplusb/react-universally/blob/master/tools/webpack/configFactory.js).

But, the `getJsFilesFromSrcDir` function (in `ensureVendorDLLExists.js`) catch `**/*.js` files only.

```javascript
function getJsFilesFromSrcDir(srcPath) {
  return globSync(`${pathResolve(appRootPath, 'src', srcPath)}/**/*.js`);
}
```

How about the `.jsx` files? **I think they are skipped.**

**Comment by ctrlplusb** [comment]
Good catch.  I don't use the `.jsx` format myself so this is an oversight. :)

**Comment by ctrlplusb** [comment]
Appreciate the detailed reports!

**Comment by ctrlplusb** [comment]
Would you be interested in becoming a collaborator on this project and doing a PR to fix this? :)

**Comment by enten** [comment]
I suggest:

```javascript
const JS_FILE_EXTENSIONS = ['js', 'jsx'];

function getJsFilesFromSrcDir(srcPath) {
  return JS_FILE_EXTENSIONS
    .reduce((acc, ext) =>
      acc.concat(globSync(`${pathResolve(appRootPath, 'src', srcPath)}/**/*.${ext}`))
    .filter((file) => ~JS_FILE_EXTENSIONS.indexOf(pathExtName(file)));
}
```

So, in `buildVendorDLL` function, we don't need to check files extension anymore:
`-` ~~`const isJsFile = file => pathExtName(file) === '.js';`~~
`-` ~~`const allJSFiles = [...clientFiles, ...universalFiles].filter(isJsFile);`~~
`+` `const allJSFiles = [...clientFiles, ...universalFiles];`

> Would you be interested in becoming a collaborator on this project and doing a PR to fix this? :)

If I can make real contributions, why not :)

**Comment by ctrlplusb** [comment]
Done! That looks great. I like your style!

**Comment by ctrlplusb** [comment]
On `next` branch.
