### ISSUE TITLE
Code Splitting with Subroutes

### ISSUE THREAD

**Issue by KeKs0r** [ctrlplusb/react-universally#17]
Hi,

I am playing around with this boilerplate to solve my async routing & server rendering issues.
One thing I am not sure yet is how to solve this for nested routes.

I have for example such a Route Setup
```
.
├── Register                 # Main Route
│   └── Enter Email          # Child Route
│   └── Complete Profile     # Child Route
```

I want webpack to generate a single chunk for Register + all subroutes.
I am not sure how I could achieve this currently with:
```javascript
function resolveRegisterComponent(nextState, cb) {
  System.import('../components/Register')
    .then(module => cb(null, module.default))
    .catch(handleError);
}

function resolveRegisterChildRoutes(location, cb) {
  System.import('../Register/ChildRoutes')
    .then(module => cb(null, module.default))
    .catch(handleError);
}

const routes = (
  <Route path="/" component={App}>
    <IndexRoute getComponent={resolveIndexComponent} />
    <Route path="about" getComponent={resolveAboutComponent} getChildRoutes={resolveRegisterChildRoutes} />
  </Route>
);
```

I know that I can also asynchronous get the childroutes, but I don't know how I would tell webpack to bundle those into one package.

**Comment by ctrlplusb** [comment]
Hi @KeKs0r!

Awesome to hear that you are using this boilerplate. :)

Okay, just so I am clear with what you are after here, am I correct to assume that you are trying to get all of your source for Register and it's child routes/components all bundled into a single webpack chunk?

**Comment by KeKs0r** [comment]
@ctrlplusb : correctly. so there are obviously other main routes with child routes, but I want all "MainRoutes" to be a single chunk.

**Comment by ctrlplusb** [comment]
Okay, hmmmmm... I am not sure off hand on how to do this.  You might have to switch out to the object mapping based syntax to get more control on the routing definition, but I am not certain on that either.

I can have a play at some point later if I get a free moment.  It's an interesting case.

**Comment by KeKs0r** [comment]
I have tried to play around with it a little. I am not sure how to combine the getComponent import with the getChildRoutes, so for now I am using require.ensure 
https://github.com/KeKs0r/react-universally/blob/vatomic/src/routes/login.js
(ignore the file restructuring that I did on that branch)

Unfortunately when testing this, I see that my "login" chunk is loaded even if I am not on that route. Not sure why.

Maybe there is a better solution with `System.import`

**Comment by ctrlplusb** [comment]
Hmmm, I am not sure if using `require.ensure` will work, or if it is recommended.

I believe that `System.import` is considered the target API for use with code splitting in `webpack` v2.

Here are the webpack 2 notes: https://gist.github.com/sokra/27b24881210b56bbaff7#code-splitting-with-es6

**Comment by ctrlplusb** [comment]
At the bottom of the notes it does briefly mention code splitting with `require.ensure`, so perhaps...

**Comment by KeKs0r** [comment]
Hmm I temporarily solved it by including the all Mainroutes into the main chunk and then all children into separate chunks. It is not perfect, but not sure how to currently get around it. Let me know if you come up with some alternative ideas.

**Comment by ctrlplusb** [comment]
Sure thing, it may be worth posting your question on Stackoverflow too.  It's quite clearly illustrated.  We may get lucky and get the attention of someone who knows for sure. :)

**Comment by ctrlplusb** [comment]
@KeKs0r I am closing this issue for now.  Please do let me know if you discovered an elegant solution.  Thanks.
