### ISSUE TITLE
An issue with code splitting

### ISSUE THREAD

**Issue by kikoanis** [ctrlplusb/react-universally#170]
I am trying to use your code split component (within similar structure to react-universally) and I am hitting an issue that seems weird to me.

Here is the scenario that I use:
I am using ["semantic-ui-react"](http://react.semantic-ui.com/introduction) as an example but it could be any UI library.

In my application, suppose you have two parts; about and home
Both parts use the same Button module 

``` import { default as Button } from 'semantic-ui-react/Button'; ```

Now if I use the code split as usual, I get two chunks with similar sizes as both parts use the same module and everything works fine apart from you have two chunks that contain shared script (increases load time and defeats the whole idea of code split)

To try to reduce the sizes of the chunks, I use webpack.optimize.AggressiveMergingPlugin to try to marge what is shared between them. The plugin works fine and produces one chunk for both parts.

But when I try to use it, I hit this error message which I guess it is coming from your code-split-component
```
An error occurred whilst attempting to rehydrate code-split-component. Error: Loading chunk 92611469 failed.(…) Error: Loading chunk 92611469 failed.
    at HTMLScriptElement.n
```

Not sure what I am doing wrong here

**Comment by kikoanis** [comment]
OK.. more on this

Now if I change the About component to use home chunk as a name

```
<Match
        pattern="/about"
        render={routerProps =>
          <CodeSplit chunkName="home" modules={{ About: require('./About') }}>
            { ({ About }) => About && <About {...routerProps} /> }
          </CodeSplit>
        }
      />
```
it works fine.

Obviously this is not feasible for large applications as in this case you cannot tell which component is sharing code with what, unless you know which parts should share scripts. This could be a webpack issue and I tried to search around with no success and I am no expert in webpack.

**Comment by ctrlplusb** [comment]
Sounds like an interesting case!

**Comment by ctrlplusb** [comment]
Unfortunately I am an away till 26th now. Promise to look thereafter.

**Comment by kikoanis** [comment]
@ctrlplusb Thank you for all of your hard work on this library and wish all the best.

**Comment by ctrlplusb** [comment]
Thanks :-)

I had a think and I may have a solution to this, but I am on the way to the airport. I'll check in when I am back.

**Comment by bkniffler** [comment]
Great question, I'd be very interested in this too!

**Comment by ctrlplusb** [comment]
I dreamed up a possible cause and fix for this whilst away.  I'll try it out soon and let you know. :)

**Comment by Kimel1** [comment]
Have you fixed this bug?

**Comment by ctrlplusb** [comment]
@Kimel1 not yet.

**Comment by ctrlplusb** [comment]
Closing this in favour of: https://github.com/ctrlplusb/code-split-component/issues/21

**Comment by ctrlplusb** [comment]
@kikoanis - I have posted a comment about this: ctrlplusb/code-split-component#21
