### ISSUE TITLE
DllPlugin: better importRegex

### ISSUE THREAD

**Issue by enten** [ctrlplusb/react-universally#171]
File: [tools/development/ensureVendorDLLExists.js](https://github.com/ctrlplusb/react-universally/blob/master/tools/development/ensureVendorDLLExists.js)

I'm not an expert with regex, but **the current [importRegex](https://github.com/ctrlplusb/react-universally/blob/3339e5ddee052b624d1207ae4f708411af00423b/tools/development/ensureVendorDLLExists.js#L15) doesn't catch all import syntaxes**.

```javascript
const importRegex = /(from '|require\(')([\w\-_]+)/g;
```

* imports which use double quotes will not be caught (e.g. `require("foobar")`)
* imports with a dot/slash will be caught without parts after the first sign (e.g. `require('foo.bar')`  or `require('foo/bar')` became `foo`)
* imports of a scoped package will not be caught (e.g. `require('@foo/bar')`)
* ...and others usecases (like imports keywords in comments)

_Quick fix suggestion_
I think that we can **found a "standard" regex** (wrote by a regex sensei) **to detect most imports syntaxes**.

_Better fix suggestion_
Imports detection (throught js sources) is a critical topic. But this is a redundant need.
**May be an awesome lightweight package exists to do that?**

**Comment by enten** [comment]
The awesome [match-require](https://github.com/yiminghe/match-require) package (by yiminghe) can do the job.

Note: match-require catch relative imports/requires. We need to exclude them (with [`isRelativeModule`](https://github.com/yiminghe/match-require/blob/master/index.js#L72) which is exposed).

Because match-require tests are [too](https://github.com/yiminghe/match-require/blob/master/tests/spec/index.js#L4) [light](https://github.com/yiminghe/match-require/blob/master/tests/spec/import.js#L6):
* test ES6 imports detection (of math-require package) with [test-es6-imports.js](https://gist.github.com/pilwon/ff55634a29bb4456e0dd)
* find unit tests for node requires detection testing

**Comment by ctrlplusb** [comment]
Awesome. On my return!

Thanks for this and your continued interest :)

**Comment by enten** [comment]
You're welcome!

**Comment by strues** [comment]
I'm friends with a RegEx master. I'll ask him if he can help write some _more_ RegEx for me. Sadly, its been on my "Learn This" list for a couple of years now.

**Comment by strues** [comment]
see above

**Comment by enten** [comment]
Great! I ran [test-es6-imports.js](https://gist.github.com/pilwon/ff55634a29bb4456e0dd) with your regex. Two tests failed only:

```
[FAIL] import 'module' ;
[FAIL] import "module" ;
```

It's more visible with [regex101](https://regex101.com/r/ektSzM/1).
The two lines which failed aren't highlighted.

As you can see, I made a simple copy/past without remove double-quotes. Normally, the imports must not be caught (because they are parts of strings).

Cover all these cases will create a rewriting of [match-require](https://github.com/yiminghe/match-require).
Why not use it directly?

**Comment by strues** [comment]
I dont see why we shouldn't use match-require. Reinventing the wheel doesnt make sense

**Comment by ctrlplusb** [comment]
Hey @enten @strues 

Yep, agreed lets move to `match-require`. :)

**Comment by ctrlplusb** [comment]
Staged on `next`.

**Comment by enten** [comment]
**Be careful with `match-require` : it catch all valid imports.**

It will catch imports intended to webpack loaders like [`import 'normalize.css/normalize.css'`](https://github.com/ctrlplusb/react-universally/blob/f572ab997b8983471672695c413021d6c9ca0b7d/src/shared/universal/components/App/App.js#L7) for example.

This is why I explicitly exclude [`**/*.css` in dll options](https://github.com/ctrlplusb/react-universally/blob/c644ed93f85ba0ed76848beec53d2aeea57ebf2e/tension.js#L24). Else, `normalize.css` will be bundled in dll and causes syntax errors.

> Note: under the hood, tension [use `getImportsFromFile`](https://github.com/enten/tension/blob/7c07a6d2b963f7b3c9e2641fdc79200195f3a757/lib/utils/jsFiles.js#L14) that we previously wrote in this topic.

**Comment by ctrlplusb** [comment]
Yep, I added `normalize.css/normalize.css` the the ignores list in the `.env_example`.

Thanks for the heads up. :)
