### ISSUE TITLE
Can webpack config be patched to allow css urls

### ISSUE THREAD

**Issue by cyberwombat** [ctrlplusb/react-universally#176]
Please see this thread https://github.com/webpack/style-loader/pull/96

The gist of the issue is that when source maps are enabled its not possible to do
````
background: url('/my/img.jpg')
````
as URLs are relative to dev server. When I turn off source maps it works as people have also experienced.

 At the end of the thread is a potential suggestion but it requires no publicPath to be set. I bring this to your attention in case it's an obvious fix for you.

**Comment by strues** [comment]
As far as I know (and I could very well be mistaken) public path is required for SSR usage. The public path needs to be there and absolute (http://localhost:3000/client/) so that Webpack is able to serve the files during development.

**Comment by cyberwombat** [comment]
Ok. So this is a Chrome only issue.  My attempts at using [resolve-url-loader](https://github.com/bholloway/resolve-url-loader) so far have not succeeded.

**Comment by ctrlplusb** [comment]
Thanks for the report @cyberwombat 

I am almost certain I have done something similar and have not experienced the same issue, but let me try this out again.  It's helpful to have that issue link thanks.

**Comment by ctrlplusb** [comment]
@cyberwombat I think there was a bug in the public URL config previously. I am closing this.
