### ISSUE TITLE
Replace app-root-path by app-root dir

### ISSUE THREAD

**Issue by bkniffler** [ctrlplusb/react-universally#177]
Hi, 
I got problems with getting the root path if I use react-universally as a dependency in conjunction with npm link, instead of having everything inside the folder (as is currently the way you designed react-universally). This is due to the logic that app-root-path uses. I've found app-root-dir to be more clever about solving the issue, since it also tries process.cwd(). 

Would you consider switching? You'd just have to replace `app-root-path` with `app-root-dir`, and `toString()` with `get()`. I can also submit a PR, just say a word!

**Comment by ctrlplusb** [comment]
Go for it :-)

**Comment by BryanARivera** [comment]
+1

**Comment by bkniffler** [comment]
https://github.com/ctrlplusb/react-universally/pull/180

**Comment by strues** [comment]
Resolved in @bkniffler's PR. Closing.
