### ISSUE TITLE
hotServer.js and chokidar usage

### ISSUE THREAD

**Issue by enten** [ctrlplusb/react-universally#178]
File: [tools/development/hotServer.js](https://github.com/ctrlplusb/react-universally/blob/55ad02df699bdeebe2e68c6a3dcd6c8c6173c6be/tools/development/hotServer.js)

Why you [use chokidar to detect server changed](https://github.com/ctrlplusb/react-universally/blob/55ad02df699bdeebe2e68c6a3dcd6c8c6173c6be/tools/development/hotServer.js#L80)?
Why you won't use `compiler.watch()` method as in [HotDevelopment](https://github.com/ctrlplusb/react-universally/blob/55ad02df699bdeebe2e68c6a3dcd6c8c6173c6be/tools/development/index.js#L69) class?

**Comment by cellis** [comment]
@enten I think I can answer this for you, having dug deep into this project. So, the issue is that the server needs to be restarted, but *before* it's restarted, it needs to be released. `compiler.watch` isn't granular enough to allow you to shut down the server before hand, hence the chokidar callbacks do this, then manually trigger `compiler.run`.

**Comment by enten** [comment]
> before it's restarted, it needs to be released

**Why not call [`ListenerManager.dispose()`](https://github.com/ctrlplusb/react-universally/blob/7eaa7d832baf320a3d0bf57b1a136f0058f21386/tools/development/listenerManager.js#L31) in the [`compiler.plugin('done')` listener](https://github.com/ctrlplusb/react-universally/blob/7eaa7d832baf320a3d0bf57b1a136f0058f21386/tools/development/hotServer.js#L25)?** (only if there is no stats errors of course).
`ListenerManager.dispose()` [close the listener only if it was referenced](https://github.com/ctrlplusb/react-universally/blob/7eaa7d832baf320a3d0bf57b1a136f0058f21386/tools/development/listenerManager.js#L33). So, the [test in the anonymous `compilerHotServer`](https://github.com/ctrlplusb/react-universally/blob/55ad02df699bdeebe2e68c6a3dcd6c8c6173c6be/tools/development/hotServer.js#L73) function is useless.

> externally required modules [...] your compiler.watch wouldn't recompile for this, as it only looks at server/index.js as it's entry.

**But why restart the server if an un-required server file has changed?**

I made a test where I removed chokidar, the `compilerHotServer` funtion and used `compiler.watch()` instead of `compiler.run()` and it works perfectly!

I still think that chokidar usage is unnecessary (for that case).

**Comment by cellis** [comment]
> **But why restart the server if an un-required server file has changed?*

The files *are* required, in `server/index.js`. So even though the first run of webpack,`index.js` `require()`d files that may later change, and these changes won't be picked up, so the server will be stale. If you don't have them in the entry, they won't be recompiled while using `compiler.watch`.

**Comment by ctrlplusb** [comment]
Thanks @enten you are 100% right, webpack's watch is useful here.  I can't remember my original reasoning behind using chokidar, but with the current tools state it certainly isn't required.

I am still using chokidar to monitor changes to the webpack scripts so the dependency is hanging around. If you know of a lighter weight way of doing this please do let me know.

This is in the `next` branch.

**Comment by ctrlplusb** [comment]
@cellis thanks for your interest in this.  I would appreciate it if you could try out the next branch and let me know if it still works as expected.  I know you have some good insight into possible issues around this change.  Thanks. :)

**Comment by cellis** [comment]
@ctrlplusb I thought you were on holiday ;). Anyways, here's the scenario that chokidar helps with: suppose I have a `server/api.js` file that is included in `server/index.js`. How does using `compiler.watch` (which has `server/index.js` as it's only entry) restart the server based on changes to `server/api.js`? Is there something obvious I'm missing here?

**Comment by ctrlplusb** [comment]
Got back yesterday. :) Still dealing with the jetlag though. :)

It will be fine in the case you describe as long as the index.js references the api.js in some manner.  Webpack is intelligent enough to track the imports graph. 

I did some testing myself, adding/removing imports to/from the index.js and the webpack watch process was able to handle it all correctly.  :)

**Comment by cellis** [comment]
Ahh yes.

> When using watch mode, webpack installs file watchers to all files, which were used in the compilation process. If any change is detected, it’ll run the compilation again. When caching is enabled, webpack keeps each module in memory and will reuse it if it isn’t changed.

Makes sense now.
