### ISSUE TITLE
[redux] Strange route errors when using taskRoutes and runTasksForLocation

### ISSUE THREAD

**Issue by bslinger** [ctrlplusb/react-universally#179]
Hey there,

I'm not sure if this is a bug in your boilerplate or in react-router and react-router-addons-routes, but hopefully you can help me out.

When setting up taskRoutes to enable pre-fetching of data for SSR, there seems to be an issue with matching sub-routes. I've forked the repository and created a test case here: https://github.com/bslinger/react-universally/tree/redux

If you run that you'll see that going to /about runs the pre-fetch task successfully, but if you click the link to go to /about/sub it doesn't find the route and returns a 404, even though the Match seems to be set up correctly in About.js.

If you then remove the pre-fetch task for the /about route and try to go to /about/sub again, it succeeds (and if I put a pre-fetch task on /about/sub it works then too).

Any idea what might be going on here? It's causing me a ton of grief with my project.

**Comment by strues** [comment]
Hey bslinger, @ctrlplusb is out of town and the taskRoutes are his brainchild. That being said, I'll spend some time this evening looking into the problem you're having.

**Comment by bslinger** [comment]
Thanks @strues, that'd be great - if it needs to wait until he's back though, no problems, I've got a lot of other bits to work on 👍

**Comment by strues** [comment]
@bslinger I just cloned your fork and am going to sit down and take a look. Been bit busy with work.

**Comment by bslinger** [comment]
I'm assuming you didn't have any luck @strues ? Hopefully @ctrlplusb can see what the issue is, I'd love to get this working properly in my app :)

**Comment by ctrlplusb** [comment]
Hi @bslinger 

I am back. :)  Thanks for reporting this along with a link to an example.  I will have a play soon and report back.  There are some issues with the current router addons that I am aware of, but I can't say for sure this is the reason for your issue.  I'll have to play around first.

**Comment by bslinger** [comment]
Thanks for looking at this @ctrlplusb ! Any luck yet?

**Comment by ctrlplusb** [comment]
Hi @bslinger 

Sorry not yet, been so wrapped up in all the project stuff.  I will look soon for you sorry.

**Comment by ctrlplusb** [comment]
Hey @bslinger I am finally looking into this.

I have updated the redux branch to the latest master.

Looking at this issue my current guess is that react-router has introduced a caching mechanism on the route matching (wild guess).  The behaviour is very strange.  

I am doing more digging.  Will keep you posted.

**Comment by ctrlplusb** [comment]
https://github.com/ReactTraining/react-router/blob/v4/modules/matchPattern.js

**Comment by ctrlplusb** [comment]
@bslinger 

Ok, so this works if I change your `taskRoutes.js` definition to the following:

```js
    {
      pattern: '/about/',
      prefetchData: ({ id = 1 } : { id: number }) => dispatch(PostActions.fetch(id)),
      // deferredData: () => new Promise(resolve => setTimeout(resolve, 2000)),
    },
```

Note the "/" that I added to the end of the pattern.  This open-endedness seems to play nicer with the route match internals of react-router, allowing the Match components on the page to be hit.  It needs more debugging. Seems crazy to me thus far.

**Comment by ctrlplusb** [comment]
I have created a minimal example repo that recreates this issue and have logged an issue.

https://github.com/ReactTraining/react-router-addons-routes/issues/15

**Comment by bslinger** [comment]
Thanks for looking into it @ctrlplusb , I'll keep track of that issue and see how it goes 😀

I'll also mess around with trailing slashes - the way trailing slashes work in react-router is a whole other can of worms though 😐

**Comment by ctrlplusb** [comment]
This issue was moved to ctrlplusb/react-universally-redux#1

**Comment by ctrlplusb** [comment]
I have a feeling this one may not go away but I have been dreaming of a simpler solution that should be just as effective. I'll only get to it in the new year though.

**Comment by bslinger** [comment]
No worries man, I've got it working well enough at the moment for my development needs. I'm looking forward to seeing where you take it next :)

**Comment by ctrlplusb** [comment]
FYI, here is the library I was referring to:

[`react-jobs`](https://github.com/ctrlplusb/react-jobs)
