### ISSUE TITLE
Modular and/or React Scripts approach

### ISSUE THREAD

**Issue by strues** [ctrlplusb/react-universally#181]
This is two discussion topics rolled into this issue.

1. Thoughts on refactoring the meat of the Webpack config into their own separate files? My reasoning is there's a lot going on in the configuration and it can be overwhelming. Splitting into multiple small files would make it easier to digest, as well as present a plug-in-play environment for the end user.

2. Take the concept behind react-scripts and make the build toolkit its own installable package. Hiding the complexities from the end user.

**Comment by enten** [comment]
I wrote [wcf](https://github.com/enten/wcf) to assist webpack configuration definition (inspired by the current webpack/configFactory.js).

[That is a re-writing](https://gist.github.com/enten/0b35f2566e8a79d0c056e5bf738b9c2c) of the webpack/configFatory.js with `wcf` (I had mentioned it [here](https://github.com/ctrlplusb/react-universally/issues/167#issuecomment-261251008))

I hope it can help for Webpack config refactoring.

**Comment by kompot** [comment]
One more project approaching webpack modularity/composability that might be of some value for this issue
https://github.com/andywer/webpack-blocks

**Comment by ctrlplusb** [comment]
Some great points @strues - I shall reply more appropriately soon. :)

**Comment by ctrlplusb** [comment]
Some cross over with #192

**Comment by ctrlplusb** [comment]
Another consideration [terse-webpack](https://github.com/ericclemmons/terse-webpack)

Also liking [webpack-merge](https://github.com/survivejs/webpack-merge) which could be abstracted around.

**Comment by enten** [comment]
`terse-webpack` is awesome! I wrote [wcf](https://www.npmjs.com/package/wcf) with the same purposes.

It could be better if terse-weback allow more flexibility with [`when()`](https://github.com/ericclemmons/terse-webpack/blob/6ebcbc8b76645240914091b1aca182b517d1449f/src/api.js#L64) (which [filter on NODE_ENV only](https://github.com/ericclemmons/terse-webpack/blob/6ebcbc8b76645240914091b1aca182b517d1449f/src/api.js#L68)), allow multiple targets building with one definition, allow custom hooks and accept a context in [`getConfig()`](https://github.com/ericclemmons/terse-webpack/blob/6ebcbc8b76645240914091b1aca182b517d1449f/src/api.js#L68) which will be passed through configurations hooks/reducers.

**Comment by ctrlplusb** [comment]
Yeah, it definitely has it's limitations.  I'm excited to go through your `wcf`. :)

**Comment by ctrlplusb** [comment]
Closing in favour of #201
