### ISSUE TITLE
Is `path` module really required?

### ISSUE THREAD

**Issue by kompot** [ctrlplusb/react-universally#183]
Yarn warns "Dependency "path" listed in "dependencies" is the name of a built-in module".
I tried removing it and dev/prod seems to work fine. Is it really required?
Not that it interferes with something, just curious.

**Comment by strues** [comment]
No, its not required. You're perfectly fine leaving path out of dependencies.

**Comment by kompot** [comment]
So it should/must be dropped to reduce entropy?

**Comment by ctrlplusb** [comment]
Not sure how or why this was added! Thanks for the report.

On the `next` branch.

**Comment by ctrlplusb** [comment]
To be clear, I have removed the dependency.
