### ISSUE TITLE
[Question] react-router-redux syncHistoryWithStore

### ISSUE THREAD

**Issue by kfamilonidis** [ctrlplusb/react-universally#184]
I'm wondering if there is any way to sync the history with the redux store so to be able to use the nice handy methods push() that react-router-redux provides.

**Comment by ctrlplusb** [comment]
Hi @kfamilonidis 

Hmm, I am not sure myself.  I don't know off hand.  Why are you trying to use redux? Why not just call the api's provided by history directly?

**Comment by ctrlplusb** [comment]
Also, I would consider adding this as a stackoverflow question.  I am not sure it's specific as an issue against this project.

**Comment by ctrlplusb** [comment]
Hi @kfamilonidis I am going to close this for now.  Please let me know how you got along.

**Comment by kfamilonidis** [comment]
thanks @ctrlplusb, your comment helped me a lot to figure it out, I passed history from createHistory to BrowserRouter, and everything seemed to worked. I write it down in case someone has the same issue:

```javascript
const history = createHistory();
const store = configureStore(history,window.APP_STATE);
syncHistoryWithStore(history,store)

  <BrowserRouter history={history}>
    ...
  </BrowserRouter>

```
