### ISSUE TITLE
e2e testing recommendation for RU

### ISSUE THREAD

**Issue by cyberwombat** [ctrlplusb/react-universally#185]
In my old simple pre Webpack/React days I used to do e2e testing of my API with `supertest` which just loads the express app. Now I run into all kinds of Webpack/middleware issue which leads me to wonder what the best practice might be. What do you use to test an API with RU?  test against a running production server?  with which tools?

**Comment by strues** [comment]
@cyberwombat I run a slightly modified version of this for one of my projects. The API is separated from the server-side rendering, but Ive been testing the API right alongside my React app using Jest. However, I've still got a couple tests still relying on chai.

You can see the full repo https://github.com/strues/boldr or here is how I have an API test written https://github.com/strues/boldr/blob/master/src/api/routes/auth/auth.test.js

The server I wrap with supertest is simply `const server = http.createServer(app);`

Jest config
```
  "jest": {
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/tools/test/styleMock.js",
      "^.+\\.(css|scss)$": "<rootDir>/tools/test/styleMock.js"
    },
    "collectCoverage": true,
    "transform": {
      ".*": "<rootDir>/node_modules/babel-jest"
    },
    "testPathDirs": [
      "<rootDir>/src/cms",
      "<rootDir>/src/api"
    ],
    "setupFiles": [
      "<rootDir>/tools/test/setup.js"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/(tools|docs|node_modules|bin|flow-typed|public)/"
    ],
    "transformIgnorePatterns": [
      "/node_modules/"
    ],
    "coverageReporters": [
      "lcov",
      "text",
      "text-summary"
    ]
  }
```

Let me know if that helps you out at all.

**Comment by cyberwombat** [comment]
@strues Thank you. I see that you have a standalone server for the API which would make things a lot easier.  I may need to create a test server that just loads the API as I can't see a reasonable work around.
