### ISSUE TITLE
Chunked client scripts are not included to sw.js

### ISSUE THREAD

**Issue by bkniffler** [ctrlplusb/react-universally#190]
I found an issue on sw-precache-webpack-plugin that is most surely related: https://github.com/goldhand/sw-precache-webpack-plugin/issues/7

Styles are included, its just the scripts that are missing.

**Comment by strues** [comment]
@bkniffler have you ever used https://github.com/NekR/offline-plugin? Maybe swapping the service worker out for offline-plugin would solve the issue.

**Comment by bkniffler** [comment]
Looks very cool, thanks for the advise, I'll check it out.

**Comment by AndreasZeiser** [comment]
In my case the chunked client scripts are included. Do you see the log output `Caching static resource "PATH_TO_FILE"` during build?

**Comment by ctrlplusb** [comment]
Thanks for the report @bkniffler - I will look into my own projects and see if I am experiencing a similar issue.

**Comment by ctrlplusb** [comment]
I've played a lot with this and haven't been experiencing the same issue.  There are loads of issues with the current configuration, but we can discuss them in #188 

I am going to close this issue for now.
