### ISSUE TITLE
react-universally/tension

### ISSUE THREAD

**Issue by enten** [ctrlplusb/react-universally#192]
I've [already said](https://github.com/ctrlplusb/react-universally/issues/167#issuecomment-259140983): react-universally is awesome!
But **it lacks flexibility.**

### react-universally's limitations

**That becomes complicated if the developer wants to customize the boilerplate**: adjust files structure, use Vue.js instead of React, add another third party component (like the universalMiddleware), etc.

**The strong coupling between the [boilerplate](https://github.com/ctrlplusb/react-universally/tree/master/src) and the [great toolchain](https://github.com/ctrlplusb/react-universally/tree/master/tools) is an another limitation**: it's hard to keep the toolchain up to date when a project is forked since a while (obviously it's harder when there are several projects to update).

### tension: an universal application toolchain based on react-universally

I tried to **make react-universally's toolchain generic**: **[tension](https://github.com/enten/tension/)** was born.

It includes all the best pratices from react-universally. **It allows the developer to declare how webpack should bundle the source code : it's a [metafile called tension.js](https://github.com/ctrlplusb/react-universally/blob/tension/tension.js).**
It integrates recurrent tasks inherent in [universal application](https://medium.com/@mjackson/universal-javascript-4761051b7ae9#.pkwtye2iq) (like [assets json generation](https://github.com/enten/tension/blob/eed183519940c353b2eb8305086f5a044abddc48/lib/wcf.js#L89), [dll generation](https://github.com/enten/tension/blob/eed183519940c353b2eb8305086f5a044abddc48/lib/bundlers/web.js#L115), [dev server configuration](https://github.com/enten/tension/blob/eed183519940c353b2eb8305086f5a044abddc48/lib/bundlers/web.js#L37) for web bundles, [hot reloading](https://github.com/enten/tension/blob/eed183519940c353b2eb8305086f5a044abddc48/lib/wcf.js#L159), and [others webpack universal good practices](https://github.com/enten/tension/blob/eed183519940c353b2eb8305086f5a044abddc48/lib/wcf.js#L10)).

I tried to **make tension's fingerprint as small as possible**.

I create a [new branch (called tension)](https://github.com/ctrlplusb/react-universally/tree/tension) to test it.
In that branch, [I removed all stuff relative to the concrete toolchain](https://github.com/ctrlplusb/react-universally/commit/66a29e1f9882ab135b2f98dee05e1d83054a580f#diff-a9dffa1ad35917ae65e3fe8ee6615e78). I updated the [npm's scripts in the package.json](https://github.com/ctrlplusb/react-universally/commit/66a29e1f9882ab135b2f98dee05e1d83054a580f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) to use tension as toolchain.

> Notes:
> I voluntarily disabled the service worker feature (time to see if I incorporate it in tension).
> The `depoy` task script isn't migrate yet.

### How to test it

```bash
git clone https://github.com/ctrlplusb/react-universally -b tension react-universally-tension
cd react-universally-tension
npm install
npm run development
```

Please test it, [read my commit](https://github.com/ctrlplusb/react-universally/commit/66a29e1f9882ab135b2f98dee05e1d83054a580f) and give me a return.

**If you think that decoupling the boilerplate from the toolchain is a good thing, we can collaborate on tension to create a great universal toolchain and improve react-universally.**

**Tips**:

* `analyze`, `build`, `clean`, `development` tasks are [magically](http://www.reactiongifs.com/r/mgc.gif) provided by [tension's cli](https://github.com/enten/tension/blob/7c07a6d2b963f7b3c9e2641fdc79200195f3a757/lib/cli/index.js#L191).

```bash
# show tension usage
./node_modules/.bin/tension -h
```

* `build`, `clean` and `development` tasks can be applied for specific bundles.

```bash
# launch hot client only
npm run development -- client
# cleaning universalMw and server bundles
npm run clean -- universalMw server
```

* change log level with options [`-v|--verbose`](https://github.com/enten/tension/blob/7c07a6d2b963f7b3c9e2641fdc79200195f3a757/lib/cli/index.js#L209) and [`-d|--debug`](https://github.com/enten/tension/blob/7c07a6d2b963f7b3c9e2641fdc79200195f3a757/lib/cli/index.js#L208)

```bash
npm run development -- -v
```

* [colors are enabled](https://github.com/ctrlplusb/react-universally/blob/c644ed93f85ba0ed76848beec53d2aeea57ebf2e/package.json#L11) through option [`-c|--colors`](https://github.com/enten/tension/blob/7c07a6d2b963f7b3c9e2641fdc79200195f3a757/lib/cli/index.js#L207)

**Comment by lucianlature** [comment]
That's very nice. How about the ability to switch the server configuration?...Like `koa` instead of `express`?...

**Comment by ctrlplusb** [comment]
@enten this is a fantastic and exciting effort.  Thank you so much for all your work here.

This will take me some time to go through and consider all the implications etc before I can give you a more thoughtful response.  I am jam packed at the moment catching up with everything post holiday but I will try and make some time this week to give it a thorough run-through.

You are a legend sir.

**Comment by enten** [comment]
The developer is free to choose the server library/framework which he needs.

The only requirement for a server bundle is to [return an instance of http.Server as default export in the entry point](https://github.com/enten/tension/blob/5d0e5cd93cee4e12ec400ad3918f14d6f4e5e50e/lib/bundlers/server.js#L43) ([as react-universally does](https://github.com/ctrlplusb/react-universally/blob/d15438032e638e083e971570d5cf134f1e8ceafd/tools/development/hotServer.js#L46)).

So, you are free to use express, koajs, [happi](http://hapijs.com/api#serverlistener), or another library for your server bundle.

Express is used for web bundles only through the great [webpack-dev-server](https://github.com/webpack/webpack-dev-server). [I choose to integrate webpack-dev-server](https://github.com/enten/tension/blob/5d0e5cd93cee4e12ec400ad3918f14d6f4e5e50e/lib/bundlers/web.js#L37) to take advantage of [its useful options](https://github.com/webpack/webpack-dev-server/blob/master/lib/optionsSchema.json). So, when you [declare a web bundle](https://github.com/ctrlplusb/react-universally/blob/tension/tension.js#L2), the [`devServer` property](https://github.com/ctrlplusb/react-universally/blob/tension/tension.js#L17) will be [passed to webpack-dev-server](https://github.com/enten/tension/blob/5d0e5cd93cee4e12ec400ad3918f14d6f4e5e50e/lib/bundlers/web.js#L39).
So webpack-dev-server is used to replace the [current hotClient](https://github.com/ctrlplusb/react-universally/blob/d15438032e638e083e971570d5cf134f1e8ceafd/tools/development/hotClient.js).

**Comment by ctrlplusb** [comment]
FYI #194 

Sorry :(

**Comment by enten** [comment]
@ctrlplusb 

> Sorry

Why you said that? You think that decoupling boilerplate and toolchain is useless?

tension can handle adjustments easily: it's made for that.

Removing the universalMiddleware is very simple: remove [its declaration in metafile](https://github.com/ctrlplusb/react-universally/blob/c644ed93f85ba0ed76848beec53d2aeea57ebf2e/tension.js#L51) and integrate it source code into server folder.

**Comment by ctrlplusb** [comment]
Great to know that it's an easy configuration change only. :)

**Comment by enten** [comment]
I really hope that tension will be used as react-universally's toolchain.

So, developers will be able to start project from react-universally and maintain the toolchain up to date easily (whithout fixing lot of merge conflicts).

I definitely think that extracting the toolchain will allow us to simplify react-universally' source code and increase the separation of concerns: upgrading the toolchain by modify tension, upgrading the boilerplate by modify react-universally.

I will try to comment my commit to help you when you will review it (but writing in english is very difficult for me).

**Comment by ctrlplusb** [comment]
It will need a massive review by me before I do any sort of commitment in using `tension` specifically, but agree with the points that you are making.  As I am also using react-universally for my side projects I am also experiencing the merging issues you highlight.  I think yourself and @strues are 100% right in saying we need to separate the toolchain.  

I am doing a big cleanup parse on this project as I feel it is finally fairly stable.  There are a few things I dislike still, once I have these things sorted I am open to pushing for separating the toolchain and then also creating a cli as proposed by @bkniffler.  This will be the next evolution of the project.

P.S. The "sorry" from my earlier comment was meant to apologise because I thought I was creating more work for you when I merged the universal middleware into the server.  I didn't mean for it to sound like I was not interested in your efforts. I most definitely am interested!

**Comment by lucianlature** [comment]
@ctrlplusb So `tension` branch will end up merged into `next`?...

**Comment by enten** [comment]
@lucianlature 
> It will need a massive review by me before I do any sort of commitment in using tension specifically. [ctrlplusb]

I hope we will collaborate soon if that work is useful.

[I started to wrote the README](https://github.com/enten/tension) to help tension concerns. I want to finalize a first draft this week.

**Comment by ctrlplusb** [comment]
@enten 

Sure thing, I can understand your excitement especially as you have put so much work into this already.  It's really great what you have done, but I don't want to rush this process at all.  I wasn't involved at all with the architecture of tension, so I need to take a long and thoughtful look into it.  I need to be 100% that it will fit in with my long term plans for the project before onboarding it as a technology.  Sorry, I really don't want you to feel disappointed, but I would prefer we continue this discussion in #201.

There is lots to be done still, and once we have laid out some foundations we can move forward on what will be best for this project and everyone for the long term.

Please keep up with your amazing work though, even if we don't use `tension` as it is I can already see that it can be a very helpful toolchain for various projects.

**Comment by enten** [comment]
**I initialized the [Getting started section](https://github.com/enten/tension/#getting-started).**

There are many aspects to be documented. I think that introduce them through the getting started guide is the best way to discover them.

@ctrlplusb 

I totally understanding your point of view. And I like it: it's a best way to done good work.

I just don't want that we lose time on re-develop a new toolchain from scratch while your approach is effective. And I already said: `tension` is your work in a generic way. It's embarrassing to maintain a fork of identical tools created by a good sir without its collaboration.

But my biggest fear is to not be understood due to my poor english. I'm really open to adjust tension in a way which corresponding to the original needs and if it's compatible with react-universally's future plans.

I really like your work and would like to give some help if I can and that it's compatible with future plans.

**Comment by ctrlplusb** [comment]
Closing in favour of #201
