### ISSUE TITLE
Deprecate Webpack's Dedupe Plugin

### ISSUE THREAD

**Issue by strues** [ctrlplusb/react-universally#196]
It's been removed from Webpack v2.1.0-beta.27.

https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.27

**Comment by ctrlplusb** [comment]
Yep, lets do this.

**Comment by ctrlplusb** [comment]
I'll take of this.

**Comment by ctrlplusb** [comment]
On the `next` branch.
