### ISSUE TITLE
Clean up branches.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#197]

**Comment by ctrlplusb** [comment]
Sync with `next` and come up with guidelines for naming them.

**Comment by strues** [comment]
If we're going to create branches based off of the list we compiled for, configuration options, i believe it was, my suggestion would be to name based on feature type.

Like: 
styles/css
styles/postcss
styles/styled-components

server/express (default so probably not needed)
server/koa
server/hapi

**Comment by ctrlplusb** [comment]
Nice, I like the sub categorisation. We should maybe bring alive a new issue that lists those branches again.

Also, we need to consider a prefix for "extensions in development". Maybe "incubator/foo"

**Comment by ctrlplusb** [comment]
What about the following:

**Features**
features/styles/css

**Incubated Features**
incubator/styles/css

This leaves us opportunity to have other prefixes, such as "examples/apiServer".
