### ISSUE TITLE
Remove `colors` package and use `chalk` instead.

### ISSUE THREAD

**Issue by lucianlature** [ctrlplusb/react-universally#198]
Use [Chalk](https://github.com/chalk/chalk)
Main reason: `colors` is extending `String.prototype`, which is not the best practice around.

**Comment by enten** [comment]
colors is dependency free (it's not the case of chalk).

And it's possible to [use colors without extending String prototype](https://github.com/Marak/colors.js#usage) (check second usage example):

```
var colors = require('colors/safe');
```

**Comment by enten** [comment]
Additional note (for developers):

* `--no-colors` flag in `argv` will disable color support (in both `colors` and `chalk`).

**Comment by strues** [comment]
@ctrlplusb I've replaced colors with Chalk and created some predefined color options. Off of a branch from Next. Would you like me to push it, PR and then we can delete the branch?

**Comment by smirea** [comment]
you can choose to not extend the prototype in `colors`. Quoting from the Readme:

> var colors = require('colors/safe');

> console.log(colors.green('hello')); // outputs green text
> console.log(colors.red.underline('i like cake and pies')) // outputs red underlined text
> console.log(colors.inverse('inverse the color')); // inverses the color
> console.log(colors.rainbow('OMG Rainbows!')); // rainbow
> console.log(colors.trap('Run the trap')); // Drops the bass

**Comment by ctrlplusb** [comment]
We decided to go for `colors/safe` approach.

**Comment by ctrlplusb** [comment]
On `next`
