### ISSUE TITLE
standard

### ISSUE THREAD

**Issue by giltig** [ctrlplusb/react-universally#20]
Hi, 
Very nice boilerplate.
I would recommend thought replace eslint with standard : 
http://standardjs.com/

**Comment by ctrlplusb** [comment]
Hahaha, well yeah, this is all a matter of opinion I guess.

I did actually start this project using standard, but then decided to swap out with airbnb's eslint config.  I just had a nagging feature that ";" user count dominates those without.  

It's a case of we can't make everyone happy here, but I am trying to base my decision on code standards based on what I feel the majority of developers would already be doing.  I wonder if there are actual metrics for this?

**Comment by giltig** [comment]
Hmm. 
I actually prefer standard because it is cleaner and regarding the ;, 
I think it's better without because of chaining and jsx and a lot of stuff that makes it look weird...

**Comment by rlindskog** [comment]
Completely opinionated, but I like standard better as well. I made a standard fork if you want to use it @giltig [React Universally - Standard](https://github.com/rlindskog/react-universally-standard).  I'll keep it up to date.

**Comment by ctrlplusb** [comment]
I'll add this to the docs, thanks @rlindskog !
