### ISSUE TITLE
Why are dlls not vendored in production?

### ISSUE THREAD

**Issue by cellis** [ctrlplusb/react-universally#204]
So far loving this stack! But, i'm wondering why the vendor DLL is only used in client dev. I'm starting to write tooling adjustments to allow vendor.js in production as well. Why? Well, in long running production servers ideally you push the minimum changes possible to avoid forcing the client to redownload the entire vendor bundle ( assuming the vendor list doesn't change ). Thoughts?

**Comment by ctrlplusb** [comment]
I agree with you in principle, and you are certainly able to extend your implementation to do so. The reason it doesn't exist by default is that I couldn't get an optimised build output from webpack - as soon as I did the vendor approach webpack would bundle ALL of the source for each dependency, subverting webpack's tree shaking features. Try run the `npm run analyze` command and comparing the bundle sizes. If you find a method that creates an optimised output I would be open to including it by default.

**Comment by cellis** [comment]
Good to know. Also, it's easy to lose perspective here. While the entire index.js is maybe 500kb, a few images in a prod update could easily top 2MB or more 😄 . So it's not a huge deal.

**Comment by ctrlplusb** [comment]
Yeah it depends on ones target audience in the end I guess. :-)
