### ISSUE TITLE
I have this working with Relay ( GraphQL / Mongoose ).

### ISSUE THREAD

**Issue by cellis** [ctrlplusb/react-universally#205]
I'd like to know If anyone is interested in using Relay 0.9.3 with a modification of this stack. I've managed to get it running with [relay](https://github.com/facebook/relay) and [graffiti](https://github.com/RisingStack/graffiti-mongoose). 

There were, however, several important modifications that I had to make and drawbacks to this approach;

**Incompatible with RRv4**

First, react-router v4 is incompatible with relay. See [here](https://github.com/relay-tools/react-router-relay/issues/193) and [here](https://twitter.com/ryanflorence/status/776474787883261953). So, you won't be able to use the code-split-component. Instead you'll have to use `System.import`. I downgraded to 2.8.1, which is still a fine router.

**Tightly coupled right now to mongoose/mongodb**

I haven't explored other dbs, as mongodb suits my needs for now.

P.S. also includes [glamor](https://github.com/threepointone/glamor)

**Comment by ctrlplusb** [comment]
@cellis - interested, have you ever tried the Apollo Stack?

**Comment by cellis** [comment]
@ctrlplusb I haven't had a chance to try it, but it does look promising ( I only have so much time )! 

I like that they want to decouple from React, but I'm 100% invested in React right now, so Apollo is orthogonal to my approach.

My goal now is to tidy up a starterkit  aside from implementation details of my apps ( which mostly relates to changes around environment/deployment ).

**Comment by ctrlplusb** [comment]
@cellis We can look to integrating this into our upcoming "branches" issue if you like.

**Comment by cellis** [comment]
Sounds like a plan. I'll have to check out a fresh copy of react-universal and fish things from my app into it, as my app is deployed to heroku and didn't benefit from the clean thinking of #206, so environments, building, and especially deployment has diverged quite a bit.
