### ISSUE TITLE
Add a pre-install script that ensures the user is using node >= 6

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#207]

**Comment by code-punkt** [comment]
What about the `engines` property in `package.json`?

**Comment by ctrlplusb** [comment]
Does it throw errors/warnings?

**Comment by code-punkt** [comment]
@ctrlplusb It throws a warning unless `engineStrict` is set to `true`, in which case it throws an error. `engineStrict` is deprecated though, so the user is supposed to configure his npm to either warn (default) or error on non-matched `engines`.

Problem with all of that is, that it doesn't run on `npm run` or `npm install` inside of the package, but when you install the node module itself - so i guess it's a no-go in this repo 😞

**Comment by ctrlplusb** [comment]
Thanks for the info @code-punkt!

Ok, yeah, lets still with a post-install script then. :)

**Comment by kikoanis** [comment]
Not sure if it is really a good idea to do a post-install as all package would be already installed and built. Wouldn't be a good idea to do a pre-install. Something like this should do the trick
```
const exec = require('child_process').exec;
exec('npm -v', (err, stdout, stderr) => {
  if (err) throw err;
  if (parseFloat(stdout) < 3) {
    throw new Error('[ERROR: react-universally] You need npm version @>=3');
  }
});

exec('node -v', (err, stdout, stderr) => {
  if (err) throw err;
  if (parseFloat(stdout) < 6) {
    throw new Error('[ERROR: react-universally] You need node version @>=6');
  }
});
```

**Comment by ctrlplusb** [comment]
Good shout.

Thanks @kikoanis

**Comment by ctrlplusb** [comment]
On `next`

**Comment by ctrlplusb** [comment]
Actually... no still open :)

**Comment by ctrlplusb** [comment]
And fixed... again.
