### ISSUE TITLE
[redux] taskRoute and homepage: is there a way to match exactly

### ISSUE THREAD

**Issue by Gregcop1** [ctrlplusb/react-universally#209]
Hi. First things first. Thanks for this amazing work.

I encounter some issues with taskRoute used on homepage. My taskRoute looks like this:
```
{
    pattern: '/',
    prefetchData: () => dispatch(findAll({ limit: 4 }))
}
```

It works pretty well on the homepage but launch the task on each subroute (so all pages :)). Is there a way to match exactly a route as the react-router do?

**Comment by strues** [comment]
Glad you're enjoying the project, @Gregcop1. I'll have to defer to @ctrlplusb for any React Router 4 support. I've spent very little time with RRv4 as Im waiting until the first beta releases.

**Comment by ctrlplusb** [comment]
Hi @Gregcop1 

This is an issue with the `react-router-addon-routes` semi-official package.

I have proposed a [PR fix](https://github.com/ReactTraining/react-router-addons-routes/pull/10).

Please go vote for it. :-)

**Comment by Gregcop1** [comment]
Done. You rock ;)

**Comment by ctrlplusb** [comment]
FYI this is merged. :)

Awaiting the release...

**Comment by ctrlplusb** [comment]
This issue was moved to ctrlplusb/react-universally-redux#2

**Comment by ctrlplusb** [comment]
The new version has been published 🎉

**Comment by ctrlplusb** [comment]
Done :)
