### ISSUE TITLE
Not found page breaks SSR

### ISSUE THREAD

**Issue by smirea** [ctrlplusb/react-universally#213]
To reproduce (latest next branch just now):
 - npm run development
 - go to /about123

Console:
<img width="757" alt="screen shot 2016-12-01 at 12 03 05 pm" src="https://cloud.githubusercontent.com/assets/544097/20803768/5d3dfa70-b7be-11e6-82cc-3143777de01a.png">

**Comment by ctrlplusb** [comment]
Hey @smirea!

Thanks for the report.

**Comment by ctrlplusb** [comment]
Had a look at this and it is a bit beyond me at the moment.  The server produces the correct output but the client fails, initially producing a blank inner result for `App`.  This is particularly strange as the Match component used for miss checks is running synchronously.

It might be an issue with react router, but I think we should create a micro repo illustrating the issue before reporting it.

**Comment by strues** [comment]
Ive been looking into this issue and like @ctrlplusb, I'm leaning toward React Router is responsible.

**Comment by ctrlplusb** [comment]
Removing from 10.0.0 milestone as don't want it to be a blocker. It's not a critical big IMO.

**Comment by ctrlplusb** [comment]
FYI this issue only appears in development mode.

**Comment by ctrlplusb** [comment]
Works on latest within `next`
