### ISSUE TITLE
"flow-remove-types" not removing type imports in "/config/*" files.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#217]
Not sure why not.  It behaves correctly against the source types.

**Comment by ctrlplusb** [comment]
Issue lies on the `next` branch.

Prevents adopters from removing flow from their implementations.

**Comment by ctrlplusb** [comment]
Removing from 10.0.0 milestone as don't want it to be a blocker.

**Comment by williamoliveira** [comment]
Not sure if related but I got this error when I ran flow:remove on 10.0.1
I suspect it is because it deleted the types file before removing the imports

```
/mypath/config/private/plugins.js
  11:35  error  Unable to resolve path to module '../../tools/types'  import/no-unresolved
  11:35  error  Missing file extension for "../../tools/types"        import/extensions

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by ctrlplusb** [comment]
Yep, related.

I need to take some time to see why the `flow-remote-types` module fails in this case.  It works in others.

**Comment by ctrlplusb** [comment]
You can manually go and fix the rest... sorry.

**Comment by williamoliveira** [comment]
Yep, no problem, already done it

**Comment by ctrlplusb** [comment]
Great. :)

@williamoliveira please let me know if you see any flow bits hanging around still.  I have tested that command thoroughly.

Thanks!

**Comment by ctrlplusb** [comment]
@williamoliveira - I've fixed this. :)

Staged on `incubator/master` branch.

**Comment by williamoliveira** [comment]
Awesome, thank you
