### ISSUE TITLE
Feature branches (apologies to everyone for changing my mind... again)

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#218]
__UPDATE__

I have decided branches are too noisy and difficult to manage. We will offload features onto seperate repositories.

I have created a redux and apollo repo (see README.md for links).

We need to decide on ownership for the following feature branches and move them to seperate repos:

 - [ ] postcss-sass (created by @strues)

Here is an example workflow:

```bash
# Clone required incubator branch into target new repo folder
git clone https://github.com/ctrlplusb/react-universally -b incubator/state/redux react-universally-redux

# Enter repo folder
cd react-universally-redux

# Create a master branch
git checkout -b master

# Rename the remote
git remote rename origin upstream

# Add the new repo target as origin remote
git remote add origin https://github.com/ctrlplusb/react-universally-redux.git

# Push master rebinding it to origin
git push -u origin master

# Remove the old incubator branch
git branch -d incubator/state/redux

#
# Now you can use the following workflow to update your repo...

# Fetch the latest changes from react-universally master
git fetch upstream

# Merge any new changes from upstream master
git merge upstream/master

# Fix the merge conflicts and commit
```

**Comment by ctrlplusb** [comment]
Current tasks:

- [ ] Merge v10.0.0 into `incubator/state/redux`
- [ ] Merge v10.0.0 into `incubator/state/apollo`
- [ ] Merge v10.0.0 into `incubator/tests/jest`
- [ ] Merge v10.0.0 into `incubator/tools/docker`
- [ ] Complete `incubator/state/redux`
- [ ] Complete `incubator/state/apollo`
- [ ] Complete `incubator/tests/jest`
- [ ] Complete `incubator/tools/docker`

**Comment by cellis** [comment]
Have just checked out the new react-universally with config changes. Having a look and then will try to replay my relay changes into it.

**Comment by ctrlplusb** [comment]
Proposal: delete `postcss` feature as it's covered in the `sass` feature. The others are CSS-in-JS imps which are standalone.

**Comment by ctrlplusb** [comment]
And... rename `sass` to `postcss-sass`

**Comment by strues** [comment]
I like the idea of condensing the two.

**Comment by ctrlplusb** [comment]
We have too many CSS-in-JS implementations I think.

I think we should choose one.  `styletron` is heavily leaning itself as a universal targetted solution so perhaps this would be the most natural choice?

Sorry @lucianlature I know you have spent a lot of effort on all of these branches, but I am already seeing the complexity of management they bring to the table.  I want to cut them right down to a few choice technologies.

**Comment by ctrlplusb** [comment]
Thoughts @strues @lucianlature @bkniffler @carsonperrotti @enten?

**Comment by ctrlplusb** [comment]
Perhaps we could reconsider the strategy and have the extensions hosted seperately.

I would be happy to link them from the official readme.  @lucianlature so instead of deleting your branches we could recreate them on your github.  I would appreciate you taking ownership of them as me maintaining the merging of them all takes some effort. :)

**Comment by ctrlplusb** [comment]
Thinking about it more and more I think the separate repo strategy may be the best.  Then I don't need to limit anything, as anyone can create any extension they like and all I have to do is maintain a list of links. :)

It makes cloning off a target implementation far easier too.

**Comment by ctrlplusb** [comment]
Here is the workflow I used for creating my `react-universally-redux` repo:

```bash
# Clone required incubator branch into target new repo folder
git clone https://github.com/ctrlplusb/react-universally -b incubator/state/redux react-universally-redux

# Enter repo folder
cd react-universally-redux

# Create a master branch
git checkout -b master

# Rename the remote
git remote rename origin upstream

# Add the new repo target as origin remote
git remote add origin https://github.com/ctrlplusb/react-universally-redux.git

# Push master rebinding it to origin
git push -u origin master

# Set tracking of the master branch of react-universally
git branch --track up/master upstream/master

# Remove the old incubator branch
git branch -d incubator/state/redux

#
# Now you can use the following workflow to update your repo...

# Fetch the latest changes from react-universally master
git fetch upstream

# Merge any new changes from upstream master
git merge up/master

# Fix the merge conflicts and commit
```

**Comment by ctrlplusb** [comment]
Please let me know if you want to take ownership of any repos.  

I am going to claim the `apollo` branch too.

**Comment by ctrlplusb** [comment]
Also, please try follow the example of [`react-universally-redux`](https://github.com/ctrlplusb/react-universally-redux), i.e. have a small note at the top of the README.md that links to a FEATURE.md (sorry @lucianlature I told you BRANCH.md before).  It's best to keep the README.md the same across them to avoid merge issues on prose, which is far trickier.

**Comment by ctrlplusb** [comment]
I might steal `jest` and `styletron` as I am going to use these two a lot moving forward.  But will add you as a collaborators @strues and @lucianlature.

**Comment by lucianlature** [comment]
Ok, so that leaves me **koa2**, **glamor** and **styled-components**. Happy to host them in my GitHub account, but maybe some links from master's README.md could be also useful.

**Comment by ctrlplusb** [comment]
If you are happy to maintain them that would be awesome. :-)

Yeah follow the example I did in the react-universally-redux repo.

Also, you could consider the preact feature now ;)

**Comment by ctrlplusb** [comment]
I've added you as a contributor in the master repo.

**Comment by lucianlature** [comment]
Cool, cheers mate!

**Comment by codepunkt** [comment]
I liked the branches a lot more. When you try to combine things such as apollo, redux, glamor and jest to build a stack you like, you're basically fucked because you can't diff the repositories easily. Trying to integrate apollo into redux, it seems easier doing it on my own based on the redux repository as opposed to checking the related -apollo repository because i can't find out what code is related to apollo compared to the base repo.

**Comment by LorbusChris** [comment]
I was eyeballing styled-components, but
is there even the slightest twist with styletron? Looks amazing!

@lucianlature If you could keep the koa2 branch alive for a little while that would be great! Thats definitely something I want to investigate further. Thanks for the great work :)

**Comment by ctrlplusb** [comment]
@codepunkt - the Apollo feature already includes redux. :-)

I hear what you are saying, but I think if you choose one rep from each category(state/style/test) you can still attach them as up upstream and merge them into your target project. The projects all have their commit history maintained too. I'll play with a couple of workflows in this regard and document it. 

I'm sorry if it's a disappointment but I feel like having any more branches than what we had was gonna get noisy, and like the openness that external repos provide. Each repo can then maintain their own master/next branches and issue lists etc. It's also easier for people to take ownership which takes workload off my plate.

Let's try find a happy medium. :-)

**Comment by LorbusChris** [comment]
@ctrlplusb talking about workflows...

If all the feature branches were to be built ON TOP of master, one could also use a rebase-based workflow approach for the feature branches. I've found this to be a little less annoying than merging, but one might loose some history and in order to update one needs to force push which is probably not something everybody is comfortable with.

**Comment by ctrlplusb** [comment]
Yeah here you.we need to play. The current workflow I have been using its essentially a similar experience as merging master into a branch. Git does a great job of taking into account previous merges etc.

I guess if you plan to break away from react-universally completely in a project - then a rebase is highly appealing.

**Comment by lucianlature** [comment]
@LorbusChris I'm using **koa2** for my projects instead of **express**, so that branch will stay alive for a long time, hopefully. 

As decided, I will take care of my branches in my account.
Next to be released are the repositories for **hapi** support and **preact** integration instead of React, once they will be available I will drop the links.

**Comment by ctrlplusb** [comment]
@codepunkt

Ok, I managed to merge multiple repositories with minimal effort/issues.  I only had to deal with 2 merge conflicts even. :)

In my case I used `react-universally-apollo` and `react-universally-jest`.

Workflow:

```bash
# Select your "primary" repository (generally a "state" category I think)
git clone react-universally-apollo my-project

# Rename the "origin" appropriately
git remote rename origin upstream/apollo

# Add your project's repo remote target
git remote add origin https://github.com/ctrlpusb/my-project

# Push the current code to it, rebinding the master branch to the "origin" remote.
git push -u origin master

# Now select whatever other features you would like.
# In my case I wanted "jest"
git remote add upstream/jest https://github.com/ctrlplusb/react-universally-jest

# Fetch the latest from it
git fetch upstream/jest

# Merge into your project
git merge upstream/jest/master

# Deal with the conflicts, commit and push.

# Then any time you want updates it is a matter of repeating the above two
# steps. For example:
git fetch upstream/apollo
git merge upstream/apollo/master
```

**Comment by ctrlplusb** [comment]
Merging the yarn files are a pain.  I generally just select "merge all from theirs" and then kill the yarn file and run the `yarn` command again to rebuild it based on the current dependencies.

**Comment by lucianlature** [comment]
@ctrlplusb @LorbusChris 

Created repositories for:
 - koa2: https://github.com/lucianlature/react-universally-koa2
 - Glamor: https://github.com/lucianlature/react-universally-glamor
 - Styled Components: https://github.com/lucianlature/react-universally-styled-components

Now you can tick off from the list above these three items, and then add these links to Extensions paragraph in README.md. :)

**Comment by ctrlplusb** [comment]
Awesome work @lucianlature!

**Comment by ctrlplusb** [comment]
The styletron feature repo is live too. 

I now have a project with `apollo`, `jest`, and `styletron` merged.  :)  

Working nicely so far! :)

**Comment by lucianlature** [comment]
Yep, same here ;)

Great stuff, I'm loving it!

**Comment by ctrlplusb** [comment]
@lucianlature please check out my styletron branch and let me know if you think it looks okay. Thanks.

https://github.com/ctrlplusb/react-universally-styletron

**Comment by lucianlature** [comment]
@ctrlplusb Looks good to me, sir 👍

**Comment by ctrlplusb** [comment]
@smirea - actually, that makes a lot of sense.

Do you know if I can fork my own repo though?

**Comment by smirea** [comment]
oh... that's unfortunate, github doesn't apparently allow for you to fork yourself :| annoying. Well hopefully others do it with other feature branches ^^

**Comment by smirea** [comment]
it might be extra work, but what do you think about having a standard "canonical" branch on every feature repo, that gets updated whenever the feature repo is rebased? (that gets fast forwarded on every rebase) That way we can use the branch diff tool. 

It might even be better since the diff would reflect more relevant changes - as opposed to a fork diff which would compare against the current HEAD that probably has upstream commits

**Comment by ctrlplusb** [comment]
Some great feedback @smirea 

I'll do some investigation! :)

**Comment by LorbusChris** [comment]
The missings diffs are my main problem with that too. 

However, you can rename a fork, see [react-universally-found](https://github.com/LorbusChris/react-universally-found).

If one singular person can't maintain several forks of the same repo, maybe an organization can?

**Comment by ctrlplusb** [comment]
An organisation may be the way to go. Could be a cool option as all the features would be collocated then.

Currently you have to manually clone, add upstream remote and then do a `git diff upstream/master`.

**Comment by ctrlplusb** [comment]
Hmm, oki I tried creating an organisation and then forking within the org - it doesn't work. :(

Buuuut, if I moved react-universally into the org I could then fork the repo to produce feature repos.

**Comment by ctrlplusb** [comment]
The compare view of @LorbusChris's repo:
https://github.com/ctrlplusb/react-universally/compare/master...LorbusChris:found

It is useful. :)

**Comment by ctrlplusb** [comment]
Would rebasing of the fork affect the compare view?

**Comment by ctrlplusb** [comment]
Forks feel like the simplest/sanest solution for now... 

Yep, the compare may be running against a master that is ahead in terms of commits like you point out @smirea but I am afraid of complexity here.

Any other ideas chaps?

**Comment by ctrlplusb** [comment]
Argh, actually one other issue with forks: you can only fork a repo once. :(

Clones are unfortunately the only way forward, but perhaps we could bake in tooling that allowed you to view a diff?

Feels more complex than I would have liked though...

**Comment by strues** [comment]
Hopefully I'm not derailing the conversation too much here. I've been skimming over the recent discussions and am wondering if it might be worth looking into writing the additional repos as a yeoman generator instead?

From everything we've been discussing, it honestly feels like we're doing everything we can to give the flexibility of a yeoman generator, without actually providing a yeoman generator.

**Comment by ctrlplusb** [comment]
@strues - please, derailing is welcome! :)

Hmm, I don't think generators quite have the same value here.  In our current case we can merge together any of the repos (or branches) to suite our needs.  With generators we would need to create pre-baked combinations to achieve the similar as I don't think we could rely on a script to execute merging automatically.

**Comment by ctrlplusb** [comment]
I have been looking at this more and more and I am going to do a 180 on this decision.

I'm sorry guys, it's my bad, I was a bit hasty in this decision without involving you all.  I'll do the copy and pasting into branches.  It will be much easier to manage the branches in the repo.  I think we can have them follow the same strategy of having a FEATURE.md.  I'll just need to add more collaborators to the project if need be.

I am going to change the branching strategy though.  No more "incubation".  It'll just be straight up "feature/branchname".  This way it will feel much easier to grok and maintain the branches.  We can use the PR system to prove updates to branches.  It's the master branch which needs an "incubation" branch (i.e. `next`).

I humbly apologise to everyone!

@codepunkt - you were right! :)

I am going to start creating the branches for my feature repos now.  I'll leave the repos be for now just in case someone comes up with an amazing strategy, but for now I think the simple branching strategy is the easiest for everyone to use all round.

**Comment by lucianlature** [comment]
Oooh maaaan... 😠

**Comment by ctrlplusb** [comment]
@lucianlature - I know I know - I am so sorry for wasting your time like this.  But I think its better to do what is right for everyone.  I am really really really sorry. 

Don't worry about merging your branches.  I am already doing it for you.

**Comment by lucianlature** [comment]
Could [this](http://blogs.atlassian.com/2013/05/git-automatic-merges-with-server-side-hooks-for-the-win/) help?

**Comment by ctrlplusb** [comment]
I don't think so no. :(

**Comment by ctrlplusb** [comment]
Phew... okay I have done the initial porting.  That was some karmic reaction!

**Comment by ctrlplusb** [comment]
@codepunkt @strues @LorbusChris @bkniffler @enten @carsonperrotti @smirea 

Hey everyone!  I have finally finished the admin of bringing in and updating all branches.... phew.

I am so sorry for the rollercoaster I put you all on. And I am especially sorry to you @lucianlature - I know the time you invested in this and I can completely understand your frustration.  I'll try be a bit less hasty with future decisions.  I really hope this doesn't deter your enthusiasm for the project, which I was really enjoying.

I have updated all branches to be inline with the latest release (10.2.0).  We need a strategy for maintaining the quality of the branches, ensuring that they are always inline with the latest project version (or that they become deprecated).  Here is my proposed strategy:

 - Have a `next` branch which lines up all changes to become a new `master` version.
 - When we are happy with the state of `next` and are ready for a push we start a PR update process of all existing branches, merging in the changes from `next`.
 - Then we can deploy the new version side by side to accepting all PRs.

Thoughts?

**Comment by enten** [comment]
As I said last night: manage features through git's branches is a good strategy (better than develop an useless abstraction layer to allow dynamic/runtime feature loading).

And you're right: you need to be clear about the feature branch's lifecycle. Maybe it's the moment to start a contributing guide (based on your post above).

I'm not a git expert but the strategy that you describe sound good for me.

**Comment by ctrlplusb** [comment]
Closing this...

**Comment by carsonperrotti** [comment]
Just got caught up here. I agree with @enten's point above here. Happy to help out and still contribute as much as I can to the branches. I'll have much more time too as we start approaching the holidays.
