### ISSUE TITLE
[next] Fix serviceworker & offline page fallback

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#219]

**Comment by ctrlplusb** [comment]
This has fixed by adding an enhanced AppCache configuration to handle the offline cases.  We now also get caching of each request to support a proper offline experience.  Pretty cool.

**Comment by ctrlplusb** [comment]
On `next`

**Comment by ctrlplusb** [comment]
Actually, this needs more testing...

**Comment by carsonperrotti** [comment]
I was just coming here to open this issue. Just deployed my lated build which is based off of `next` and ever time I close the tab and come back, it reports me as offline. Keep me posted on this one or let me know if I can help in any way.

**Comment by ctrlplusb** [comment]
I am dumping the use of AppCache too, because:

"Using the application caching feature described here is at this point highly discouraged; it’s in the process of being removed from the Web platform"

**Comment by ctrlplusb** [comment]
Ooooooh, think I finally hit a good idea on how to get an offline first experience working with this type of SSR setup!  Crossing fingers.

**Comment by ctrlplusb** [comment]
It works!  SOOO awesome.  We can have a proper offline-first experience now! :)

**Comment by ctrlplusb** [comment]
Pushed!

Would appreciate you testing this @carsonperrotti :)

**Comment by carsonperrotti** [comment]
Works great for me @ctrlplusb

**Comment by strues** [comment]
Works perfect. nice job
