### ISSUE TITLE
Passing props to children

### ISSUE THREAD

**Issue by giltig** [ctrlplusb/react-universally#22]
Hi,
I've seen you've chosen React Router.
How would you pass props to Route children ?

**Comment by ctrlplusb** [comment]
Hmmm, there are various techniques.

What are you trying to achieve?

Have you referenced their docs?

 - https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md

**Comment by giltig** [comment]
I would like to pass props other than children - actually I would like to pass props to my sub components, and createElement is not a good solution

**Comment by ctrlplusb** [comment]
Hmm, still a very generic description of your problem.  I can't really advise on that.

I have implemented a project using this boilerplate where I use [`redux`](http://redux.js.org/) to manage my state.  It's very simple to connect components at any level of your component tree to the state.  Additionally, as my state relies on AJAX calls I used `redial` to manage this on the server.  I plan to release this project as open source soon'ish.  It may be a helpful reference to you.

**Comment by geowarin** [comment]
A thing I like to use is the [createElement](https://github.com/reactjs/react-router/blob/master/docs/API.md#createelementcomponent-props) method in react-router to pass props to all the pages:

```js

function elementFactory(store) {
  const actions = createActions(store);
  return (Component, props) => <Component actions={actions} {...props} />;
}

<Router history={history} createElement={elementFactory(store)}>
    {routes}
</Router>
```

**Comment by ctrlplusb** [comment]
That's awesome @geowarin - I've never used this API before.  I think this may help with another issue on this repo. Thanks!
