### ISSUE TITLE
v10 release

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#221]
@strues @enten @carsonperrotti @bkniffler 

Finally have all the issues fixed that I wanted addressed for v10.

Personally I am happy with how the project has evolved since the v9 release.  To be honest I feel like this is a v1 release.  It feels the most stable and considered version of the project by far.

I really have to thank the four of you for all of your valued input over the past few weeks.  This release would be nowhere near what it is today without the efforts and comments of you all, so a HUGE thanks goes out to you all.

I would appreciate if you raised any final concerns on what is in the `next` branch before we go ahead and release it as v10. 

Please don't be afraid to say if you think an aspect of it needs work.  Especially around the configuration and comments.  A big thing for me is to keep the application structured and commented in a way that anyone can come to the project and adjust it to their own needs.

Thanks again!

**Comment by ctrlplusb** [comment]
The biggest new features to sense check:

 - configuration
 - offline support
 - revised webpack configs

**Comment by ctrlplusb** [comment]
I am going to add a "contributors" section to the package.json as well as the licence.  Please share your details with me if you are okay with me adding you.

**Comment by enten** [comment]
Generate stats for `webpack-bundle-analyzer` through its plugin (remove webpack cli usage) and add its options in the project config (to allow user to switch between static or server reports).

Use `webpack-dev-server` (its class `Server`) in the hot client server (instead of the custom express server). This sound more v11.

> I am going to add a "contributors" section to the package.json as well as the licence. Please share your details with me if you are okay with me adding you.

Of course.

```
Steven Enten <steven@enten.fr>
```

**Comment by ctrlplusb** [comment]
> Generate stats for analysing-bundle-analyzer through its plugin (remove webpack cli usage) and add its options in the project config (to allow user to switch between static or server reports).

What is your intention behind analysing the server?

**Comment by carsonperrotti** [comment]
You're more than welcome to add me to the contributors list. 
``` Carson Perrotti <carsonperrotti@gmail.com> ```

**Comment by strues** [comment]
Pulling down the latest next branch. Will play with it and report back with any issues.

**Comment by Kimel1** [comment]
I'm looking forward to release. Huge thanks to all of you)

**Comment by ctrlplusb** [comment]
@Kimel1 yep - that will be the first branch that gets updated. :)

**Comment by ctrlplusb** [comment]
Thanks @strues :)

Are you happy to be added officially within the contributors list?

**Comment by strues** [comment]
Sure @ctrlplusb that sounds good to me.

**Comment by ctrlplusb** [comment]
@enten nice, what details should I use? :)

**Comment by Kimel1** [comment]
@ctrlplusb I'v noticed one weird thing in master and next branch. When I load page, there is some 1 sec delay to css been loaded. But if I turn off JS in Google Chrome, then CSS will never loaded  and it's no cool, because one great feature of SSR is that user with JS turned off can see website as other people.
Can you reproduce this bug on your side and give some explain about it?

**Comment by ctrlplusb** [comment]
@Kimel1 this should only be the case when in development mode, can you try production please?

This is because we rely on the webpack dev server to load and hot reload the css, which happens via javascript, hence the initial delay.

**Comment by Kimel1** [comment]
@ctrlplusb I'v followed your guide to deploy on now (it's awesome)  https://react-universally-xrjgublxuv.now.sh and it seems that all works perfectly css!
Thank you for explanation. I guess you need mention this in Readme or some FAQ.

**Comment by strues** [comment]
Here's something to make note of. Using babel-plugin-module-resolve will require adding additional items to the DLL ignore. As of right now I dont have a proposal for a solution.

See below:

```
[ 'react',
// ....
  'types/react',
  'components/index',
  'state/index',
  'core/utils',
  'core/config/base',
  'theme/styles/main.scss',
  'state/dux/notifications',
  'react-router/lib/Link',
  'superagent',
  'nock',
  'normalizr',
  'chai',
  'immutable',
  'dnd-core',
  'react-dnd-html5-backend',
  'state/reducers',
  'theme/Boldr/PageTemplate',
  'state/dux/auth',
  'react-router',
  'components/Layout',
  'redux-form',
  'components/Button',
  'date-fns',
  'types/models',
  'core/index',
  'styled-components',
  'core/config/layouts',
  'state/dux/ui',
  'state/dux/article',
  'state/dux/tag',
  'components/Avatar',
  'core/utils/dndContext',
  'immutability-helper',
  'react/lib/update',
  'core/utils/deepRemove',
  'react-dnd',
  'redux-form-material-ui',
  'material-ui/RaisedButton',
  'material-ui/MenuItem',
  'core/api',
  'core/config/notifications',
  'material-ui/List',
  'material-ui/Avatar',
  'material-ui/svg-icons/av/new-releases',
  'material-ui/Drawer',
  'material-ui/svg-icons/action/settings-applications',
  'material-ui/svg-icons/editor/insert-link',
  'material-ui/svg-icons/communication/import-contacts',
  'material-ui/svg-icons/device/dvr',
  'material-ui/svg-icons/file/cloud-upload',
  'material-ui/svg-icons/action/home',
  'material-ui/svg-icons/action/dashboard',
  'material-ui/svg-icons/social/people',
  'material-ui/svg-icons/content/content-copy',
  'material-ui/svg-icons/action/list',
  'material-ui/Card',
  'components/Widget',
  'material-ui/AppBar',
  'material-ui/Paper',
  'material-ui/IconButton',
  'material-ui/svg-icons/action/delete-forever',
  'material-ui/svg-icons/editor/mode-edit',
  'material-ui/IconMenu',
  'material-ui/svg-icons/navigation/expand-more',
  'material-ui/Toolbar',
  'core/config',
  'state/selectors',
  'redux-mock-store',
  'redux-thunk',
  'material-ui/RadioButton',
  'boldr-editor',
  'state/dux/post',
  ... 9 more items ]
```

**Comment by ctrlplusb** [comment]
@strues yeah, that looks like a headache.  Lets stay away from that. :)

**Comment by ctrlplusb** [comment]
@Kimel1 yep, you will get a new url every time you deploy.  It's immutable hosting. :)

`now` is so rad.

**Comment by ctrlplusb** [comment]
@strues - one idea: parse the package.json and use it to filter that list.

**Comment by strues** [comment]
Its not terrible and certainly isnt breaking anything to prevent release. After seeing the console output, if you're using babel-plugin-module-resolve, you'll need to ignore the shortened paths.

**Comment by LorbusChris** [comment]
There are two issues I'm experiencing (both in development, haven't tested prod yet):
* The Menu Logo is not served
* The console states the following upon startup:
```
Server listening on port 1337
==> SERVER -> Running on http://:::1337 with latest changes.
```

**Comment by Kimel1** [comment]
If I understand right, all react components defining as functions with return, where return is render function analogue.
Ok, but how I must use constructor() or componentDidMount() in this case? 
I have never worked with react components as functions(
Usually I use this "class SomeComponent extends React.Component {  ". 
Is there a some good guide or tutorial for explain how to develop component in this boilerplate.

**Comment by ctrlplusb** [comment]
@strues - to be clear: the `babel-plugin-module-resolver` shouldn't be included/used in the `next` branch.  Are you seeing it in your own?

**Comment by ctrlplusb** [comment]
@LorbusChris 

> The Menu Logo is not served

Do you mean the `src/shared/components/App/Header/Logo/logo.png` logo? Are you seeing any errors in your console?

**Comment by LorbusChris** [comment]
@ctrlplusb 

In Chrome and Opera:
`Failed to load resource: http://localhost:1337/client/93a2b06556deb55b214bb0cfbce8a4e0.png the server responded with a status of 404 (Not Found)`

In Firefox there is an additional warning about CSP blocking a script:
`
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://localhost:1337 http://cdn.polyfill.io 'nonce-0ef30069-2803-48b3-812b-10f6c7af34ef' http://localhost:7331").
`

**Comment by Kimel1** [comment]
@ctrlplusb  Thank you
I changed src\shared\components\App\Header\Menu\Menu.js to 
```
/* @flow */

import React from 'react';
import { Link } from 'react-router';



export default class Menu extends React.Component {

  componentDidMount() {
    console.log('poop');
  }
  
  render() {
    return (
      <ul style={{ marginTop: '1rem' }}>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/about">About</Link></li>
      </ul>
    );
  }
}
```
and it's works perfect. Is it good to use this style of component, or functional components is better?

**Comment by LorbusChris** [comment]
@ctrlplusb: PS: In Production, the image is served fine and neither of those warnings occur

**Comment by ctrlplusb** [comment]
Thanks @LorbusChris.

I have removed the `child-src` definition as this is related to web workers and doesn't have wide browser support.  I figure if you are delving into advanced project configuration that uses web workers you'll likely be fine with extending the CSP config. :)

The CSP warning appears to look like there is an eval'ed script or something in the webpack output.  As soon as I added "'unsafe-eval'" to the CSP it worked.  I will have to investigate this further.

In regards to the image not loading in development.  That is really strange.  I tried my FireFox install (v43) and it worked without an issue.  Strange case indeed.

**Comment by Kimel1** [comment]
@ctrlplusb 
Here is some unstable behavior during bundling. 
I add `import 'bootstrap/dist/css/bootstrap.css'; ` to App.js (and also install related package     `"bootstrap": "^4.0.0-alpha.5"`) 
And if I `npm run development ` then in browser console I get 
```
__dev_vendor_dll__.js:15169
 Uncaught Error: Module parse failed: C:\react-universally-next\node_modules\bootstrap\dist\css\bootstrap.css Unexpected token (8:5)
You may need an appropriate loader to handle this file type
```

But I tried to `npm run build` and delete "build" folder. And in 1/10 case when I open page, all works good but in 90% cases I get error

**Comment by strues** [comment]
Try saving a file after you receive the error. Sometimes saving will _kick it in gear_ and workout the kinks.

**Comment by Kimel1** [comment]
I'm experimentiong and find out one thing.
If I delete build folder and run
`npm run build`
`npm start`
THEN ALL RIGHT and no errors in 100%

but if after I run `npm run development` I'v got same error

**Comment by Kimel1** [comment]
I'v modified project.js:154  `ignores: ['normalize.css/normalize.css', 'bootstrap/dist/css/bootstrap.css'],`
And the problem solved. But I noticed another one
`GET http://localhost:8080/client/93a2b06556deb55b214bb0cfbce8a4e0.png 404 (Not Found)`

**Comment by LorbusChris** [comment]
@ctrlplusb The image 404 bug is gone.
I suspect this was caused by some node hiccup due to (at first unsuccessfully) changing versions using `n` earlier. 
Sorry for the troubles!:see_no_evil:

**Comment by ctrlplusb** [comment]
@LorbusChris  @Kimel1 

There was a genuine bug with the image loading. Fixed! Thanks for the report. :-)

**Comment by ctrlplusb** [comment]
@Kimel1 yeah I think that is in the FAQ. I will double check. Anything that needs to be processed by the main webpack config loaders needs to be added to that ignores list.

**Comment by ctrlplusb** [comment]
@LorbusChris 

> The console states the following upon startup:
>     Server listening on port 1337
>     ==> SERVER -> Running on http://:::1337 with latest changes.

Fixed. Thanks for the report. :)

**Comment by ctrlplusb** [comment]
@Kimel1 I have updated the FAQ section in regards to the issue you experienced.

Thanks for the report.

**Comment by ctrlplusb** [comment]
Released!

**Comment by enten** [comment]
:tada: Awesome!

How about the [npm's package](http://npmjs.com/package/react-universally)?
