### ISSUE TITLE
Docker support and example?

### ISSUE THREAD

**Issue by amcsi** [ctrlplusb/react-universally#223]
It would be great if this project could be Dockerized. At the moment I'm having some trouble with it.

It appears that the environment variable that are used get determined on `npm run build` and not `npm run start`. This is problematic, because the Docker style is to have your container built environment-agnostically, and it is when you run the container where you should be passing environment variables.

Unfortunately this project ignores any environment variables when running `npm run start`

**Comment by ctrlplusb** [comment]
@amcsi the newly released v10 of this project respects runtime environment configuration. Have you tried it? Just releases about an hour or two ago.

**Comment by amcsi** [comment]
No way, nice one!

I'm closing this then.

When is the redux branch going to be updated accordingly?

**Comment by ctrlplusb** [comment]
@amcsi no problem.

Hopefully soon. :)  It will the first branch that I upgrade.
