### ISSUE TITLE
Could we make Happypack optional?

### ISSUE THREAD

**Issue by williamoliveira** [ctrlplusb/react-universally#226]
It sure is great but I think it adds too much complexity and a lot more surface to break, it feels like the gains do not justify for smaller apps

**Comment by ctrlplusb** [comment]
We could consider a branch "without-happypack".

I just worry having a toggle between with or without in by default will make the configs even more obscure.

**Comment by code-punkt** [comment]
There's already tons of branches. I don't see how this will move the project forward in any meaningful way.

**Comment by ctrlplusb** [comment]
You are right about the branch numbers. It's an experiment, that may need some evolution and consideration.

**Comment by ctrlplusb** [comment]
Sorry closing this @williamoliveira - I am too nervous of even more complexity.  I am open to investigating other means of optimising builds, there is also the [`hard-source-webpack-plugin`](https://github.com/mzgoddard/hard-source-webpack-plugin) which would leave your loaders alone.  We would need to get some metrics together on a large project.

**Comment by ctrlplusb** [comment]
We also need the following issue resolved: https://github.com/NekR/offline-plugin/issues/148

**Comment by williamoliveira** [comment]
All right, understandable

**Comment by codepunkt** [comment]
@williamoliveira the proposition was a good/interesting one nevertheless. If this project had a well-defined goal or target audience (large apps, small apps, "enterprise" apps or w/e), one could decide to pursue or not pursue feature requests based on that.

Imho, when having SSR and happypack its perfect as a base to start larger or at least very specialised products/apps - but thats just my 0.02$.

**Comment by NekR** [comment]
Just in case, there a fix for that `offline-plugin` issues on the way: https://github.com/NekR/offline-plugin/pull/172
