### ISSUE TITLE
Remove the HappyPack threadpool.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#227]
Looks like it still gives issues, even in v3.

Need to set the thread count explicitly in the helper.

**Comment by strues** [comment]
Really? I haven't noticed. What sort of issues is it causing?

**Comment by ctrlplusb** [comment]
Issues when killing the development server and starting it again (manually).

**Comment by ctrlplusb** [comment]
Maybe it was due to something else?

**Comment by strues** [comment]
I'll recheck and see if I can break it in a couple minutes. I need to wrap some work related stuff up first.

**Comment by strues** [comment]
I experienced the HappyPack issue twice this afternoon. We'll need to revert back to not using thread pooling. Im intrigued by what's causing the problem because I can't reliably reproduce it. Are you able to?

**Comment by ctrlplusb** [comment]
On `incubator/master`
