### ISSUE TITLE
SourceMaps not loaded on dev server

### ISSUE THREAD

**Issue by smirea** [ctrlplusb/react-universally#229]
running `npm run development` with latest `master` (the paths refer to the build dir and the line numbers are in the 1000s)

<img width="1225" alt="screen shot 2016-12-08 at 3 08 38 pm" src="https://cloud.githubusercontent.com/assets/544097/21025910/554ac128-bd58-11e6-96c9-4002f958af02.png">

**Comment by ctrlplusb** [comment]
I have a fix for this. :)

It's going to a be a thanks to @enten - I took his idea from tension. :)

**Comment by enten** [comment]
Using the BannerPlugin in entry point only to enable the sources map?

**Comment by ctrlplusb** [comment]
@enten by using the childing process spawn technique. ;)

**Comment by ctrlplusb** [comment]
Staged on `incubator/master`
