### ISSUE TITLE
 How to keep project always updated?

### ISSUE THREAD

**Issue by Kimel1** [ctrlplusb/react-universally#233]
If I develop some app using your boiletolate and for example in next week you committed critical bug fix. How could I update my current project automatically?

Or I need do all fixes manually ?

**Comment by ctrlplusb** [comment]
Hey @Kimel1 

I am away from keyboard at the moment but I will detail my workflow for you later.

**Comment by Kimel1** [comment]
@ctrlplusb
I'm looking forward to it

**Comment by ctrlplusb** [comment]
Okay, you could follow a similar strategy to the following:

```
# First clone this repo
git clone https://github.com/ctrlplusb/react-universally my-project

# Go into your project
cd my-project

# Now rename the "origin" git remote to "upstream"
git remote rename origin upstream

# I would then recommend creating a hosted repository for your 
# project (e.g. on github, or a free private on bitbucket)
# Then add your newly created repository as the "origin"
# remote like so: (for example, you need to put in the proper url)
git remote add origin ssh://git@bitbucket.org/Kimel1/my-project.git

# Then push the master branch content to the new "origin" remote
git push -u origin master

# You can now code/commit/push to origin as normal.
# If you want to at some stage get new changes from the
# react-universally project, then do something like this:

# First fetch the latest changes
git fetch upstream

# Then merge them into your project
git merge upstream/master

# You will have to deal with merge commits most likely
# I would get comfortable with a good merge tool. I use
# Atom Editor and they have a cool package called 
# merge-conflicts which does the job okay.
# After you have completed the merge you can commit
# and continue
git commit
```

Hope that is helpful.

Of course you need not clone the master of this repository, you could clone off one of the upcoming feature branches too. The rest of the steps would be the same or similar.

**Comment by Kimel1** [comment]
@ctrlplusb  This info can be helpful for others too, so you might add this to FAQ

**Comment by ctrlplusb** [comment]
Staged on `incubator/master`

**Comment by williamoliveira** [comment]
Is there a way to remove flow from upstream before merging? the flow types makes the conflict resolving a little bit harder for those who don't use it
