### ISSUE TITLE
Making a git commit restarts the dev server

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#243]
Noticed a weird behaviour where making a git commit / push while the dev server is running triggers a webpack build and restarts. Anyone else or just me? 

Running v10.1

**Comment by ctrlplusb** [comment]
Hmm, that is strange...

**Comment by ctrlplusb** [comment]
How is `10.1` running for you otherwise?

**Comment by carsonperrotti** [comment]
Other than that one weird quirk, It's running like a champ!

**Comment by ctrlplusb** [comment]
Closing this as a quirk. :)
