### ISSUE TITLE
Koa 2 Branch

### ISSUE THREAD

**Issue by immysl** [ctrlplusb/react-universally#244]
I downloaded the code of the Koa 2 incubator branch just a couple of hours ago and now it is missing :open_mouth: It is a really good setup for exactly what I wanted i.e. React with Koa 2 and Webpack 2. Have to thank you a lot for it :smile: 

Anyway I don't see branch anymore. Are you guys planning to drop support for Koa 2?

**Comment by lucianlature** [comment]
`Koa2` feature is now sitting in its own repository at https://github.com/lucianlature/react-universally-koa2

**Comment by immysl** [comment]
That's great to know :smile:

**Comment by lucianlature** [comment]
Use this workflow to merge `react-universally` with `react-universally-koa2`:

```bash
# Select your "primary" repository (generally a "state" category I think)
git clone react-universally my-project

# Rename the "origin" appropriately
git remote rename origin upstream/master

# Add your project's repo remote target
git remote add origin https://github.com/ctrlpusb/my-project

# Push the current code to it, rebinding the master branch to the "origin" remote.
git push -u origin master

# Now select whatever other features you would like.
# In my case I wanted "koa2"
git remote add upstream/koa2 https://github.com/lucianlature/react-universally-koa2

# Fetch the latest from it
git fetch upstream/koa2

# Merge into your project
git merge upstream/koa2/master

# Deal with the conflicts, commit and push.

# Then any time you want updates it is a matter of repeating the above two
# steps. For example:
git fetch upstream/koa2
git merge upstream/koa2/master
```

**Comment by ctrlplusb** [comment]
Hmm, actually it looks nicer cloning from the master and adding features like you have done.  I will update the readme.

**Comment by immysl** [comment]
I see that a new branch is now available for Koa 2. So does it mean that the new repo created for the Koa 2 version is not valid anymore?

**Comment by ctrlplusb** [comment]
Hi @immysl - apologies for this.  I completely decided against the separate repos in the end as it causes issues with being able to see differences between the master and features.  

The branch on this repository is the one to use.  All the branches are up to date and will be kept strictly up to date with the latest version on master.  This then allows you to merge in multiple branches to your own cloned project.

Apologies again.

**Comment by immysl** [comment]
@ctrlplusb I understand the reasoning behind it and hope it is for the best :smile: Will update the code from the branch instead from now on.
