### ISSUE TITLE
react-toolbox-2beta

### ISSUE THREAD

**Issue by devdlabs** [ctrlplusb/react-universally#248]
Hello guys, Did anyone try new react-toolbox-2 version webpack configuration?

**Comment by ctrlplusb** [comment]
I suspect you could use the postcss-sass branch and expand it?

**Comment by devdlabs** [comment]
@ctrlplusb I tried that and other options too, but somewhere I miss configured. Will look at it in next week. Thank you.

**Comment by ctrlplusb** [comment]
Great, please let me know how it goes.

I am going to close this for now. :)
