### ISSUE TITLE
npm run deploy fails at "babel-node tools/scripts/deploy"

### ISSUE THREAD

**Issue by protoEvangelium** [ctrlplusb/react-universally#250]
**Just testing out the React-universally starter kit and I get this error:** 

```
Tell the author that this fails on your system:
 babel-node tools/scripts/deploy

Cannot find module '/home/nowuser/src/build/server'

Command node build/server ended with code 1
```

**Here is what I am doing:** 

- Followed the 4 step setup to deploy out of the box (**_I have not made any changes_**)
- Using Node version 7
- Windows 10

**Comment by ctrlplusb** [comment]
Hi, thanks for the report. I'll look into this soon.

**Comment by LorbusChris** [comment]
It looks `npm run build` has to be run before deploying.

I see 2 options here: Either the build step is added directly to the deploy command, or this step is added to the README (making it 5 easy steps :)

**Comment by LorbusChris** [comment]
BTW with yarn we can also do `yarn run [cmd]`

**Comment by protoEvangelium** [comment]
Thanks @LorbusChris  @ctrlplusb 

I ran `npm run development` and started working on the project.  Then I can back to the url that `npm run deploy`  created about a couple hours later and it worked!
