### ISSUE TITLE
Exporting a Class instead of a Function breaks HMR

### ISSUE THREAD

**Issue by smirea** [ctrlplusb/react-universally#252]
in DemoApp.js

instead of:

```
export default function DemoApp () {
```

do:

```
export default class DemoApp extends React.PureComponent {
```

Now hot reloading will behave like it's working (console output happens) but the content does not actually update

**Comment by ctrlplusb** [comment]
Wow, strange case - what happens if you seperate the `export default...` from the class declaration.  I know RHL has a caveat that you need to be exporting `const` values. Perhaps there is a strange babel transformation case happening in the above that breaks this semantic?

**Comment by smirea** [comment]
This seem to be specifically a react issue with `PureComponent` + HMR

doing the following works:

```
export default class DemoApp extends Component 
```

this does not work:

```
export default class DemoApp extends PureComponent 
```

doing the `export default` separately has no effect.

Note: all my sub-components all extend `PureComponent` and they work with HMR, but only if the root component **is not** a PureComponent
