### ISSUE TITLE
Problems with CSP on /graphiql in feature/apollo

### ISSUE THREAD

**Issue by codepunkt** [ctrlplusb/react-universally#253]
Graphiql has an inline script that violates the CSP directive, neither having a nonce nor a hash. I was wondering if we could fix this by simply omitting the helmet csp middleware for the graphiql route (which is only served in development anyways).

**Comment by maximblack** [comment]
The same with Redux DevTools, when dispatching an action. Violates the CSP

**Comment by codepunkt** [comment]
@maximblack Can you elaborate on that?

I've fixed the problem with graphiql by excluding csp middleware on graphiql route in development.
Maybe there's an easy solution for your problem aswell.

**Comment by LorbusChris** [comment]
> I've fixed the problem with graphiql by excluding csp middleware on graphiql route in development.
@codepunkt I'm curious how you did that, ming sharing? I thought CSP configs were global

**Comment by carsonperrotti** [comment]
I have this in my project with Apollo and experience no issues with GraphiQL.

```
if (process.env.NODE_ENV === 'development') {
  // Graphiql needs the following
  cspConfig.directives.scriptSrc.push('cdn.jsdelivr.net');
  cspConfig.directives.scriptSrc.push("'unsafe-inline'");
  cspConfig.directives.styleSrc.push('cdn.jsdelivr.net');
}
```

**Comment by strues** [comment]
That is correct @carsonperrotti. I've played around with the graphql branch and everything works a-okay with the above CSP

**Comment by codepunkt** [comment]
Allowing `unsafe-inline` in dev environment somehow *seems* wrong to me. I'd rather restrict that to the graphiql url or disable csp altogether on that url. To do so, i've made csp middleware a named export and excluded it from the security middlewares default export array.

**Comment by codepunkt** [comment]
@ctrlplusb These are the options, in my preferred order (based on keeping the codebase as simple as possible). You decide, i open a PR! :)

1. Remove graphiql endpoint altogether, since [apollo devtools](https://dev-blog.apollodata.com/apollo-client-developer-tools-ff89181ebcf#) have it included
2. Disable CSP on graphiql url in development
3. Add `unsafe-inline` as an additional option to the graphiql url in development

**Comment by ctrlplusb** [comment]
Yes to all 3! :)

Thanks @codepunkt 👍

**Comment by codepunkt** [comment]
@ctrlplusb i thought of those as mutual exclusive. now i'm confused. WAT.

**Comment by ctrlplusb** [comment]
Doh, my bad.  I completely misinterpreted that. 😊

Number 1!!

Thanks @codepunkt 👍
