### ISSUE TITLE
Proposal - add modernizr and modernizr-loader

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#256]
Allows for easy:

```js
import Modernizr from 'modernizr';

if (!Modernizr.promises) {
    // ...
}
```

Progressive enhancement is a cornerstone of a modern application.

Do you guys think modernizr is the "go to" for this type of feature?

**Comment by ctrlplusb** [comment]
Anyone use anything other than modernizr for feature checking?

**Comment by Kimel1** [comment]
It's  a good idea.
Can you describe most common cases in which you use modernizr? 
(Just to share experience)

**Comment by rlindskog** [comment]
@Kimel1  Modernizr is used to detect if any given browser has a certain feature.  Its used for detecting browser support for touch, canvas, promises, or anything on [this list of features](https://modernizr.com/docs#features).

I use it to detect support for the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API).  If a browser doesn't support it, I find other ways to animate my website.

**Comment by rlindskog** [comment]
@ctrlplusb This would be nice!  I already use modernizr-loader with react-universally on a website I'm working on. Do you think this would be a new feature branch or on the master?

**Comment by ctrlplusb** [comment]
@rlindskog I am inclined to think that master is the best place for it.  It feels more like development tooling. An opt-in usage within your code. :)

**Comment by rlindskog** [comment]
@ctrlplusb I don't know if this is a good project for this, but I just created [modernizr-server](https://github.com/rlindskog/modernizr-server) that handles fetching modernizr-information to the server. It helps me preemptively handle SSR differences.

**Comment by codepunkt** [comment]
@rlindskog interesting project. doesn't this mean that seo on first visit is basically screwed?
