### ISSUE TITLE
[branch] add feature/mobx

### ISSUE THREAD

**Issue by HaveF** [ctrlplusb/react-universally#260]
Do you need a new branch for mobx?

It seems you should have a new feature branch about mobx first, then I can send PR to it.

https://github.com/HaveF/react-universally-1/commit/5b4ffff8abe851ae0db8d71d7a5840e9e4bcec42

**Comment by LorbusChris** [comment]
You can create a PR against master/next now and change the base branch later on. Its one of the nice features added rather recently here on Github :)

**Comment by ctrlplusb** [comment]
Released :)  `feature/mobx`

Thanks again!
