### ISSUE TITLE
html webpack plugin

### ISSUE THREAD

**Issue by devdlabs** [ctrlplusb/react-universally#266]
@ctrlplusb I would like to automate build process by generating html file in build directory  by injecting styles and javascript files, that will help people in uploading to production sever with git push. Is there any such plans to include https://www.npmjs.com/package/html-webpack-plugin ?

**Comment by ctrlplusb** [comment]
It's already included :)

We use it to generate the page required by the service worker.  The fallback page that is especially useful for offline app viewing.

**Comment by devdlabs** [comment]
Great! I'm using old version. Just checked  new version, it is kewl but lot of things hidden for non-nodejs coders.
Thank you

**Comment by ctrlplusb** [comment]
@devdlabs sure thing, please let me know if anything seems complex to understand. The configuration is already being simplified in the `next` branch.

Thanks!
