### ISSUE TITLE
Build fails with webpack 2.2.0-rc.1

### ISSUE THREAD

**Issue by kikoanis** [ctrlplusb/react-universally#268]
It seems that this settings in configFactory is not valid any more as of rc0

```
  performance: {
      // Enable webpack's performance hints for production builds.
      hints: isProd,
    },
```

The hints settings now accepts one of three values
```
                false,
                "warning",
                "error"
```
this could be changed to 
```
  hints: isProd ? 'warning' : false, 
```

Also, your code-split plugin now also fails with the new rc but this is may be related to the version of webpack that you are using in code-split
I tracked it down to this line in commonjs/plugins/webpack.js
```
var shouldRegisterModule =
          // We aren't interested in registering the node modules.
          module.resource.indexOf('node_modules') === -1
          // Or modules that are empty.
          && module.chunks.length > 0;
```
it seems that module.resource is undefined some times. Not sure if this will go away once you upgrade to the latest version.

**Comment by ctrlplusb** [comment]
Thanks for the report @kikoanis!

**Comment by ctrlplusb** [comment]
Staged in `next`.

I didn't experience the issue with the code split plugin.  Was this when you were executing `react-universally`?  Was it a standard clone/execute or are you running a custom extended project?

**Comment by ctrlplusb** [comment]
I am also updating code-split-component to do some checking here.  It looks like if one of the entries fail to compile it can cause this issue.
