### ISSUE TITLE
Announcement: Version 11 ready.  Please review/test. 😇

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#269]
https://github.com/ctrlplusb/react-universally/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A11.0.0

__Update feature branches__

 - [x] apollo
 - [x] found (done in PR)
 - [x] glamor
 - [x] jest
 - [x] koa2
 - [x] mobx
 - [x] postcss-sass
 - [x] redux
 - [x] styled-components
 - [x] styletron

**Comment by ctrlplusb** [comment]
Staged on the `next` branch.

**Comment by carsonperrotti** [comment]
I'll test it out right now!

**Comment by ctrlplusb** [comment]
Released. :)
