### ISSUE TITLE
Make clear the distinction between devDependencies and dependencies.

### ISSUE THREAD

**Issue by cloud-walker** [ctrlplusb/react-universally#27]

**Comment by ctrlplusb** [comment]
Yeah, the distinction I was making in terms of `dependencies` vs `devDependencies` was which are the dependencies that are actually "used" in runtime by the client/server.  

`rimraf`, `webpack` etc are more build pipeline dependencies and therefore I put them as `devDependencies`.

**Comment by cloud-walker** [comment]
I'm trying to deploy my copy of your boilerplate to heroku, and they use only standard dependencies in production, in fact I think this is the real distiction between devDependencies and dependencies.

http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

This thread on stackoverflow confirm my theory.

I've now deployed my version to heroku, and this is my actual dependency list:

```json
"dependencies": {
    "compression": "1.6.2",
    "express": "4.14.0",
    "helmet": "2.1.1",
    "hpp": "0.2.1",
    "rimraf": "2.5.3",
    "react": "15.2.1",
    "react-dom": "15.2.1",
    "react-router": "2.6.0",
    "webpack": "2.1.0-beta.19",
    "serialize-javascript": "1.3.0",
    "extract-text-webpack-plugin": "2.0.0-beta.2",
    "assets-webpack-plugin": "3.4.0",
    "source-map-support": "0.4.2",
    "dotenv": "2.0.0",
    "css-loader": "0.23.1",
    "babel-loader": "6.2.4",
    "babel-preset-es2015-webpack": "6.4.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-preset-react": "6.11.1",
    "babel-cli": "6.10.1",
    "babel-core": "6.11.4",
    "fake-style-loader": "1.0.1",
    "json-loader": "0.5.4",
    "normalize.css": "4.2.0",
    "style-loader": "0.13.1",
    "react-hot-loader": "3.0.0-beta.2",
    "webpack-node-externals": "1.2.0"
  },
  "devDependencies": {
    "babel-eslint": "6.1.2",
    "chokidar": "1.6.0",
    "eslint": "3.1.1",
    "eslint-plugin-react": "^5.2.2",
    "node-notifier": "4.6.0",
    "webpack-dev-middleware": "1.6.1",
    "webpack-hot-middleware": "2.12.1"
  }
```

I think that react-hot-loader should be on devDeps, but, its still needed in production during compilation.

**Comment by ctrlplusb** [comment]
Yeah I see your point.  I need to think about this one.

In terms of heroku, it is possible to allow the install of dev dependencies:
https://devcenter.heroku.com/articles/nodejs-support#devdependencies

**Comment by ctrlplusb** [comment]
@cloud-walker Thanks for your input into this.  I have done some testing and have restructured the dependencies so that they contain all _runtime_ dependencies.  The devDependencies will contain all build dependencies.

**Comment by ctrlplusb** [comment]
@cloud-walker it was really grinding me that we had libraries that I consider dev/build dependencies within our runtime dependencies. I managed to come up with a solution. :)
It's running nicely on the https://github.com/ctrlplusb/react-universally/tree/next branch.  Just a friendly heads up to you.

If you have any feedback on it please let me know.  The exact commit is:
https://github.com/ctrlplusb/react-universally/commit/bf94b0d66cbbb3c63bbabad22008eeccb1a829b0

**Comment by cloud-walker** [comment]
Maybe its a personal choice, but for example modules like css-loader are used in production also, so they are not devDependencies.

Since this is a boilerplate, and not an npm package, I assume as normal dependencies all the npm packages actually used in production (during build process also). But again, I think it could be a personal choice (ex. maybe you build for production from your local machine, so webpack stuff are for devDependencies.)

Sorry for my bad english :smiley:

**Comment by ctrlplusb** [comment]
Yep, you are guessing correctly.  I am trying to make a distinction between build/runtime.  Building can be done on any machine (a CI server for example) with the result being deployed to production.  I like that I can support this scenario easily so that the production environment won't get any more dependencies installed than it needs.  Then again, its easy to reconfigure a production environment to install both the dependencies and devDependencies if I want it to do build and run.

Thanks for your input!  I really appreciate any and all input on this project. :)
