### ISSUE TITLE
Contact details of contributors/maintainers.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#270]
Hey all;

I am missing emails for the following people (to be added to the package.json):

 - [ ] "Alin Porumb",
 - [x] "Christian Glombek",
 - [x] "Christoph Werner",
 - [ ] "David Edmondson",
 - [ ] "Evgeny Boxer",

**Comment by LorbusChris** [comment]
christian.glombek[at]rwth-aachen.de

Merry Christmas :)

**Comment by ctrlplusb** [comment]
And to you. :)

**Comment by codepunkt** [comment]
christoph[at]codepunkt.de

Thanks for your work with this project! Hope you'll have a relaxed time with your loved ones! :)

**Comment by ctrlplusb** [comment]
Thanks @codepunkt!

I wish the same for you. :)

Happy holidays everyone. :)

**Comment by ctrlplusb** [comment]
Closing this.  If any of the outstandings would like to provide me details then just ping me. :)
