### ISSUE TITLE
filterObject function throw error when object value is false, '' or null

### ISSUE THREAD

**Issue by tvkhoa** [ctrlplusb/react-universally#276]
in `filterObject.js`, you have an if condition 
```
if (!obj[key]) {
     throw new Error(`Object filters set an "allow" on path "${propPath}", however this path was not found on the source object.`);
 }
```
And it will throw error if obj[key] is false, '' or null,...

I think we should change it to 
```
if (obj[key] === undefined) {
```

Btw, this project is awesome. @ctrlplusb

**Comment by ctrlplusb** [comment]
Hi @tvkhoa!

Thanks for the report and for the kind words.  To be honest this project has really started to take off the moment other people took interest in it and began to contribute in many ways.  So a lot of credit extends to them. :)

I've fixed this, and will release a patch quite soon as it's a fairly critical bug.

Keep me posted with your experiences with the project, we are always looking to improve it. :)
