### ISSUE TITLE
Add async reducers with redux during routing

### ISSUE THREAD

**Issue by datoml** [ctrlplusb/react-universally#278]
Hello,

I was trying to take some parts from the react-boilerplate and include it into this universal approach.
It seems like I am stuck here with the routing :(.

The goal is to load the reducer, sagas and the component before routing to the page.

How can I achieve the same with react-router v4?

I was also thinking about going back to v3 but I think this isnt a good idea.

Thanks in advance :).

```
{
      path: '/',
      name: 'home',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/HomePage/reducer'),
          System.import('containers/HomePage/sagas'),
          System.import('containers/HomePage'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('home', reducer.default);
          injectSagas(sagas.default);

          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    }
```

**Edit**

Ok, so I managed to add the reducer async within the taskRoutes function. Now i get what this is all about :).
```
{
      pattern: '/',
      prefetchData: () => {
        const importModules = Promise.all([
          System.import('../reducers/testReducer'),
        ]);

        importModules.then(([reducer]) => {
          injectReducer('home', reducer.default);
        });
      }
    },
```

But I think the async concept didnt work with SSR.
The server now injects the reducer and creates the store, passes it down to the client and then creates the store on the client again.
The problem is, that the reducer hasn'T loaded on the client so I get this handsome error:
`Unexpected keys "home", "about" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "route". Unexpected keys will be ignored.`

**Edit2:**
I think there is no big benefit in loading reducers async. It also makes everything more complicated :).

**Comment by ctrlplusb** [comment]
@datoml I believe the async reducers and sagas exist in `react-boilerplate` to aid with code-splitting. i.e. they will get bundled with the respective route code they belong to. 

You can most certainly achieve something similar using our react router 4 routes.  

I am just throwing out a wild idea here.  i.e. I haven't tested this or given it time to settle into the best possible solution, but you could for example pass through the injector functions to the resolved routes.

```js
// App.js

import AsyncHome from './AsyncHome';
import { injectReducer, injectSaga } from './'

const injectProps = {
  injectReducer,
  injectSaga
};

export default function App() {
  return (
    <div>
      <Match 
        exactly 
        pattern="/" 
        render={routerProps =>
          <CodeSplit chunkName="home" modules={{ Home: require('./containers/Home') }}>
            { ({ Home }) => Home && <Home {...routerProps} {...injectProps} /> }
          </CodeSplit>
        } 
      />
    </div>
  )
}
```

Within your home component mount/unmount events you could bind/unbind the reducers/sagas.

Hope this is helpful.

**Comment by datoml** [comment]
Thanks for this example.
But I think this doesn't work either.
For example:

You render the Home component on the server the redux store gets injected with the home reducer. You then pass down the state to the client.

On the client you want to rehydrate the state but the home reducer wasn't loaded yet.
This will happen later when you hit the route.
So redux will refuse to load the key home.

Or am I missing something?

**Comment by ctrlplusb** [comment]
Hmmm, you may then need a factory function of sorts that does the reducer registration and returns a Home component for use of rendering.

**Comment by codepunkt** [comment]
Out of curiosity: Why? What's the benefit of all this injection magic? 😕

**Comment by ctrlplusb** [comment]
I am assuming here, but I think it's intention is to bundle the reducer/saga specific code with the route code splitting chunk. It doesn't feel worth the complexity to me. Not sure how significant the bundle size savings would be.

**Comment by codepunkt** [comment]
Ahh, i see.
@datoml did you try https://github.com/randallknutson/redux-injector?

**Comment by datoml** [comment]
@ctrlplusb I was thinking the same. It is not worth the complexity it brings :).
@codepunkt I didn't try this sone but I think it would end with the same result.
Thanks for the help tho.
We can close this I guess :).
