### ISSUE TITLE
Feature - Redux - unnecessary API calls

### ISSUE THREAD

**Issue by elodszopos** [ctrlplusb/react-universally#281]
Hello,

I noticed that on the feature branch switching between the posts keeps making API requests, even if it already has been downloaded and is no longer necessary fetch the data.

I solved this on my fork using an approach that's as generic, open-ended for interpretation and personal preference as possible.

I pass into task executors current state as well and let each task runner decide if it is necessary to fetch or not. Let me know if you think that would be a viable solution here too @ctrlplusb.

Thanks!

Below you can find the unnecessary API requests being made - at least they're 304's.

![image](https://cloud.githubusercontent.com/assets/4669986/21516560/05724aec-cce2-11e6-963b-00796b522b0b.png)

**Comment by ctrlplusb** [comment]
Hi @elodszopos!

Thanks for this!  

Yep, I really need to add more documentation to the `redux` feature branch.  It is definitely important for people to consider how they would like to (and if they need to) prevent tasks from firing with every hit on a route.  Memoization and all sorts of techniques could be considered.

I will definitely have a look at your implementation and take it under consideration.

Please also be aware that I am in the middle of producing a new solution to declaring tasks that I believe will be far more intuitive.  My solution doesn't include anything to manage caching of requests thusfar though,  so this is definitely still worthwhile for me to review.

I am not 100% certain I should bake in a caching strategy. If we don't we should at least have a hefty chunk of documentation that explains the benefits etc.

Thanks again for you interest in this project and for helping out like this! 🙏

**Comment by elodszopos** [comment]
Right now it looks something like this:

`TaskRoutesExecutor` in `componentWillMount` and `componentWillReceiveProps` also passes along current state, not just `dispatch`.

```
executeTasks(location, dispatch, store.getState());
```

`executeTasks` passes along the state using the `locals` param that `runTasksForLocation` receives.

```const executingTasks = runTasksForLocation(location, tasksToExecute, { dispatch, state });```

And finally, here's how task routes look like:

```
function taskRoutes({ dispatch, state }) {
  return [
    {
      pattern: '/posts/:id',
      prefetchData: ({ id } : { id: number }) => (state.posts.byId[id] ? Promise.resolve() : dispatch(PostActions.fetch(id))),
      // deferredData: ({ id } : { id: number }) => dispatch(PostActions.fetch(id)),
    },
  ];
}
```

On SSR we also execute tasks for the location that the request was for. We have access to the store as well.

```
const executingTasks = runTasksForLocation({ pathname: request.originalUrl }, ['prefetchData'], { dispatch, state: store.getState() });
```

It's rudimentary really, but enough to get the conversation started. Once you can give us more info on what the new task mechanism will look like, let us know. Or maybe I can help implement - whichever. 

For memoization I can wholeheartedly recommend [this library - reselect](https://github.com/reactjs/reselect).

Also, there's a [very nice library](https://github.com/makeomatic/redux-connect) that I've used with great pleasure for a very similar task in a web app that's now in production, with SSR. Very well maintained and super responsive repo-owner. Cool guy.

I'm not proposing for it to be used - just a look at it's internal workings might sparkle some nice ideas.

**Comment by elodszopos** [comment]
Also - my pleasure. After looking through many alternatives and possible choices - I chose this starter kit because:

It's simple, it's fast and very intuitive. Me gusta. I was able to create my very own feature-packed personal starter in just two days for whatever play-project I may have in the future. I want to help make it better.

**Comment by ctrlplusb** [comment]
We really appreciate the feedback! :)

Thank you so much for all of this. :)

**Comment by devdlabs** [comment]
@ctrlplusb what about redux-router ? It looks more simpler for me. Did I miss anything ?

**Comment by devdlabs** [comment]
@ctrlplusb looking eagerly for your new taskrouter. Any news..?

**Comment by elodszopos** [comment]
@devdlabs you can find more on that [here](https://github.com/ctrlplusb/react-jobs), courtesy of @ctrlplusb

**Comment by ctrlplusb** [comment]
Yeah, it's a sweet library but I prefer RR v4.  I like the way the application gets expressed.  

I have just finished my first working test bed of my `react-jobs` library against the redux branch.  I basically deleted a ton of code and added a very small amount.  We now have collocated queries and caching on them.

I am going to do some more testing and will push my progress at some point.  I want to get this wrapped up and then push it all together with the v12 release.
