### ISSUE TITLE
Move flow into a feature branch?

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#288]
It's really awesome, but that's my opinion, and I want you all to be able to make your own choices.

**Comment by ctrlplusb** [comment]
The existing redux branch fairly heavily relies on flow. I need to come up with the best strategy for this case.

**Comment by ctrlplusb** [comment]
I would be interested in hearing peoples experiences with the `npm run flow:remove` script.  Is this sufficient?  What is your merging experience like after flow has been ejected?  Would you strongly prefer flow to be moved into a feature branch?

**Comment by carsonperrotti** [comment]
I personally remove flow from my fork after each update. The script works but leaves artifacts behind, extra spaces, code comments, etc.

**Comment by codepunkt** [comment]
I did some editing by hand after running `flow:remove`. From that point on, i'm copy/pasting commits from branches i have combined. Should try some cherry-picking/conflict resolving though 🤣

**Comment by ctrlplusb** [comment]
OK, I've decided to make this happen.  I feel like non-flow users will outweigh flow users, and I want this to be a generic starter.  For the good of the community, I'll drop flow as the default.

**Comment by ctrlplusb** [comment]
Staged on `next`
