### ISSUE TITLE
How does authentication work with server side rendering?

### ISSUE THREAD

**Issue by datoml** [ctrlplusb/react-universally#289]
Hello,
how can I implement authentication when using server side rendering?
I found this library but it doesn't work with react router 4.
https://github.com/lynndylanhurley/redux-auth

Can someone give me some hints how to do it?
Would really appreciate it :).

PS:
I tried a lot of boilerplates so far and your's by far the best one ever :).
Thx @ctrlplusb

**Comment by strues** [comment]
You can find an example on in the [React Router docs ](https://github.com/ReactTraining/react-router/blob/v4/website/examples/Auth.js). I'll expand off of their example here.

The first thing to do is create the router component to handle authenticated routes.
```
const MatchWhenAuthorized = ({ component: Component, ...rest }) => (
  <Match {...rest} render={props => (
   // replace with props.auth.isAuthenticated
  // or however your redux stores are setup for auth.
    fakeAuth.isAuthenticated ? (
      <Component {...props}/>
    ) : (
      <Redirect to={{
        pathname: '/login',
        state: { from: props.location }
      }}/>
    )
  )}/>
)
```

Notice where in the example they use `fakeAuth.isAuthenticated`. The way you'll handle this in a real world application is replacing `fakeAuth.isAuthenticated` with your redux store using react-redux's connect. That would look something like this:

```javascript
function mapStateToProps(state) {
  return { auth: state.auth }
}

@connect(mapStateToProps)
class AuthExample extends React.Component {
  render() {
    return (
      <Router>
        {({ router }) => (
          <div>
            {
             // replacing fakeAuth.isAuthenticated
              this.props.isAuthenticated ? (
              <p>
                Welcome! {' '}
                <button onClick={() => {
                  this.handleSignout(() => {
                    router.transitionTo('/')
                  })
                }}>Sign out</button>
              </p>
            ) : (
              <p>You are not logged in.</p>
            )}

            <ul>
              <li><Link to="/public">Public Page</Link></li>
              <li><Link to="/protected">Protected Page</Link></li>
            </ul>

            <Match pattern="/public" component={Public}/>
            <Match pattern="/login" component={Login}/>
            <MatchWhenAuthorized pattern="/protected" component={Protected}/>
          </div>
        )}
      </Router>
    )
  }
}
```

How do you check for authentication as soon as a user first loads your app?

I typically check in the client entry file for a token in localStorage. If a token is found, I dispatch an action that verifies the token against the server (basically a request with the token in the header). The response returns the user's information if they are authenticated.

**Comment by datoml** [comment]
Thank you for this example 👍 .

But what would be the solution when rendering an authorized component on server?
Like in this example the store grabs the jwt from localStorage as initState.
https://github.com/auth0-blog/redux-auth
```
function auth(state = {
    isFetching: false,
    isAuthenticated: localStorage.getItem('id_token') ? true : false
  }, action) {
  switch (action.type) {
    case LOGIN_REQUEST:
      return Object.assign({}, state, {...
```
This doesn't apply for server side rendering.
So I was thinking about grapping a cookie from the request an check if there's a JWT in it and use this for the initial state.
Would probably look something like this.
```
function auth(state = {
    isFetching: false,
    isAuthenticated: localStorage == null ? checkAuthCookie : checkLocalStorage
  }, action) {
  switch (action.type) {
    case LOGIN_REQUEST:
      return Object.assign({}, state, {...

```
Would this be a good solution?

**Comment by sbuys** [comment]
<Redirect> doesn't work for me when visiting the url "/protected" directly in browser - I'm redirected to "/" instead of "login". Only when clicking a <Link to "/protected"> am I redirected correctly. Any idea what gives?

**Comment by oyeanuj** [comment]
@datoml I'd recommend looking at the redux-auth-wrapper for authentication and authorization logic wrt to the routes and components. I am not sure if it supports RR4 yet, but that HoC pattern might be helpful to look at as an example.

**Comment by strues** [comment]
I forgot @datoml as I was writing the example that you probably are implementing directly with the server as opposed to a separate API. Here's another little thing you can do:


```javascript
// src/server/middleware/ssrMiddleware/index.js

// only here for some context / an example
// this just places the request url in the initial state
 const getHost = req =>
    `${req.headers['x-forwarded-proto'] || req.protocol}://${req.headers.host}`;

  const createStore = req => configureStore({
    boldr: {
      meta: {
        host: getHost(req),
      },
    },
   auth: {
      isAuthenticated: // check the auth on the initial request and do something with it here.
   }
  });
  
 /// implement the usual with createStore replacing configureStore

  const memoryHistory = createMemoryHistory(req.url);
  const store = createStore(req, memoryHistory, apiClient);

```

**Comment by eurobob** [comment]
@strues, in your MatchWhenAuthorized example, how would that work with the CodeSplit functionality?

I'm getting a pesky error

<img width="830" alt="screen shot 2017-03-08 at 18 25 13" src="https://cloud.githubusercontent.com/assets/4255350/23700065/a797ae8a-042c-11e7-844a-eeab3c78e6a4.png">

**Comment by eurobob** [comment]
Answered my own question. I'm still rendering the item like a component function. Was previously using the render attribute on the Match element.

**Before** (doesn't work)

`<MatchWhenAuthorized
        pattern="/about"
        render={routerProps =>
          <CodeSplit chunkName="about" modules={{ About: require('../pages/About') }}>
            { ({ About }) => About && <About {...routerProps} /> }
          </CodeSplit>
        }
      />`

**After** (works)

`<MatchWhenAuthorized
        pattern="/about"
        component={routerProps => (
          <CodeSplit chunkName="about" modules={{ About: require('../pages/About') }}>
            { ({ About }) => About && <About {...routerProps} /> }
          </CodeSplit>
        )}
      />`

**Comment by ctrlplusb** [comment]
Closing for now, as more of a discussion.

**Comment by Aadriya** [comment]
I have an error Like


Invariant Violation: Could not find "store" in either the context or props of "Connect(Header)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Header)".

**Comment by datoml** [comment]
@Aadriya Can you post a code example?
