### ISSUE TITLE
How to fetch data with SSR?

### ISSUE THREAD

**Issue by Kimel1** [ctrlplusb/react-universally#290]
Hi,
Thank you for hardworking on the boilerplate, it's awesome.
SSR is relatively new technology and some things aren't clear for me. 
Say I develop e-commerce. I need an api to communicate with frontend. And w/o SSR it's easy to do. I can run an api on the express server and use something like Amazon Lambda for hosting static files with the react. Or I can do this on the same server, run api and share static files is easy by the express, even on same port. 

But using SSR data fetched by server first (from api on the another server for example), then data load every request from backend to frontend. 
The question is how to fetch data on the server side, if the api and ssr are on same server. I can of course do a loopback request and the server will call to self. But it's can influence on a performance. 

So I can't use a shared code for client and server to fetch data therefore the code reusability gets off.

**Comment by ctrlplusb** [comment]
Personally I would go for the simple route and let the server call itself.  I tend to use `axios` and then have a helper using the webpack flags (e.g. `process.env.IS_NODE`) to configure the `axios` instance appropriately per environment.

Do some metrics testing and see if the performance hit is anything significant.  It seems internal network requests all the rage these days what with micro-service architecture and all that, so perhaps it's not as much of an issue as you may be thinking.

**Comment by Kimel1** [comment]
@ctrlplusb 
Turns out it might be normal practice to let server call itself. I'm beginner and it's now clear for me. I think there is no test required, I just wanted to hear the opinion from professional. 
So I can use your example in feature redux branch to fetch data as good example.

Thank you for explanation. 

 With your permission, I'll ask another question in this issue. 
In Post.js
```
function mapStateToProps(state, { params: { id } }) {
  return {
    post: FromState.getPostById(state, id),
  };
}
```
I tried to find out what `post: FromState.getPostById(state, id), ` mean, but don't understand why  the reducer putted to this components props. In redux tutorials says:

> Note: in advanced scenarios where you need more control over the rendering performance, mapStateToProps() can also return a function. In this case, that function will be used as mapStateToProps() for a particular component instance. This allows you to do per-instance memoization. You can refer to #279 and the tests it adds for more details. Most apps never need this.

So there is a function instead of state, but why?

**Comment by Kimel1** [comment]
@ctrlplusb 
I would be grateful if you'll help me with second question too. 
In post.js (Action)
```
function fetching(id: number) : Action {
  return { type: 'FETCHING_POST', payload: id };
}

function fetched(post: Post) : Action {
  return { type: 'FETCHED_POST', payload: post };
}

export function fetch(id: number) : ThunkAction {
  return (dispatch, getState, { axios }) => {
    fetching(id);

    return axios
      .get(`https://jsonplaceholder.typicode.com/posts/${id}`)
      .then(({ data }) => dispatch(fetched(data)));
  };
}

```
And if I correct understood when I click on post link, the `FETCHING_POST` must fired, then on data fetched `FETCHED_POST `will fired. 
But in Chrome Dev Console, I see always only `FETCHED_POST `
[![Untitled.png](https://s29.postimg.org/nk9gciguv/Untitled.png)](https://postimg.org/image/tl759l3gz/)

Is there a bug?

**Comment by devdlabs** [comment]
Oh dear he is using https://github.com/ReactTraining/react-router-addons-routes for dispatching actions :-)

**Comment by ctrlplusb** [comment]
> I think there must be dispatch(fetching(id)); instead of fetching(id);

Yes you are right! :)

**Comment by Kimel1** [comment]
Sorry, but I still don't understand anything about post: `FromState.getPostById(state, id)`
could you explain pls?

**Comment by ctrlplusb** [comment]
Hey @Kimel1

This is an "idiomatic redux" pattern recommend by the author of redux, Dan Abramov. 

He has a series of free courses available on egghead.  I highly recommend that you look into them:

 - [Getting Started with Redux](https://egghead.io/courses/getting-started-with-redux)
 - [Building React Applications with Idiomatic Redux](https://egghead.io/courses/building-react-applications-with-idiomatic-redux)

**Comment by Kimel1** [comment]
Hi, @ctrlplusb 
Thank you very much! You can close the issue now.

**Comment by ctrlplusb** [comment]
No problem, enjoy the courses, Dan is a great teacher.
