### ISSUE TITLE
React Router v4 Matching

### ISSUE THREAD

**Issue by rlindskog** [ctrlplusb/react-universally#291]
Hey, awesome project!  I'll definitely keep in touch with this.
What do you think about rendering React Router v4 matches with a route-config like this?

    // App.js
    import React from 'react'
    import routeConfig from './route-config.js'
    
    let routes = routeConfig.map((route, index) =>
      <Match
        key={index}
        pattern={route.pattern}
        exactly={route.exactly}
        render={routerProps =>
          <CodeSplit chunkName={route.component.displayName} modules={{ [route.component.displayName]: route.component }}>
            { theComponent => theComponent && <route.component {...routerProps} /> }
          </CodeSplit>
        }
      />
    )
    
    export default class App extends React.Component {
      render() {
        return (
          <div>
            {routes}
            <Miss component={Error404} />}
          </div>
        )
      }
    }

    // route-config.js
    import Home from './Home'
    import About from './About'
    import Blog from './Blog'
    
    export default [
      { pattern: '/', component: Home, exactly: true },
      { pattern: '/about', component: About },
      { pattern: '/blog', component: Blog }
    ]

I feel like it's a bit simpler.

**Comment by tvkhoa** [comment]
I agree with @rlindskog , with this way, it works nicely with routeTasks in redux feature. We can remove the duplicated code in routes.

**Comment by ctrlplusb** [comment]
I hear you guys and appreciate the code duplication can make your routes declarations very noisy.

Unfortunately there are some restrictions with how `code-split-component` currently works which prevents any sort of solution as the one you are proposing.  However, I am working on a new release of this library which may be able to open up these types of choices.

**Comment by ctrlplusb** [comment]
Solved in `next` :)
