### ISSUE TITLE
Vendor dll is being cached by browser

### ISSUE THREAD

**Issue by howardya** [ctrlplusb/react-universally#292]
Hi guys, can I check something. 

I have small error showing up in the console in the redux branch. The steps I took are : 

git clone repo
git checkout feature/redux
yarn install
yarn run development

Upon checking localhost:1337 there is error printed out 
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap c6d47b1…:19)
    at Object.<anonymous> (module.js from dll-reference __dev_vendor_dll__:1)
    at __webpack_require__ (bootstrap 74a3122…:659)
    at fn (bootstrap 74a3122…:83)
    at Object.<anonymous> (isBuffer.js:38)
    at __webpack_require__ (bootstrap 74a3122…:659)
    at fn (bootstrap 74a3122…:83)
    at Object.<anonymous> (_arrayLikeKeys.js:4)
    at __webpack_require__ (bootstrap 74a3122…:659)
    at fn (bootstrap 74a3122…:83)

Is this something I should fix? Thank you very much for this great boilerplate.

**Comment by sbuys** [comment]
I had the same issue. If I remember correctly, the fix was to run `npm run clean`

I think there might be something going on with the caching. I'm building on top of the boilerplate and seeing similar errors: "Cannot read property X of undefined" as I add new dependencies. But if I run chrome in Incognito or clear my browser cache the errors go away.

**Comment by ctrlplusb** [comment]
Interesting... I'll keep my eye on this.

Also worth noting, if you run a `npm run build` and `npm run start` a service worker will be registered that does some heavy caching.  Make sure you go to the `Applications` tab of Chrome Dev Tools and then unregister it.

**Comment by sbuys** [comment]
@ctrlplusb Thanks for the follow up. FYI - I unregistered the server worker and still had some issues in chrome. My only fix was to load "http://localhost:3030/client/__dev_vendor_dll__.js" directly and force refresh.  🤔

**Comment by ctrlplusb** [comment]
Thanks! That actually gives me lots of insight into the issue!

**Comment by ctrlplusb** [comment]
Staged in `next`

**Comment by howardya** [comment]
well that was fast. too fast. :) 

thank you for the updates.
