### ISSUE TITLE
Add ngrok support

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#293]
https://ngrok.com/

**Comment by codepunkt** [comment]
Whats the usecase?

**Comment by ctrlplusb** [comment]
One example: exposing your dev server to a mobile device.

**Comment by ctrlplusb** [comment]
I'm not 100% yet on this, but came across it and thought it could be an interesting addition.  I'm interested in hearing the experiences of others here.

**Comment by codepunkt** [comment]
Mobile devices in my LAN can access the dev machines local IP, which can be logged on starting the server. Seems easier to me :)

**Comment by oyeanuj** [comment]
I've found ngrok to be very useful, while testing on mobile devices (especially, the ones that aren't yours or not on the same LAN) as well as debugging a particular build with someone remote (user or dev). It saves a lot of pain in a lot of such cases and I think is a good developer experience default.

**Comment by codepunkt** [comment]
for remote debugging or mobile devices that are not on the same LAN i prefer deploying to (now)[https://zeit.co/now] nowadays.

**Comment by andreyluiz** [comment]
Ngrok does something very close to now. What about a feature branch?

**Comment by ctrlplusb** [comment]
Yeah, with `now` it isn't really needed.  We need to keep encouraging people to try `now`. :)

**Comment by ctrlplusb** [comment]
I'll close this, if the need ever arises we can discuss it again.
