### ISSUE TITLE
Rework the vendor DLL configuration.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#295]
Hey guys;

Having worked across branches/projects now I am finding the current configuration a bit brittle.

I think we should move away from auto-inclusion of the package dependencies as the vendor DLL items, as it doesn't work as nicely for this project (being an SSR project over a frontend only project).  Too often I accidentally include a new dependency I added for the server and then have to go and edit the `excludes` config.

Additionally I think we should remove the `ignores` and `excludes` items, and keep it to a single `includes` config item.  Thereby making it a manual update process.  We could instead print a helpful message on the console and/or in the docs informing them of this.

**Comment by ctrlplusb** [comment]
New config:

```js
      devVendorDLL: {
        // Enabled?
        enabled: true,

        // Specify any dependencies that you would like to include in the
        // Vendor DLL.
        //
        // NOTE: It is also possible that some modules require specific
        // webpack loaders in order to be processed (e.g. CSS/SASS etc).
        // For these cases you don't want to include them in the Vendor DLL.
        include: [
          'react',
          'react-dom',
          'react-helmet',
          'react-router',
        ],

        // The name of the vendor DLL.
        name: '__dev_vendor_dll__',
      },
```

**Comment by strues** [comment]
Full circle! However it does make sense as my excludes are longer than my includes would be...

/shrug

**Comment by enten** [comment]
:+1: 

Great! I'm totally agree.

**Comment by aap82** [comment]
👍

**Comment by ctrlplusb** [comment]
Staged on `next`

**Comment by enten** [comment]
**Off topic**

Can you use the notation `${commit_message} (fix #${issue_id})` for the commits which fix an issue? 

With this notation: the affected issue will be closed automatically and a reference to the commit will be add in its events feed.

**Comment by LorbusChris** [comment]
@enten @ctrlplusb 

Also works with `close` and `resolve`, their 3rd person conjugation and past form (i.e. `fixes` & `fixed`)

refs: https://help.github.com/articles/closing-issues-via-commit-messages/
