### ISSUE TITLE
Should set NODE_ENV=production for build script (currently undefined)

### ISSUE THREAD

**Issue by sbuys** [ctrlplusb/react-universally#298]
NODE_ENV is undefined when running build script, so it defaults to "development" in [config/internals/environmentVars.js#L12](https://github.com/ctrlplusb/react-universally/blob/master/config/internals/environmentVars.js#L12)

```javascript
function registerEnvFile() {
  const envName = process.env.NODE_ENV || 'development';
  const envFile = '.env';
````

Which leads to production build with development environment vars when using the .env files.

**Comment by sbuys** [comment]
Is the correct place for this just in package.json for the build script?

`NODE_ENV=production babel-node tools/scripts/build`

**Comment by ctrlplusb** [comment]
Hmmm, I think we should change the default to "production".

Good find @sbuys , thanks!

**Comment by sbuys** [comment]
Thanks for the fix! Love what you've built and really appreciate all the work 🙏.
