### ISSUE TITLE
Service Worker failed to install

### ISSUE THREAD

**Issue by diondirza** [ctrlplusb/react-universally#301]
When I tried to grouping my assets in public folder by adding folder inside it, SW failed to install.
<img width="1225" alt="screen shot 2017-01-06 at 5 12 46 pm" src="https://cloud.githubusercontent.com/assets/10954870/21714909/01a9f104-d434-11e6-8437-58be9a7aa9a4.png">

Any clue to solve it guys?

**Comment by ctrlplusb** [comment]
Hey @diondirza!

Hmmm, did you just add a new folder within `public`?  You didn't do any adjustments to the service worker configuration?

**Comment by diondirza** [comment]
Nope, just add new folder and add some images, sorry I am beginner for this SW thing. 
Still looking on related issue about this in Offline-Plugin page.

**Comment by ctrlplusb** [comment]
Sounds like a bug TBH.  I'll try have a look soon.

**Comment by strues** [comment]
Spitballing here, but try unregistering the service worker in Chrome. Then hard refresh. Ive experience some quirks with both offline-plugin's SW and the other webpack SW plugin.

**Comment by diondirza** [comment]
I found the culprit, seems your SW externals configuration including directory paths as external files then sw will have request for those. Since our server doesn't know how to handle those requests it will give response 404 that make SW install event break.

For quick fix just add options parameter in globSync function to exclude directory
line 459 --`globSync(publicAssetPathGlob, { nodir: true })`

I have made a [PR](https://github.com/ctrlplusb/react-universally/pull/305) for this

**Comment by ctrlplusb** [comment]
Awesome @diondirza, thanks for taking the time to look into this. I'll go through this soon. 👍
