### ISSUE TITLE
React Native feature branch?

### ISSUE THREAD

**Issue by eurobob** [ctrlplusb/react-universally#304]
Any plans for this? Or any idea what the best way to go about it would be? Think this would be an awesome addition for trying to get a shared codebase together, maybe similar to https://github.com/benoitvallon/react-native-nw-react-calculator ?

**Comment by ctrlplusb** [comment]
Hey @eurobob!

Thanks for your interest in this project. :)

Hmmm, I don't have any experience with React Native myself.  From what I have heard on podcasts it sounds like it's quite a different tooling architecture from a web application. I am not sure this starter could/should be adapted to support both forms.

To be honest my ideas for the project is to push it to be a progressive web application base at the same time.  Making the use of responsive design you should be able to achieve a decent experience for mobile apps.

If you experiment with this concept though please do keep me in touch. :)

**Comment by ctrlplusb** [comment]
I am open for PR's here, but for now I am going to close this.

Also, look at [`create-react-native-app`](https://github.com/react-community/create-react-native-app)

**Comment by oyeanuj** [comment]
@eurobob I'm curious where you ended up with this?

@ctrlplusb Have you considered `react-native-web` for one of the feature branches? That could be a useful stepping stone for folks, especially as `react-primitives` and `react-native-web` take off more..
