### ISSUE TITLE
Build for electron

### ISSUE THREAD

**Issue by eurobob** [ctrlplusb/react-universally#306]
I added electron to my project, and i'm trying to get `npm run build` to create a bundle for it that doesn't use the service worker or hash the filename

I created an additional (fixed) bundle named 'desktop' in the config and tried adding it to the webpackConfigFactory, but it won't compile when i run the command. Instead I get this error:

> ERROR in ./src/desktop/index.js
> Module parse failed: src/desktop/index.js Unexpected token (35:6)
> You may need an appropriate loader to handle this file type.

It seems that it's falling down on the JSX. What am I missing to make this work? Do I need to edit another config file?

Any suggestions much appreciated :)

**Comment by ctrlplusb** [comment]
Hey @eurobob 

Hmmm, by the sounds of it you need to make sure the "babel-preset-react" is getting added to the "isNode" builds.  Check the project configuration and update the babel configuration appropriately.  Most like you just need to remove the if-statement.

**Comment by eurobob** [comment]
would that be in the config/index.js file?

**Comment by ctrlplusb** [comment]
Yep. :)

**Comment by eurobob** [comment]
Isn't that already happening on line 335?

**Comment by enten** [comment]
_Probably off topic._

Webpack support [special targets for electron builds](https://github.com/webpack/webpack/blob/0ddf5fdb5aac988b25fc94c31a00d57a9bec4390/schemas/webpackOptionsSchema.json#L790).

I don't know what are the consequences on bundles built.

But I think that it's an useful information which need to be shared with you sirs.

**Comment by eurobob** [comment]
For a bit more context, I pointed the electron compilation at the client build and it worked. It's just a pain because of the hash. All i'm looking to do is put the same client build in a desktop/electron folder with no hash and no service worker. How would I go about doing this?

**Comment by enten** [comment]
> How would I go about doing this?

Remove hash in file names included in the bundle?
Disable the service worker?
The both?

**Comment by eurobob** [comment]
Both. What I want is 3 folders in my build output:

• Client
• Server
• Desktop

I don't want to alter the client build. I want that to compile as it currently does. I just want to compile exactly the same thing into the desktop folder with the service worker disabled (which I believe just requires removing it in the src index for desktop) and not to hash it.

I'm having trouble though. Since it's not a node bundle it doesn't belong in the additional bundles section, so i'm having to hack the web pack config a bit, but it doesn't recognise the JSX

**Comment by enten** [comment]
@eurobob 

> i'm having to hack the web pack config a bit

Yes, it's the right way. You need to create logic about your desktop target (`isDesktop` and `ifDesktop` constants must be created and used to disable hash in file names and disable the service worker).

Share a gist of your webpack factory if you encounter difficulties.

@ctrlplusb 

This topic show limitations of the current webpack factory. If you plan to adjust the webpack factory, please takes this case in consideration my friend.

**Comment by ctrlplusb** [comment]
Open to PRs, but honestly I like the web focus.
