### ISSUE TITLE
Support for Remote Development

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-universally#310]
So we develop a large portion of our app using c9.io which requires specific ports and the use of IP 0.0.0.0.  I have set the .env to those ports (8080 and 8081) but I am getting an error now that i am not using the appropriate ports.  Logs don't really show anything here to help me so I've been scouring through the code trying to figure out where i can start to troubleshoot this but I feel that it has something to do with only supporting development via localhost or something?

```
You may be using the wrong PORT & IP for your server application.Try passing $PORT and $IP to properly launch your application. You can find more information in our docs.
```

^ the above happens if port is not 8080, 8081, or 8082 which are the only ports exposed.  IP must be 0.0.0.0 

```

# The host on which to run the server.
SERVER_HOST=0.0.0.0

# The port on which to run the server.
SERVER_PORT=8080

# The port on which to run the client bundle dev server (i.e. used during
# development only).
CLIENT_DEVSERVER_PORT=8081

```

^ above is my .env file which it says it is reading from.

It does appear to serve the html but it does not serve the static files, etc.

![image](https://cloud.githubusercontent.com/assets/15365418/21790512/aec76826-d691-11e6-94c0-8262ba38d907.png)

Would be nice if the logs gave a bit more information about the various servers it is starting up.  As you can see, based on the output I see from the terminal everything things perfect, but there is obviously some random value that is not doing what I need it to.  

![image](https://cloud.githubusercontent.com/assets/15365418/21790783/8b7e55f8-d693-11e6-976a-c0b8d45e5ed5.png)

**Comment by bradennapier** [comment]
So just a little bit more information on this, it would appear this is similar to an issue I had previously.  Essentially I need to separate the host (0.0.0.0) and the path (https://....).  Setting the host to the actual http path failed.

So while I need the server to use 0.0.0.0 to go public, I need the references throughout to go to the specified http path (https://my-path-user.c9users.io)

This very well may already be possible.

![image](https://cloud.githubusercontent.com/assets/15365418/21791213/2983b002-d696-11e6-869a-34ec99e4de6e.png)

**Comment by ctrlplusb** [comment]
Interesting, I haven't used something like this myself before.  Thanks for the info, I'll give this a try some time. 😀

**Comment by codepunkt** [comment]
@bradennapier Out of curiosity: Why would you use something like Cloud9 over your typical IDEs or editors such as Sublime, VSCode, Atom etc?

**Comment by bradennapier** [comment]
There are a few major benefits.  I like the container-based options so that I can easily duplicate the environments.  I also like being able to access it anywhere and not really worry about local resources and/or environment itself.  For example, if my network is terrible where I am I can run processes that require a more stable network and the command runs in the cloud and I can just close the computer without worry.  Or I need to re-install my computer or get a new one then my dev environment remains static and I have nothing to worry about.  Cloning the environment including the entire OS is another major benefit for us. 

Collaborative editing is a huge plus.  Being able to edit with the team, chat, and integrate as one generally has been a major benefit.  I work with a lot of developers in my other projects where I am helping them a lot as we go along so I can simply go in and either watch their progress and/or help simultaneously without push, commit, and all that.

We can then build any scripts and runners we need to easily provide a dedicated environment for our team to do whatever is needed.   All-in-all it's pretty hard to really illustrate it until you are using it.  It obviously does suck when network fails completely not being able to access the workspace -- I know c9 has c9 desktop which can solve that but I haven't look into that yet... I just use git at that point to keep a local copy when needed at which point I just use Atom.

**Comment by bradennapier** [comment]
Also, I've always thought it could be such a cool dev tool for testing out packages.  Similar to now but with a IDE attached so that any user can try something.  You would create a public environment that others could clone that includes everything they need to try it out and see the results immediately without worrying about any dependencies, etc.  Can include any programs, cli, or anything else that could help during dev.

**Comment by lucianlature** [comment]
@bradennapier Interesting points of view, thanks for sharing.

**Comment by bradennapier** [comment]
I have not.  I have looked at a few of the options like codenvy but have stuck it through with c9.  They are behind the amazing ace editor and have really built some awesome capabilities into their IDE that I haven't seen elsewhere.  

Another thing that excites me is that C9 was purchased by Amazon recently.  I am sure you can expect a cloud IDE stack with integration to things like lambda and ec2 natively soon.

**Comment by codepunkt** [comment]
@bradennapier to be able to offer the same environment for devs working remote we've been using docker containers in development. combined with a private docker registry and a gated git remote (might be github, but could basically be hosted anywhere), that works wonders.
we don't have any collaborative editing though, only code reviews by one dev after another has comitted or pull requested the code. we also don't have the same IDE when you ssh on any server - unless people use vi/vim. from my pov you usually shouldn't need that because your development environment should replicate as much of your production environment as possible.

still, lots of great insight. thanks! i understand where you're coming from and why this issue makes perfect sense! :)

**Comment by bradennapier** [comment]
FYI, I do see these errors during full hot reload attempts.  Not enough of an annoyance right now to try to figure it out -- i just do a full reload:

```
bootstrap 71403d8…:29 GET http://dash-universal-bradynapier.c9users.io:8081/client/71403d89e50aca591786.hot-update.json 404 (Not Found)
(anonymous) @ bootstrap 71403d8…:29
hotDownloadManifest @ bootstrap 71403d8…:21
hotCheck @ bootstrap 71403d8…:223
check @ process-update.js:64
module.exports @ process-update.js:28
processMessage @ client.js?3ae6:165
handleMessage @ client.js?3ae6:72
(index):1 XMLHttpRequest cannot load http://dash-universal-bradynapier.c9users.io:8081/client/71403d89e50aca591786.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dash-universal-bradynapier.c9users.io' is therefore not allowed access. The response had HTTP status code 404.
process-update.js:122 [HMR] Update check failed: Error: Manifest request to http://dash-universal-bradynapier.c9users.io:8081/client/71403d89e50aca591786.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://dash-universal-bradynapier.c9users.io:8081/client/index.js:38:22)
handleError @ process-update.js:122
cb @ process-update.js:33
bootstrap 71403d8…:37 Uncaught (in promise) Error: Manifest request to http://dash-universal-bradynapier.c9users.io:8081/client/71403d89e50aca591786.hot-update.json timed out.
    a
```

**Comment by codepunkt** [comment]
Hot updates don't seem to send CORS headers. I'm sure that can be investigated :)

**Comment by ctrlplusb** [comment]
Hey @bradennapier if you had any luck with this please consider adding a PR so we can review and possibly integrate into project.  Until then, I am going to close this for now. Thanks.
