### ISSUE TITLE
cross-env only for selected tasks?

### ISSUE THREAD

**Issue by codepunkt** [ctrlplusb/react-universally#315]
I've noticed that `cross-env` is only used to run the `build` and `start` tasks. why is that?

**Comment by ctrlplusb** [comment]
I've only used it on the scripts that set environment variables, as that is what it is used for. 😀
i.e. cross-platform supported inline environment variable specification

**Comment by codepunkt** [comment]
Wasn't aware of that. So it basically only resolves cross-platform problems with environment vars? I'm not too cross-platform at the moment, so i wouldn't know - always thought it did something more 😏

**Comment by strues** [comment]
Cross-Env deals with mainly quirks caused from using environment variables and Windows.

**Comment by codepunkt** [comment]
Thanks. I've always used `better-npm-run` to deal with that, so i wasn't aware that `cross-env` basically does the same. Was wondering why the hell we only have two npm scripts that work cross env 😆
