### ISSUE TITLE
Require test for Redux branch

### ISSUE THREAD

**Issue by Kimel1** [ctrlplusb/react-universally#316]
In the master branch all components covered by tests.
But in the redux branch `react-universally/src/shared/components/DemoApp/Posts/Post` hasn't any test.
It could be a great example how to use Jest with the redux+react.
And it will be very well if reducers would been covered by  tests too.

**Comment by strues** [comment]
@Kimel1, I went ahead and wrote additional tests for the redux branch. They cover the reducers along with their selectors.

**Comment by ctrlplusb** [comment]
@strues thank you so much for adding the tests!

I took a brief look through them. Have you considering using snapshot testing for the results from actions applied to reducers?
