### ISSUE TITLE
Error in browser console in redux branch

### ISSUE THREAD

**Issue by Kimel1** [ctrlplusb/react-universally#325]
It's easy to reproduce this bug. 
1) Download latest clean redux branch.
2) Run dev server
3) Go google chrome dev console
4) Press F5
5) wait few seconds
6) repeat step 4 

and boom
```
sw.js:1 A bad HTTP response code (404) was received when fetching the script.
http://localhost:1337/sw.js Failed to load resource: net::ERR_INVALID_RESPONSE
```

If you press Ctrl+f5 error will gone, but try to press f5 and errors appear. 

This problem is not exist in master branch.

**Comment by Kimel1** [comment]
And another one bug is when I using IE11 and run server in production mode. 
Go to the http://localhost:1337/posts/1 and all is good. But click to post 2 link and nothing happen. 

And also if you run in dev mode then will happen same problem but plus in console log
`webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools`

**Comment by Kimel1** [comment]
I disable Service Worker =>
just go chrome://serviceworker-internals/ and unregister ??? profit!

**Comment by ctrlplusb** [comment]
Closing this as the redux branch is going to be overhauled when v13 lands.
