### ISSUE TITLE
Bug in Edge master branch

### ISSUE THREAD

**Issue by Kimel1** [ctrlplusb/react-universally#326]
Clean latest master branch. Edge 25.10 Win 10 x64
Only in development mode
[![Untitled.png](https://s24.postimg.org/slc8zyjet/Untitled.png)](https://postimg.org/image/qgrvyvhs1/)

**Comment by codepunkt** [comment]
@ctrlplusb is this fixed?

**Comment by ctrlplusb** [comment]
Yep, a PR was merged into master.
