### ISSUE TITLE
[redux] - Issues with react-jobs implementation

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#331]
Apologies, I am needing to do an upgrade.  Until then, please consider the branch unstable.

I'll sort it soon.

**Comment by sbuys** [comment]
Hey @ctrlplusb, just checking to see where you're at here.

**Comment by ctrlplusb** [comment]
Apologies.  I am going to wait for v13 to land before spending any more time on the branches.

**Comment by sergiokopplin** [comment]
hey @ctrlplusb, we are trying to use react-jobs here, have you fixed that? can i help? thanks!

**Comment by ctrlplusb** [comment]
Hey @sergiokopplin sorry about the delay.  

If you are happy to merge the `next` branch into the `redux-opinionated` branch that would be a great help. 😀

It's quite a big update though, so if the merge conflicts seem too much then please don't worry about and divert it back to me.

I plan to do a round of updates on `react-jobs` soon too.  I want to guard it up with a few more solid unit tests.

**Comment by sergiokopplin** [comment]
Ok @ctrlplusb, let me do that (:

**Comment by sergiokopplin** [comment]
@ctrlplusb should i remove flow from the redux branch?

**Comment by sergiokopplin** [comment]
i guess [this](https://github.com/ctrlplusb/react-universally/issues/288) is the answer, right?

**Comment by sergiokopplin** [comment]
@ctrlplusb having some problem here.

```
import { Provider } from 'react-redux';
import { runJobs } from 'react-jobs/ssr';
import { withAsyncComponents } from 'react-async-component';

...

  // Pass our app into the react-async-component helper so that any async
  // components are resolved for the render.
  withAsyncComponents(app).then(({ appWithAsyncComponents, state, STATE_IDENTIFIER }) => {
    // Generate the html response.
    const html = renderToStaticMarkup(
      <ServerHTML
        reactAppString={renderToString(appWithAsyncComponents)}
        nonce={nonce}
        helmet={Helmet.rewind()}
        asyncComponents={{ state, STATE_IDENTIFIER }}
        initialState={getState()}
        jobsTate={{ state, STATE_IDENTIFIER }}
      />,
    );

...
```

i'm trying to merge the next with redux, so in this file 'server/middleware/reactApplication/index.js', should i continue using withAsyncComponents or should i migrate this to use 'runJobs' instead?

**Comment by ctrlplusb** [comment]
Hey @sergiokopplin 

Apologies for not getting to this sooner.  I think we should remove flow from the branch yes. :)

I will review your PR when I have a larger slice of time, but for now lets keep it alive and then we can merge the latest `next` into it when `next` settles before doing a merge and release.

Thanks again for your help.  ⭐️

**Comment by sergiokopplin** [comment]
@ctrlplusb thank you for the awesome work here!

**Comment by ctrlplusb** [comment]
Closing this as the redux branch will be overhauled soon.
