### ISSUE TITLE
Best way to restrict rendering of component to server or client side.

### ISSUE THREAD

**Issue by codepunkt** [ctrlplusb/react-universally#332]
Hey everyone!

I've recently been wondering what the best way to render parts of the component tree client-side only or server-side only would be.

### Use-Case
An off-canvas menu that slides in from the right on lower screen widths with translate3d inline animations using `react-motion` and a fixed menu that is on the left side of the layout permanently on larger screen widths. Menu contents are basically the same.

When rendering server side, server has to render one or the other, but not both. As the server doesn't know about the state of the media queries on the client side prior to sending its data, i get about 50% invalid checksums on client-side rehydration - depending on the media query defaults set on the server.

What i plan on doing is rendering an invisible menu with the same contents as both the fixed and animated menus on the server-side for seo purposes and render either the animated toggleable off-canvas or the fixed version of the menu on the client depending on media query matches.

I know there's a lot to be discussed with this approach - feel free to write down your thoughts!

```javascript
/// simplified
const Layout = () => (
  <Header />
  <Content />
  {!isServer && (
    <MediaQuery maxWidth={1000}><Motion><Menu /></Motion></MediaQuery>
    <MediaQuery minWidth={1001}><Menu fixed /></MediaQuery>
  )}
  {isServer && <Menu invisible />}
);
```

The main thing i'm asking for with this issue is opinions on where to set and how to access the `isServer` variable inside the components render, though. So far, i have two approaches to this:

#### 1. Context
At the topmost level of the server Element hierarchy, one could add a `ServerContext` such as this.

```javascript
class ServerContext extends React.Component {
  getChildContext() { return { isServer: true }; }
  render() { return React.Children.only(this.props.children); }
}

ServerContext.propTypes = {
  children: React.PropTypes.node.isRequired,
};

ServerContext.childContextTypes = {
  isServer: React.PropTypes.bool.isRequired,
};

// Create our React application element.
const reactAppElement = (
  <ServerContext>
    <CodeSplitProvider context={codeSplitContext}>
      <ServerRouter location={request.url} context={reactRouterContext}>
        <DemoApp />
      </ServerRouter>
    </CodeSplitProvider>
  </ServerContext>
);
```

Doing so, it should be possible to read the `isServer` from the context like this:

```javascript
const Layout = (_, { isServer }) => (
  // render stuff here
);
```

##### Scoped variable and `forceUpdate`
```javascript
let isServer = true;

class Layout extends React.Component {
  componentDidMount() {
    requestAnimationFrame(() => {
      isServer = false;
      this.forceUpdate();
    });
  }
}
```
##### Component state

```javascript
class Layout extends React.Component {
  constructor() {
    super();
    this.state = { isServer: true };
  }
  componentDidMount() {
    requestAnimationFrame(() => {
      this.setState({ isServer: false };
    });
  }
}
```

Any thoughts? 😄

**Comment by smirea** [comment]
can't you use the `process.env.IS_SERVER` variable defined from webpack?

alternatively you can only render the off-screen menu once your component mounted - similar to your #2 approach, but with setState:

```js
class Layout extends PureComponent {
    state = {
        renderMenu: false,
    };

    componentDidMount () { this.setState({renderMenu: true}); }

    render () {
        return (
        <div>
            <Header />
            <Content />
            {!showMenu ? null : (
              <MediaQuery maxWidth={1000}><Motion><Menu /></Motion></MediaQuery>
              <MediaQuery minWidth={1001}><Menu fixed /></MediaQuery>
            )}
        </div>
        );
    }
);
```

this way your initial render should always be the same - with the menu completely missing - since componentDidMount() only gets called on the client

**Comment by codepunkt** [comment]
@smirea Thanks, how could i have missed the `IS_SERVER` variable? 👍  I don't want to omit the menu on the server render for SEO-purposes, though!

**Comment by codepunkt** [comment]
@smirea
- `setState` in `componentDidMount` is discouraged - see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md for more information. that's why i wrapped it in `requestAnimationFrame`. i assume i could've just ignored the lint errors, though. using rAF it still renders the component twice
- `process.env.IS_SERVER` could be used. If i use it like that, it will get replaced by webpack's `DefinePlugin` and optimized away, which will then lead to checksum errors in development mode. I tried doing `const { IS_SERVER } = process.env;` prior to using the variable - but it isn't set.

**Comment by ctrlplusb** [comment]
Personally I wouldn't get too much of a hangup about using `componentDidMount`.  As far as I know the eslint rule exists simply to prevent you from doing wasteful re-renders.  But if you are running an SSR app then you can't get around this at times as it's the only safe way to execute browser dependant code on mount without it throwing out the server.

I think it's a case of making a pragmatic decision which you can then comment your intentions for.

**Comment by ctrlplusb** [comment]
Also, I recommend against using the IS_SERVER/etc flags as much as you can.  Use it as an absolute last resort.
