### ISSUE TITLE
analyze script analyzes client in development mode instead of production mode

### ISSUE THREAD

**Issue by AndreasZeiser** [ctrlplusb/react-universally#333]
Hey Sean!

Commit https://github.com/ctrlplusb/react-universally/commit/bb3f710bb7b20b6a4f65abf054e07dc843e273cb sets the default mode from `production` to `development` in the client and server configuration which causes the analysis to run on the development build of the client.

**Comment by ctrlplusb** [comment]
Great spot! Thanks

**Comment by ctrlplusb** [comment]
Fixed on `next` branch.
