### ISSUE TITLE
react-async-component

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-universally#335]
I would imagine you plan to move this over to react-async-component rather than code-split.  I am actually working on a route system that will dynamically and asynchronously load routes which is how I found that.  I don't want to use code-split for this if its going to change.  Any idea on when you might plan to convert the boilerplate?

**Comment by ctrlplusb** [comment]
Yep, I certainly plan to, but I am giving it a bit of time on my personal project to work out a few of the links :-)

**Comment by ctrlplusb** [comment]
On the `next` branch.
