### ISSUE TITLE
Access components from common root

### ISSUE THREAD

**Issue by bryaan** [ctrlplusb/react-universally#336]
Directory Structure:

```
DemoApp
/components
  /Button
    /index.js
/About
  /index.js

```
In my `About/index.js` file I want to do:

```js
import Button from 'components/Button' 
```
instead of:

```js
import Button from '../components/Button' 
```
Which can quickly become a problem for large apps requiring multiple walks back up the directory tree.

How can I set this up?

**Comment by ctrlplusb** [comment]
Hey @BryanARivera 

There have been a few discussions on this.

See #318 and #203 ✌️

**Comment by BryanARivera** [comment]
@ctrlplusb I don't see any ref to it in the FAQ as you had suggested.  Is there any concrete example or just these clues?

**Comment by BryanARivera** [comment]
If I want to use @bradennapier's solution, which file should that snippet go in?

**Comment by BryanARivera** [comment]
@bradennapier You posted that you had IDE tooling to inject relative paths.

Do you know of any such plugin for Atom?

**Comment by bradennapier** [comment]
Hey Bryan, 
  What I showed was using aliases.  Here is my resolve from configFactory.js

```javascript
resolve: merge(
      // These extensions are tried when resolving a file.
      {
        extensions: config.bundleSrcTypes.map(ext => `.${ext}`)
      },
      // Add to resolve modules to reduce ../ overhead
      {
        modules: [ './shared', path.resolve(appRootDir.get(), 'src/shared'), 'node_modules' ],
        plugins: [ 
          componentResolver('existing-directory', 'undescribed-raw-file')
        ]
      },
      // Within aliases we allow specifying ~path to make it relative
      // to the appRootDir.  This way we don't need to have 'path' within
      // the config file.
      ifElse(config.webpack_aliases)(() => ({
        alias: Object.keys(config.webpack_aliases).reduce((p, c) => {
          const a = config.webpack_aliases[c]
          if ( a.startsWith('~') && ! a.startsWith('~/') ) {
            p[c] = path.resolve(appRootDir.get(), a.replace('~', ''))
          } else { p[c] = a }
          return p
        }, {})
      }))
    ),
```

I am actually not using the aliases anymore as this method of resolving seems to work perfectly for me.

This method allows me to include "shared" components at different hierarchy levels which is pretty awesome.  For example, given this directory structure:

![image](https://cloud.githubusercontent.com/assets/15365418/22134802/b2351c8e-de7e-11e6-950a-8a4e2f0e9074.png)

Within ProjectDashboard or ProjectSelect I can do 

```javascript
import MyComponent from 'components/MyComponent'
```

whereas ALL screens can access

```javascript
import Button from 'components/Button/Modern'
```

obviously you have to make sure you don't create clashes which shouldn't generally be an issue since "shared" components should be used as little as possible.

**Comment by bradennapier** [comment]
I do not need or inject any kind of relative paths.  My setup as described appears to do the job as needed.

**Comment by BryanARivera** [comment]
I will have to give your approach consideration.

Is there any simple edit to what you just posted that would allow this work in any folder?

I assume a 'dirty' hack would be to place the entire project in `/shared`.  Is that correct?

**Comment by bradennapier** [comment]
This sets the entire root "shared" directory as a relative path as well as the trickle-down effect.

**Comment by BryanARivera** [comment]
I see.  That means both approaches work together.  Will implement your code. Thanks!

**Comment by smirea** [comment]
@bradennapier how did you make your resolve modules work with server side rendering? I get "cannot find module" errors if I try to use that approach...

**Comment by bradennapier** [comment]
@smirea I believe these are the key pieces to the puzzle

```
{
        modules: [ './shared', path.resolve(appRootDir.get(), 'src/shared'), 'node_modules' ],
        plugins: [ 
          componentResolver('existing-directory', 'undescribed-raw-file')
        ]
      },
```

I had the same issue originally.  The key is using the relative shared and the absolute shared.  Once I had both in there it works across the board both server and client and has been excellent.

**Comment by smirea** [comment]
is the `componentResolver` necessary? I have

```js
    resolve: merge(
      // These extensions are tried when resolving a file.
      {
        extensions: config.bundleSrcTypes.map(ext => `.${ext}`)
      },
      // Add to resolve modules to reduce ../ overhead
      {
        modules: [ './shared', path.resolve(appRootDir.get(), 'src/shared'), 'node_modules' ],
      },
    ),
```

and it still fails

**Comment by bradennapier** [comment]
I don't think it should be, that is for a different purpose, although it's a very nice plugin.  Have you restarted your entire process?

**Comment by smirea** [comment]
yep, i'm doing `rm -rf .happypack; rm -rf build; npm run development` just to be sure. Same thing happens if I build and try to run the production build. 

Everything works fine if I disable server side rendering, so this is exclusively an issue within the node env. 

You sure you're also not setting custom `NODE_PATH=./src/shared` or something somewhere? That's how you used to hack it for node before. 

Also, how is your `componentResolver` configured?

**Comment by bradennapier** [comment]
Its just https://github.com/mgcrea/component-webpack-resolver-plugin which allows me to have a better organizational structure.

Are you including "shared" when you try to import?  Odd that it is working here.  Maybe its something new in Node? I'm on 7.4

```
/shared
-- /components
---- /MyComponent
------ /MyComponent.js
```

```javascript
import MyComponent from 'components/MyComponent`
```

**Comment by bradennapier** [comment]
I have made quite a few modifications to how things work so i'm looking to see if I added something else to make it work, but I'm pretty sure that was all I did on that regard.

**Comment by bradennapier** [comment]
```
resolve: {
      // These extensions are tried when resolving a file.
      extensions: config.bundleSrcTypes.map(ext => `.${ext}`), 
      
      // Allow recursive searching through ./shared folders in our app 
      // to reduce ../ overhead required.
      modules: [ './shared', path.resolve(appRootDir.get(), 'src/shared'), 'node_modules' ],
      
      // Allow us to import a folder and have it look for the matching filename
      // for example
      // import Component from 'shared/components/MyComponent' would find
      // shared/components/MyComponent/MyComponent.js
      plugins: [ 
        componentResolver('existing-directory', 'undescribed-raw-file')
      ],
      
      alias: config.webpack_aliases &&
        Object.keys(config.webpack_aliases).reduce((p, c) => {
          const a = config.webpack_aliases[c]
          if ( a.startsWith('~') && ! a.startsWith('~/') ) {
            p[c] = path.resolve(appRootDir.get(), a.replace('~', ''))
          } else { p[c] = a }
          return p
        }, {
        // Merging any defined aliases in config with the items
        // below.
        // This is required for the modernizr-loader
        // @see https://github.com/peerigon/modernizr-loader
        modernizr$: path.resolve(appRootDir.get(), './.modernizrrc')
      })
    },
```

**Comment by bradennapier** [comment]
Ahh I think I know the issue, you can not use the relative paths until you are in the es6 environment.

**Comment by ctrlplusb** [comment]
Closing this for now.

**Comment by oyeanuj** [comment]
@bradennapier @smirea @bryaan Where did you folks end up with this? What all did you folks end up modifying or adding to make this work?

**Comment by SleepWalker** [comment]
I've changed `config/values.js` like so:

```js
import appRootDir from 'app-root-dir';

const values = {
    // ...
    webpackConfig: (webpackConfig, buildOptions) => {
      // eslint-disable-next-line no-unused-vars
      const { target, mode } = buildOptions;

      // Example:
      /*
      if (target === 'server' && mode === 'development') {
        webpackConfig.plugins.push(new MyCoolWebpackPlugin());
      }
      */

      // Debugging/Logging Example:
      /*
      if (target === 'server') {
        console.log(JSON.stringify(webpackConfig, null, 4));
      }
      */

      webpackConfig.resolve.modules = ['node_modules', appRootDir.get()];

      return webpackConfig;
    },
};
```

Then for other cli things I've used `NODE_PATH` env variable, e.g.:

```js
"scripts": {
   // ...
    "test": "cross-env NODE_PATH=./ jest"
}
```

After this changes applied you can do something like (and yes, it would work everywhere, even outside webpack, if you won't forget to update all the cli commands):

```js
import config from 'config';
import { Button } from 'shared/components/ui';

// ...
```

In my project I've renamed `shared` to `app`, which makes the imports to look nicer.


Btw., probably it would be better to read the `NODE_PATH` from env and use it in webpackConfig to avoid duplication

**Comment by SleepWalker** [comment]
actually, if we will read `NODE_PATH` it will be possible to move that webpack config chunk in configFactory which will allow the support of absolute module pathes for all the users, that want to have such feature in their project. Simply add `NODE_PATH` and done. This may be done using `.env` files too if I'm not mistaken.

@ctrlplusb what do you think about this?

**Comment by oyeanuj** [comment]
@SleepWalker With that configuration, are you able to access paths in `shared`/`app` even when in files in `server` or `client`?

**Comment by SleepWalker** [comment]
Yep. It should work everywhere

On Oct 24, 2017 03:27, "Anuj" <notifications@github.com> wrote:

@SleepWalker <https://github.com/sleepwalker> With that configuration, are
you able to access paths in shared/app even when in files in server or
client?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ctrlplusb/react-universally/issues/336#issuecomment-338834955>,
or mute the thread
