### ISSUE TITLE
Best way to render route with async data?

### ISSUE THREAD

**Issue by GerardoGallegos** [ctrlplusb/react-universally#339]
I love this asome project!  I've been doing some tests but I had a question on what is the best way to render a path that depends on external data (database) As the following example:

```javascript
//  In this case I use async await but could be a classic Promises

class Users extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      data: []
    }
  }

  async componentWillMount() {
    const res = await fetch(`/api/data`)
    const data = await res.json()

    this.setState({
      data
    })
  }

  render() {

    const { data } = this.state

    return (
      <ul>
        {
          data.map(item => (
            <li key={ item.id }>
              { item.name }
            </li> 
          ))
        }
      </ul>
    )
  }
}

```
The above example works perfectly because ```componentWillMount``` is asynchronous, once the data is loaded it is called ```setState``` And the render shows the items in UI.. cool so far. But... The problem is that the first render and the one that is sent to the client does not include the items, because they will be loaded until the data is loaded, this can affect the SEO :'( Some idea how to load the asynchronous data before sending The first render to the client?

**Comment by ctrlplusb** [comment]
I am a bit biased but there is another awesome project called [`react-jobs`](https://github.com/ctrlplusb/react-jobs) to help you with this.

```
import { withJob } from 'react-jobs/ssr';

function Users({ job }){
  if (job.inProgress) {
    return <div>fetching...</div>
  }

  if (job.error) {
    return <div>failed.</div>
  }
  
  return (
    <ul>
      {
        job.result.map(item => (
          <li key={ item.id }>
            { item.name }
          </li> 
        ))
      }
    </ul>
  )
}

export default withJob(() =>
  fetch(`/api/data`).then(res => res.json())
)
```

👍

**Comment by GerardoGallegos** [comment]
@ctrlplusb Thank you very much, I reviewed [``react-jobs``](https://github.com/ctrlplusb/react-jobs) and is great, I will be doing tests but I see that it's perfect for what I need. I will be very attentive of these projects and I will try to contribute,
