### ISSUE TITLE
[HMR] unexpected require(18) from disposed module 7

### ISSUE THREAD

**Issue by nathanvale** [ctrlplusb/react-universally#34]
I am seeing this error come up when I edit my async components. I was wondering if you have seen this issue before and if it is something that came be resolved.

Thanks.

**Comment by ctrlplusb** [comment]
Hmmm, I am making some adjustments to the HMR configuration (#35).  I'll let you know when done.  It may help with this.

**Comment by ctrlplusb** [comment]
Could you try the following change:
https://github.com/ctrlplusb/react-universally/blob/master/src/client/index.js#L48

**Comment by nathanvale** [comment]
Here are the steps to reproduce with console open.

1. Start on home page - make a edit to your home text and notice HMR update
2. Click on about link notice HMR warning message in the console [HMR] unexpected require(397) from disposed module 60
3. Make an edit to your about text and notice that a hot update.js file is generated but it is not rendered. HMR is dead 😬

It appears that HMR async routes and not completing working with react hot reload 3?

**Comment by ctrlplusb** [comment]
@nathanvale thanks for the report and extra info.  I am gonna try this right now quick.

**Comment by ctrlplusb** [comment]
Damn damn damn.  I'll need to backtrack my updates.  This is a newly introduced issue.

Thanks for the report.

**Comment by ctrlplusb** [comment]
Ok, I have tracked down the issue.  It's definitely occuring when a `Route` is configured to resolve asynchronously.  

I have found a workaround solution.  We still get the "required disposed module" warning, however HMR still kicks in.  I am going to do a bit further testing and try out a few other ideas before pushing this change.

**Comment by ctrlplusb** [comment]
@nathanvale pushed.

I've had to put a workaround in the `routes/index.js` file to support HMR on dynamic routes.  Please see the respective source for details.

**Comment by nathanvale** [comment]
Nice work!

**Comment by Bamieh** [comment]
this issue is re-appearing? im getting this logs

```
[HMR] unexpected require(./configs/routes/home/index.js) from disposed module ./configs/routes/index.js
[HMR] unexpected require(./configs/routes/errors/404/index.js) from disposed module ./configs/routes/index.js
```
both are async modules, when HMR kicks in, these errors occur
