### ISSUE TITLE
Not working with Safari

### ISSUE THREAD

**Issue by rlindskog** [ctrlplusb/react-universally#341]
Anyone else having trouble running on Safari?  

The errors

On the page

`Error: Failed to resolve configuration value at "htmlPage.htmlAttributes". We have noticed that you are trying to access this configuration value from the client bundle (i.e. browser) though. For configuration values to be exposed to the client bundle you must ensure that the path is added to the client configuration filter file, which is located at "config/clientConfigFilter.js".
`

In the console

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' cdn.polyfill.io 'nonce-345d5614-1c69-4db0-8048-ff8df10162a4' localhost:7331".
`

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' cdn.polyfill.io 'nonce-345d5614-1c69-4db0-8048-ff8df10162a4' localhost:7331".
`

`Refused to load the script 'https://cdn.polyfill.io/v2/polyfill.min.js' because it violates the following Content Security Policy directive: "script-src 'self' cdn.polyfill.io 'nonce-345d5614-1c69-4db0-8048-ff8df10162a4' localhost:7331".
`

I think a fix might be with the Content-Security-Policy, allowing 'unsafe-inline'.  Nonce isn't supported in Safari.

**Comment by codepunkt** [comment]
First problem seems to be the same as #326 in Edge.

To solve the second part, combine the nonce with the unsafe-inline directive. If the UA supports nonces, the 'unsafe-inline' source will be ignored, and all scripts will be checked for the nonce. Safari, in this case, would not be able to make any sense of the nonce but would pick up 'unsafe-inline'. This is a trick to make the introduction of the nonces backwards compatible.

**Comment by codepunkt** [comment]
@rlindskog Lets assume the `htmlPage.htmlAttributes` is looked at in issue #326 😁

**Comment by ctrlplusb** [comment]
Fix should be on master.
