### ISSUE TITLE
v13 approaches

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#345]
A _big_ rewrite.  Check the changelog within the `next` branch for a full list of breaking changes and new features.  

I've been using this starter in some production projects with other devs and have come across some issues and places where things can be improved.  The biggest one is the replacement of `code-split-component` with `react-async-component`.

I believe this version addresses problems that are described/affected within: 
#343 
#335
#333 
#279 
#301 

As well as a few others which haven't been reported as of yet. 😂

**Comment by strues** [comment]
Great work. Rather than make a branch and PR I'll just suggest it here: Extract-Text-Webpack-Plugin has a beta 5 available, which gets rid of the peer dependency for outdated Webpack versions.

**Comment by lucianlature** [comment]
@ctrlplusb Probably the [new React Router beta](https://reacttraining.com/react-router/) should be part of version 13.

**Comment by ctrlplusb** [comment]
@lucianlature most definitely! :)

**Comment by strues** [comment]
The new changes with the React Router beta are pretty substantial. I've implemented it in a personal branch off of Next without the async component. Still ironing out some quirks.

**Comment by diondirza** [comment]
Without noticing this thread, i just made a PR for updating our master branch using beta version of react router, should I change it to merge with next branch instead?

**Comment by strues** [comment]
Anyone else @ctrlplusb @diondirza spent some time with the RR4 beta? The discussion [here](https://github.com/ReactTraining/react-router/issues/4407) is applicable. I'm not very fond of the solution. Curious to hear other experiences

**Comment by ctrlplusb** [comment]
FYI guys this isn't dead. I am doing a production project with a team and plan on transferring the golden updates to this release. Some solid updates to configuration and NODE_ENV handling will be far more natural.

**Comment by smirea** [comment]
@ctrlplusb do you have a ballpark estimate on this, days/weeks? no rush, just excited

**Comment by ctrlplusb** [comment]
Just landed a huge update!

**Comment by elektronik2k5** [comment]
First, thank you all for this awesome project and your efforts to maintain and develop it further! :bowing_man: :bowing_man: :bowing_man: 
I've chosen react-universally over react starter kit to start a new project and am curious whether I should work with v12 or just use the next branch? Is there an estimate to when you think v13 will be ready?

Thanks again! =)

**Comment by hchoriq** [comment]
And don't forget to make any necessary updates to docs ;) :bowing_man:

**Comment by diondirza** [comment]
@elektronik2k5 I suggest you go with next branch, since v12 has so many differences in so many ways with v13 and it will make extra cost on your project timeline to migrate your project if in the middle v13 get released. And you might get confused to see how different project structure of v12 has with v13 has. FTW go with next branch, I think it will be released soon enough.

**Comment by ctrlplusb** [comment]
Yep, I do plan on releasing v13 fairly soon. :)

**Comment by birkir** [comment]
Awesome work 🎉 

We are planning to drop our own starter kit (http://github.com/ueno-llc/starter-kit) in favour of this one as it's well maintained, has good community and is pretty close to our old one so our team doesn't have a steep learning curve.

We have a fork where we have made some crucial changes that our team depends on and will be merging the upstream a lot https://github.com/ueno-llc/starter-kit-universally (currently on the next branch).

**Comment by ctrlplusb** [comment]
@birkir that is fantastic news!  Excited for this. 🙏

**Comment by strues** [comment]
The plan is to keep all the existing feature branches up to date, right? I've implemented Apollo on the Next branch. If you'd like I can get a PR ready to bring the Apollo branch up to date. Save some of the merge conflict troubles.

**Comment by ctrlplusb** [comment]
Dude, awesome! Thanks 💗

**Comment by strues** [comment]
All taken care and PR is in. One caveat is I've not been able to get graphiql to play nicely with CSP. In order to make it work, we'd need a nonce on graphiql itself.

Since graphiql should really only be used in development, a solution could be to disable CSP completely in dev from the config. Or a process.env flag

**Comment by diondirza** [comment]
@ctrlplusb seems, next branch document title doesn't work properly. It's related to react-helmet usage in server, this will break google crawl I guess.

```javascript
// ServerHTML.js
...
return (
  <HTML
    title={config('htmlPage.defaultTitle')}
    description={config('htmlPage.description')}
    appBodyString={reactAppString}
    headerElements={
      headerElements.map((x, idx) => <KeyedComponent key={idx}>{x}</KeyedComponent>)
    }
    bodyElements={
      bodyElements.map((x, idx) => <KeyedComponent key={idx}>{x}</KeyedComponent>)
    }
  />
);
...
```
That title props not updated dynamically, I guess we should react-helmet instead of config title on this part.

**Comment by ctrlplusb** [comment]
@diondirza you are completely correct! Good spot!

Do you mind making a separate issue for this so that we can track it better?

Thanks!

**Comment by oyeanuj** [comment]
@ctrlplusb Wondering if you came across Pinterest's new package for service workers - https://github.com/pinterest/service-workers and how you thought it compared to the current one being used in `next`?

**Comment by ctrlplusb** [comment]
Finally... released!

**Comment by ctrlplusb** [comment]
@oyeanuj No I hadn't seen that yet.  Will take a look, thanks!
