### ISSUE TITLE
Stream not working

### ISSUE THREAD

**Issue by ritz078** [ctrlplusb/react-universally#346]
I am trying to stream a video via the server but I am not able to do it. Download works but stream doesn't. The same code implementation is a other server works fine. Maybe something to do with security ? or anything else ? Help is appreciated.

The streaming is working fine on firefox.

**Comment by codepunkt** [comment]
@ritz078 Can you elaborate on your findings? What was the problem, how did you manage to fix it?

**Comment by ritz078** [comment]
eventually it turned out to be an error in the Range header of the video content that was identified correctly by firebox but not by chrome. 

From:
```
res.setHeader('Content-Length', range.end - (range.start + 1));
```

To:
```
res.setHeader('Content-Length', range.end - range.start + 1);
```

The error was actually caused by running `eslint --fix` that automatically introduced brackets.

**Comment by codepunkt** [comment]
Thanks! Maybe this will help someone in the future! :)
