### ISSUE TITLE
Question regarding "dev" configuration

### ISSUE THREAD

**Issue by saniko** [ctrlplusb/react-universally#348]
Hi folks,

Thank you very much for this great project, I'm learning a lot from it!

I'm trying to migrate from an existing project.
Basically, it contains a (monolithic) css file, font and images folders as well as some js.

Have no problem with the react/js part.
I have placed the css file, both images and font folder under the demoApp for initial testing,
Some CSS class have an image as a background URL.

When running in 'development' mode, i cannot see the images on front-end.
No issue if I run the "build" and "start" scripts, images appear with no issues.

As for the fonts, I'm getting this error on console on both cases:

> Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIw4ABEAAAABQcAAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "font-src 'self' localhost:7331".

I'm using ttf fonts (the error relates to woff?)

Probably some configuration issue.
Would appreciate any help.

Best.

**Comment by lucianlature** [comment]
In `src/server/middleware/security.js` you need to add `data` to `fontSrc` in `cspConfig` configuration object:

```
fontSrc: ["'self'", 'data:'],
```

**Comment by saniko** [comment]
Thanks.
Modified security with:
` fontSrc: ["'self'","'data:'"]`

Same issue like images, fonts and images are not loaded when i run in "development" mode.

**Comment by lucianlature** [comment]
@saniko Don't enclose `'data:'` again between double quotes. Leave it as `["'self'", 'data:']`

**Comment by saniko** [comment]
Any thoughts on why I don't see images and fonts when running 'development' ?

Thanks.

**Comment by lucianlature** [comment]
@saniko: can you send us the URL you're using for an image that does not get displayed in 'development'?

**Comment by saniko** [comment]
`
   background:url(/images/home-icon.png) no-repeat;
    src:url(/fonts/Montserrat-Bold.ttf);
}`

font and images folders are located under 'components' , tried inside 'demoApp' as well.
In dev build all works fine.

Thanks.

**Comment by diondirza** [comment]
@saniko have you got this working already?

**Comment by saniko** [comment]
Unfortunately no.
Getting no errors, simply don't see fonts and images when running development,
all works fine when running the build.
Probably some minor stupid issue I'm not seeing.

**Comment by diondirza** [comment]
@saniko try to move your assets under public folder, since it's not imported with webpack you should put all your static file on that folder.

**Comment by saniko** [comment]
It's already there.

**Comment by ctrlplusb** [comment]
I suspect this may be an issue with the development server port that runs for the client bundle.  I'll ping you back soon with a URL to try and hit.

**Comment by diondirza** [comment]
ah I see, thats because we use source map, that makes our image relative path referred to dev port which has different port with your current port. Try to remove this code `query: { sourceMap: true }` in  this [line](https://github.com/ctrlplusb/react-universally/blob/master/tools/webpack/configFactory.js#L405), it should works.

**Comment by ctrlplusb** [comment]
@saniko what do you see when you hit the following URL?

http://localhost:7331/__webpack_hmr

**Comment by saniko** [comment]
A 'data' property with a huge json file,
Are looking for specific info?

**Comment by ctrlplusb** [comment]
Nah, that sounds good. Was just a quick health check.

How are you importing your fonts?

**Comment by diondirza** [comment]
@saniko Does my solution works for you? Try checkout my [branch](https://github.com/diondirza/react-universally/tree/public-image), I have replicate your issue, seems its working fine now.

**Comment by saniko** [comment]
@diondirza got webpack error,
My file structure is different then yours though.

**Comment by diondirza** [comment]
what is that error? Could you post it? that branch based on next branch. Like I said if you referenced an image in css put it in public folder, if you follow my sample in that branch it would working just fine. Don't forget to add `root` option in css loader query.

**Comment by saniko** [comment]
My project is based on master.
My images and fonts folders in the public folder.
Maybe it's best that I will wait for v13?

Thanks for helping,

This is the error:

==> DEVELOPMENT -> Webpack config is invalid, please check the console for more information.
TypeError: (0 , _config2.default) is not a function
    at webpackConfig.plugins.ifDevClient (C:/***/****/tools/webpack/configFactory.js:406:33)
    at execIfFuc (C:/***/****/tools/utils.js:53:55)
    at ifElseResolver (C:***/****/tools/utils.js:54:24)
    at webpackConfigFactory (C:/***/****/tools/webpack/configFactory.js:397:7)
    at createCompiler (C:/***/****/tools/development/hotDevelopment.js:29:29)
    at resolve (C:/***/****/tools/development/hotDevelopment.js:89:28)
    at HotDevelopment.Promise.resolve.then (C:/***/****/tools/development/hotDevelopment.js:87
:15)
(node:15352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: (0 , _config2.d
efault) is not a function
(node:15352) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
 not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ctrlplusb** [comment]
Hey @saniko you may need to share your project here so that we can debug.  Looking at your stack trace it looks like a configuration issue to me.

**Comment by saniko** [comment]
Thanks,
I think it's best that I will test this on V13 when it's released.
If The problem reproduces I will reopen.

**Comment by oyeanuj** [comment]
@diondirza @saniko I'm curious if you folks managed to solve this and what the solution here was? I'm on `v13` and struggling to get a local image as background image to work:
```css
.container {
  background: url('./local_image.jpg');
}
```

I've already tried disabling the source map but that doesn't seem to help :/
