### ISSUE TITLE
Helmet config missing from next branch

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#349]
I don't see `react-helmet` being properly configured on the `next` branch. It looks like values are taken from the config to set title and description in `HTML.js`, but the `<Helmet ... />` component is missing from `DemoApp.js`.

**Comment by ctrlplusb** [comment]
Hey @carsonperrotti yeah sorry I have tried to minimize the configuration we expose for helmet.  Things like the mobile responsive settings and icons etc feel like they are more of a fixed item to me, whilst title etc are the things more likely to change.  Sorry if this has caused some confusion.

I am open for any discussions/suggestions on this though.

**Comment by carsonperrotti** [comment]
No worries. I was just having issues including scripts to be shared with Helmet. That's all I really need it for other than title. Was that a config issue or user error here?

**Comment by ctrlplusb** [comment]
Ah, no worries.  You can still use/add the Helmet component anywhere you like. :)
