### ISSUE TITLE
cross-env on devDependencies

### ISSUE THREAD

**Issue by sergiokopplin** [ctrlplusb/react-universally#355]
Hello!

I'm having some problems with production build due to errors related to production dependencies, so the production environment install only the production dependencies (which is just the package.json dependencies, not devDependencies).

In my case, i solved moving the cross-env to "dependencies".
Can we move this dependency from "devDependencies" to "dependencies"?

---

Thanks for the awesome project, i'm using on production! :)

**Comment by ctrlplusb** [comment]
Hey @sergiokopplin!

Thanks, glad to hear that you are finding this project helpful. 😀

Sure thing about `cross-env`!

**Comment by sergiokopplin** [comment]
@ctrlplusb should i create a pr? let me know!

**Comment by ctrlplusb** [comment]
Hey @sergiokopplin I have ended up removing `cross-env` as we no longer need it based on the updates to v13.  🎉

It's all on the `next` branch.

**Comment by sergiokopplin** [comment]
thanks for the update @ctrlplusb. awesome work here!!!
