### ISSUE TITLE
PR for pre-commit linting and adding stylelint?

### ISSUE THREAD

**Issue by elektronik2k5** [ctrlplusb/react-universally#358]
I'm using react-universally for a new project and plan to add these features from https://github.com/kriasoft/react-starter-kit:

1. [lint-staged](https://github.com/okonet/lint-staged) and a git pre-commit hook for:
2. eslint
3. [stylelint](https://github.com/stylelint/stylelint)
4. maybe [stylefmt](https://github.com/morishitter/stylefmt)

Would you like me to add it as a PR or a feature branch? V12 or V13?

**Comment by ctrlplusb** [comment]
Hey @elektronik2k5 

Thanks for you interest in contributing! 😀

I haven't had any experience with these tools specifically but have used pre-commit hooks in the past.  I could definitely consider this aspect, however, I would shy away from `stylelint` as it infers the use of standard CSS which won't be the case for everyone (I tend to use CSS-in-JS frameworks exclusively myself).

I would be happy to consider a PR for the rest though.  Defo work of the `next` branch. 👍

**Comment by ctrlplusb** [comment]
We can track this via PR.
