### ISSUE TITLE
[v13] Disabling SSR causes server to fail

### ISSUE THREAD

**Issue by evanrs** [ctrlplusb/react-universally#362]
Server fails to render when `disableSSR: true`. Instead it produces several `TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null` from the `ServerHTML` component. 

These result from array spreads on conditionally included values from `helmet`. But, when `disableSSR: true` the `helmet` prop is omitted in [`reactApplication`](https://github.com/ctrlplusb/react-universally/blob/next/server/middleware/reactApplication/index.js#L26-L33) and our the render fails.

This can be fixed by using [lodash/result](https://lodash.com/docs/4.17.4#result) instead `onlyIf` in these instances.
```js
// server/middleware/reactApplication/ServerHTML.js
import result from 'lodash/result'

// … line 64
  const headerElements = removeNil([
    ...result(helmet, 'meta.toComponent', []),
    ...result(helmet, 'link.toComponent', []),
    onlyIf(
      clientEntryAssets && clientEntryAssets.css,
      () => stylesheetTag(clientEntryAssets.css),
    ),
    ...result(helmet, 'style.toComponent', [])
  ]);


// … line 108
    ...result(helmet, 'script.toComponent', []),
  ]);
```

**Comment by bradennapier** [comment]
Also discovered this - thanks for the fix evanrs

**Comment by ctrlplusb** [comment]
Thanks for the report!  Apologies for the delay getting to this.
