### ISSUE TITLE
preact magic?

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-universally#364]
What is the magical piece I am missing to make preact work with this?  I just keep getting that react is not found yet preact is definitely aliased in package.json, module-alias is present, and i aliased in webpack config.

**Comment by ctrlplusb** [comment]
Are you on `master` or `next`?

**Comment by ctrlplusb** [comment]
I was doing some messing about on `next` with aliases, which has since been reverted.  Standard preact-compat aliasing should work there again. x
