### ISSUE TITLE
Can't get 'transform-class-properties' to work

### ISSUE THREAD

**Issue by bslinger** [ctrlplusb/react-universally#368]
This is on the latest commit to the 'next' branch - I've tried adding `babelConfig.plugins.push('transform-class-properties');` to the `babelConfig` function in `config/values.js`, and messed around with adding different presets to the `configFactory.js`.  No matter what I do I either get `Unexpected token` or `SyntaxError: Missing class properties transform.`

I had it working on an older version (I think I was coming from v10 or v11) but can't seem to figure it out here. Any help would be appreciated :)

**Comment by birkir** [comment]
Which branch are you using? (master, mix of feature branches, next, etc.)

Maybe try to use stage-2 (which includes `transform-class-properties`) instead of stage-3 and see if that works.

**Comment by bslinger** [comment]
I'm using the `next` branch. I tried changing it to stage-2 [here](https://github.com/ctrlplusb/react-universally/blob/next/internal/webpack/configFactory.js#L370) but got `BabelLoaderError: SyntaxError: Missing class properties transform.`. I also tried re-arranging the presets in a few different orders based on some stackoverflow posts.

**Comment by ctrlplusb** [comment]
Hmmm, sorry quick one, not sure if this will help but also remember to update the .babelrc at root to ensure tooling handles same level.  Can't say if this will sort your case though.

**Comment by birkir** [comment]
Ok, you have to move the `stage-2` below `ifClient(['latest', { es2015: { modules: false } }]),`, otherwise you'll get errors with some babel plugins. Same with `.babelrc`.

**Comment by diondirza** [comment]
```
presets: [
  ifClient(['latest', { es2015: { modules: false } }]),
  ifNode(['env', { targets: { node: true }, modules: false }]),
  'stage-0',
  'react',
].filter(x => x != null),
```
Usually using `stage-0` preset like this without a problem,  reorder it like original sequence will make the compile failed. I guess it should works with stage-2 as well.

**Comment by mschipperheyn** [comment]
So, putting this in .babelrc doesn't work?

**Comment by bslinger** [comment]
Sorry for going silent, I have limited time to work on this project. I wasn't able to solve this issue, and I was only using class properties in one component anyway so I've just gotten rid of them. I tried the different order of presets but I'm not familiar enough with all the configuration to know that it was even pulling it from the right place. I'll close this ticket now.
