### ISSUE TITLE
Serialise 'initialState' Containing Immutable JS

### ISSUE THREAD

**Issue by Braden1996** [ctrlplusb/react-universally#375]
Hey, first of all, what you guys have made is extremely impressive. Scraped my janky old build setup and migrated this into my current project. Also, I am quite new to web applications, and am still learning, so I apologise in advance!

My project makes use of Redux and Immutable JS for most of the state objects. I used your master branch, instead of your Redux opinionated branch, as I had no need for thunks in my project. I did pretty much copy all of your relevant changes to get Redux working.

However, the `serialize-javascript` package (used within `generateHTML.js`) seemed to convert my Immutable JS into regular JS objects. [Immutable.fromJS(window.__APP_STATE__)](https://facebook.github.io/immutable-js/docs/#/fromJS) was unable to convert back certain data-structures, such as the Ordered Set.

To try to solve this, I discovered a module [transit-immutable-js](https://github.com/glenjamin/transit-immutable-js) which I use on the `initialState` key within the object that is passed into `generateHTML` in the server's reactApplicationMiddleware function. Then, I convert the transit string back into Immutable JS objects in client\index.js as I create the Redux store.

This solution seems to work, but I am wondering if it is the ideal way of going about things?

**Comment by birkir** [comment]
Hey @Braden1996 !
Great question, I actually use the `json-stringify-safe` package when generating parsable JSON.
I also added a XSS filter for security reasons.

https://github.com/ctrlplusb/react-universally/blob/c70d95e22ac7bba2dd1b9ef745c6e1dd03a05120/shared/utils/json/stringify.js

I would use Immutable `toJS` method (same as `toString()`, right?), pass it into json-stringify-safe, then apply the xss filter.

I have tried the `serialize-javascript` before with same problems like you are reporting.

**Comment by Braden1996** [comment]
Hey @birkir, thanks for getting back to me.
When I use Immutable JS's `toJS()` method in order to obtain the JSON, I lose information regarding the data-structure's type. For example, both `Immutable.Set([...])` and `Immutable.OrderedSet([...])` are converted into identical JSON arrays. This means I would be unable to read the JSON back into the originally typed Immutable JS objects without explicit knowledge of my store's state scheme.

However, I assume it would be fine to run the JSON (obtained after calling transit-immutable-js) and then pass that into stringify?

**Comment by birkir** [comment]
Ok this is outside the scope of my knowledge.

I usually construct the store manually in my mobx projects so in redux + Immutable this may be different.

But check out `transit` and the `transit-immutable-js` driver.

https://github.com/glenjamin/transit-immutable-js
