### ISSUE TITLE
[v13] Question: How to access the bundle type in ServerHTML.js

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#382]
I want to include react and react-dom from cdn in ServerHTML.js. This should only happen in production builds. Is it possible to access the same kind of info that is available in Webpack in reactApplicationMiddleware.js?

**Comment by ctrlplusb** [comment]
Yep, you could do something like the following:

```
if (!process.env.BUILD_FLAG_IS_DEV) {
  // this code snippet will only be executed for builds that are not development. i.e production? :)
}
```

**Comment by mschipperheyn** [comment]
Awesome. thx.
