### ISSUE TITLE
[v13] Server side stack traces 

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#388]
I just spent hours trying to find why my site wouldn't load. The reason was a small typo in an import statement but that doesn't matter. 

npm run develop gave me this error message:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function 

It didn't specify in which class the error occurred.

I only found the class when I ran npm run build:dev. Should have done that sooner. But in general, it would be nice if the server console output would offer more details on what went wrong.

**Comment by birkir** [comment]
![image](https://cloud.githubusercontent.com/assets/180773/23607253/0f35d0c6-025c-11e7-8160-52a00e80c56d.png)

I get the usual check a component render method, which is the norm.

Please attach a full log.

**Comment by mschipperheyn** [comment]
Ok, so, the first output is the regular output from npm run develop and the second from an npm run build

<img width="1540" alt="screen shot 2017-03-06 at 10 38 33" src="https://cloud.githubusercontent.com/assets/384959/23612288/a03682d0-0259-11e7-8e25-114d86989bb0.png">
<img width="1005" alt="screen shot 2017-03-06 at 10 41 55" src="https://cloud.githubusercontent.com/assets/384959/23612292/a4730c42-0259-11e7-8e02-9d02ff5056b3.png">

The first offers no usable information on what the error is and where to look for it. The second is spot on.

**Comment by birkir** [comment]
I can glimpse at a stack trace in your first picture at the top. These two are different whole different messages, the top one is a compilation error where the bottom one is a warning. Are you sure that those messages are related?

Something to consider is if you use stateless components you wont get where the error originated from (like in the picture I posted).

**Comment by mschipperheyn** [comment]
Yes, they reference the same issue. The top message suggests that it is an export problem, when it is in fact an import problem. Since I made a typo in the import statement, I'm referencing a components that is in fact undefined.

But the error in itself is irrelevant. The reason it was a problem was because the source of the problem wasn't referenced.

**Comment by birkir** [comment]
Sorry this is too little information to help you at this time.

**Comment by mschipperheyn** [comment]
Ok, no worries.
