### ISSUE TITLE
Add a smart error handling component.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#392]
I built one for a client project, it's kind a meld of a few tools out there to give a nice error overlay that prints errors with stacktraces.  Super helpful when developing components as unhandled errors during the react render process are obscure at best.

**Comment by birkir** [comment]
Cool, would love to get more details. I found react-safe-render when searching for react error handling component, but I think you mean something else, something similar to react-redbox 👍

**Comment by ctrlplusb** [comment]
Yeah, sure thing, I am combining a few different libraries, creating a HOC that can be easily used -and that only activates for development mode (else it just returns the original component). So I recommend that it be used to wrap EVERY component.

It's very similar to `redbox-react` in how it displays errors, however, it's much better at interpreting available sourcemaps giving you _exact_ line numbers.

For example, I switched out my component with react redbox for the exact same code error (no other code changes).

redbox displayed the following stacktrace:
```
http://localhost:7331/client/index.js:8213:30
Array.map
(native)
Files.render
http://localhost:7331/client/index.js:8210:21
Files.render
http://localhost:7331/client/index.js:10077:29
http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407620018:92664:21
measureLifeCyclePerf
http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407620018:91943:12
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407620018:92663:25
ReactCompositeComponentWrapper._renderValidatedComponent
http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407620018:92690:32
ReactCompositeComponentWrapper._updateRenderedComponent
http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407620018:92614:36
ReactCompositeComponentWrapper._performComponentUpdate
http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407620018:92592:10
```

Whilst mine produces:
```
fileId()@webpack:///shared/components/App/lib/Files/index.js:100:47
Array.map()@(native)
map()@webpack:///shared/components/App/lib/Files/index.js:99:26
render()@webpack:///~/react-poop/dist/poop.js:34:28
{anonymous}()@http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407894121:92664:21
measureLifeCyclePerf()@http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407894121:91943:12
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext()@http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407894121:92663:25
ReactCompositeComponentWrapper._renderValidatedComponent()@http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407894121:92690:32
ReactCompositeComponentWrapper._updateRenderedComponent()@http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407894121:92614:36
ReactCompositeComponentWrapper._performComponentUpdate()@http://localhost:1337/client/__dev_vendor_dll__.js?t=1489407894121:92592:10
```

Notice the line count differences. 😀

**Comment by codepunkt** [comment]
The one that has been implemented in `create-react-app` seems really good.
See  https://github.com/facebookincubator/create-react-app/pull/1101

**Comment by ctrlplusb** [comment]
Defo worth investigating this as an option @codepunkt - would much rather use something that is managed for us.

**Comment by birkir** [comment]
I tried `react-dev-utils` out, and it really needs a lot of modification to work with our stack. They have their own webpack hot server (where we use webpack-hot-middleware), etc, etc.

**Comment by oyeanuj** [comment]
@birkir @codepunkt @ctrlplusb  It seems like we could just use the [`react-error-overlay`](https://www.npmjs.com/package/react-error-overlay) package instead of the entire `react-dev-utils`. Apart from being [used in CRA]((https://github.com/facebookincubator/create-react-app/pull/2111) ), it seems like it is being used in a [bunch of other places](https://github.com/search?l=JavaScript&q=react-error-overlay&ref=opensearch&type=Repositories). [Here](https://github.com/cantyjeffrey/react-boilerplate/search?utf8=%E2%9C%93&q=react-error-overlay&type=) and [here](https://github.com/rai-project/react-components/search?utf8=%E2%9C%93&q=react-error-overlay&type=) are a couple of integration examples.

**Comment by oyeanuj** [comment]
_(a follow up to my above comment)_

Incase CRA's react-error-overlay is what we choose, here is a PR (by @Timer on another repo) for us to base this upon (as per [Dan Abramov's tweet](https://twitter.com/dan_abramov/status/925831134696665091)): https://github.com/react-cosmos/react-cosmos/pull/484#event-1320939654. It seems like it doesn't require much webpack changes to get going.

**Comment by ctrlplusb** [comment]
Closing in favour of reacts error boundaries.
