### ISSUE TITLE
[V13] Set process.env environment variables as strings

### ISSUE THREAD

**Issue by Neophy7e** [ctrlplusb/react-universally#395]
With WebPack DefinePlugin 'magic', we are able to set `process.env` variables to any type wished.

But the default behavior of node.js is that `process.env`variables are always stored and accessed as strings.

To keep consistency with node.js behavior and to make testing easier, what do you think about storing does values as strings?

https://github.com/ctrlplusb/react-universally/blob/next/internal/webpack/configFactory.js#L266

Eg: 
```js
'process.env.BUILD_FLAG_IS_CLIENT': isClient ? JSON.stringify('true') : JSON.stringify('false'),
```

**Comment by ctrlplusb** [comment]
I think that is a completely fair thing to do. It would make movement away from the DefinePlugin a bit easier too (should this ever be needed).  It's nice to emulate the API's we are "emulating". :)

Accepted. :)

**Comment by diondirza** [comment]
@Neophy7e `'process.env.BUILD_FLAG_IS_CLIENT':  JSON.stringify(isClient)` already produce string value. You could check what type it is with this code 

``` javascript
typeof(JSON.stringify(true))
// or 
typeof(process.env.BUILD_FLAG_IS_CLIENT)
```

**Comment by Neophy7e** [comment]
@diondirza 

Yes but then WebPack transform it back to a boolean, `JSON.stringify` returns a different value if you give it a string or a boolean.

```js
console.log(JSON.stringify(true)); // "true"
console.log(JSON.stringify('true')); // ""true""
```

Unfortunately, the [documentation](https://webpack.js.org/plugins/define-plugin/) doesn't state it clearly.

@ctrlplusb If you'd like to further "emulate" the `process.env` it would maybe make sense to set it also as an object.

`process.env` is defined as an object by node.js but with WebPack define plugin `process.env` values aren't set in `process.env` object. 

**In client :** 
```js
console.log(process.env); // Object {} An empty object
console.log(Object.keys(process.env)); // Array [] An empty array

console.log(process.env.BUILD_FLAG_IS_CLIENT); // true
```

This can lead to some bugs if the user assumes 'process.env' to behave as in node.

The solution would be to define `process.env` values like this for example: 

```js
  new webpack.DefinePlugin({
    'process.env': {
      BUILD_FLAG_IS_CLIENT: isClient ? JSON.stringify('true') : JSON.stringify('false')
    }
  })
```

**Comment by diondirza** [comment]
@Neophy7e nice, just realize that. Yet since that flag only matter in our code not being used by node itself I think it doesn't matter how we declare it whether being string or boolean.

Anyway define `process.env` like your example above will overwrite process.env like if you have `.env` file to add some build configuration into `process.env`

**Comment by ctrlplusb** [comment]
> This can lead to some bugs if the user assumes 'process.env' to behave as in node.

Yeah, this will have to be a known trade-off for now. As @diondirza as pointed out, overwriting the whole `env` object makes it impossible for users to pass in environment variables from the CLI etc.

**Comment by Neophy7e** [comment]
@ctrlplusb This make sense thanks for the explanation!
