### ISSUE TITLE
mobx@next error with latest next.

### ISSUE THREAD

**Issue by saniko** [ctrlplusb/react-universally#397]
Maybe it's too early,
Marged locally latest next with feature/mobx@next:

> TypeError: Cannot read property 'createHref' of undefined
>     at Link.render (C:\***\node_modules\react-router-dom\Link.js:72:36)

Question:
Can someone please provide a short example of consuming DB data by mobx store for this project?
 
Edit:
Found this repo:
https://github.com/kennethtruong/react-webapp

Thanks.

**Comment by diondirza** [comment]
@saniko You could try to upgrade your react-router-dom to stable version.

**Comment by birkir** [comment]
Hey, I have synced this with the next branch, so you should be good to go.

You can take a look at https://github.com/ueno-llc/starter-kit-universally if you want to see complete example of mobx store with server side rendering.

**Comment by saniko** [comment]
Thanks!
