### ISSUE TITLE
Can not access dev server from other machines

### ISSUE THREAD

**Issue by birkir** [ctrlplusb/react-universally#398]
We have a problem where our devs can't test devices that are on the same wlan in develop mode.

Simplified example:
 - computer ip is `192.168.1.1` and my phone is `192.168.1.2`.
 - starting develop binds `0.0.0.0:1337` to express and `0.0.0.0:7331` to the webpack dev server.
 - address to the webpack bundle will be set to `http://0.0.0.0:7331/client/index.js` because we're using the **HOST** EnvVar.
 - accessing `http://192.168.1.1/` from my phone will work, but it will try to connect to webpack dev server via `0.0.0.0` won't, so no assets get delivered.
 - by setting `HOST=192.168.1.1` won't work as it will not bind to all interfaces (localhost won't work).

---

I solved it (temporarily?) by adding a new environment variable that sets the development server host independently from the express bind address. But we can also just always bind to all ifaces (express and dev server) and use HOST as the publicPath.

Opinions?

**Comment by birkir** [comment]
My proposal is to basically just remove `config('host')` from this line:
https://github.com/ctrlplusb/react-universally/blob/next/server/index.js#L52

**Comment by strues** [comment]
I believe the reasoning for the host configuration was to help with Heroku or Now? I could be mistaken. Could implement https://github.com/bubenshchykov/ngrok as an alternative if necessary.

**Comment by birkir** [comment]
We use ngrok a lot, but it required this change. Two ngrok proxies are needed for different ip's, then we need to set HOST to ngrok0 host and CLIENT_DEV_HOST to ngrok1 host and CLIENT_DEV_PORT to 80 for it to work.

**Comment by ctrlplusb** [comment]
I honestly can't remember the original intention of adding the host.  `now` doesn't require it, I can confirm.  Anyone using `heroku`?

**Comment by birkir** [comment]
Not for heroku, not for google cloud engine (use both).

**Comment by ctrlplusb** [comment]
@birkir whats the consensus on this? Have you been using without the `config('host')` for a while now?  You reckon it's safe to go ahead with this change?

**Comment by birkir** [comment]
I've been using this without `config('host')` for a month without any issues. It's safe.

**Comment by ctrlplusb** [comment]
Sweet, do you mind updating `next`? :)

**Comment by birkir** [comment]
wow, @ctrlplusb is on fire, great work man!
