### ISSUE TITLE
Devserver & CSS Modules

### ISSUE THREAD

**Issue by KeKs0r** [ctrlplusb/react-universally#40]
I am trying to figure out how to use react-toolbox with this, but running into this issue: https://github.com/react-toolbox/react-toolbox/issues/662

The interesting part is that building my app either in production/dev or client and server, everything works fine.

Just when using the devserver.js I am running into this issue. So it might be related to the way the devserver works, but I am not sure what the issue is.

Did anyone use CSS Modules with this boilerplate and the devserver?

**Comment by ctrlplusb** [comment]
Do u have a sass loader ?

**Comment by KeKs0r** [comment]
Yes in here:
```
{ test: /\.scss$/,
          include: /(react-toolbox)/,
          loaders: 
           [ 'style',
             'css?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
             'postcss',
             'sass?sourceMap',
             'toolbox' ] },
```

And as I said, when just compiling (without dev server), my config works fine.

**Comment by ctrlplusb** [comment]
Hmmm, Oki I will try it my side and see.

**Comment by KeKs0r** [comment]
Let me know if you need additional infos. I still keep investigating.

**Comment by KeKs0r** [comment]
Okay solved it. It was due to the nodeExternals modules, since react-toolbox wasn processed by webpack.

**Comment by ctrlplusb** [comment]
That's a massive gotcha for this configuration.  I need to add this to the FAQs.

**Comment by ctrlplusb** [comment]
@KeKs0r the latest push makes this problem go away for any future library installs. :)
