### ISSUE TITLE
[v13] Loading React from CDN: Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#400]
Hi,

I use SSR and am trying to optimize the size of my `client/index.js` by externalizing 'react' and 'react-dom'. However, the client side code doesn't seem to be able to access the loaded React code. Any suggestions on how to deal with this?

    Uncaught TypeError: Cannot read property 'Component' of undefined
        at Object.<anonymous> (Router.js:90)
        at t (bootstrap b07edf5…:47)
        at Object.<anonymous> (MemoryRouter.js:1)
        at t (bootstrap b07edf5…:47)
        at Object.<anonymous> (index-f4a8de3….js:8084)
        at t (bootstrap b07edf5…:47)
        at Object.<anonymous> (BrowserRouter.js:13)
        at t (bootstrap b07edf5…:47)
        at Object.<anonymous> (index-f4a8de3….js:12072)
        at t (bootstrap b07edf5…:47)

 configFactory.js

    externals: removeNil([
      ifNode(
        () => nodeExternals(
          // Some of our node_modules may contain files that depend on our
          // webpack loaders, e.g. CSS or SASS.
          // For these cases please make sure that the file extensions are
          // registered within the following configuration setting.
          {
            whitelist:
              removeNil([
                // We always want the source-map-support included in
                // our node target bundles.
                'source-map-support/register',
                // We want react bundled with our node bundles for the optimised
                // builds as we are going to resolve to the optmised versions
                // of react via the webpack alias configuration.
                ifOptimize('react'),
                ifOptimize('react-dom'),
                ifOptimize('react-dom/server'),
              ])
              // And any items that have been whitelisted in the config need
              // to be included in the bundling process too.
              .concat(config('nodeExternalsFileTypeWhitelist') || []),
          },
        ),
      ),
      // We want to exclude react libraries from the client production version
      ifOptimizeClient(() => {
          return {
            react: {
                root: 'React',
                commonjs2: 'react',
                commonjs: 'react',
                amd: 'react',
                umd: 'react',
            },
            'react-dom': {
                root: 'ReactDOM',
                commonjs2: 'react-dom',
                commonjs: 'react-dom',
                amd: 'react-dom',
                umd: 'react-dom',
            },
            'react-addons-transition-group': {
                root: ['React','addons','TransitionGroup'],
                commonjs: 'react-addons-transition-group',
                commonjs2: 'react-addons-transition-group',
                amd: 'react-addons-transition-group',
            },
          }
      }),
    ]),

config/values.js

    const values = {
      [...]
      cspExtensions: {
        childSrc: [],
        connectSrc: [],
        defaultSrc: [],
        fontSrc: [],
        imgSrc: [],
        mediaSrc: [],
        manifestSrc: [],
        objectSrc: [],
        scriptSrc: [
            // Allow scripts from https://cdn.polyfill.io so that we can import the
            // polyfill.
            'https://cdn.polyfill.io',
            'https://cdnjs.cloudflare.com',
        ],
        styleSrc: [],
      },

server/middleware/reactApplication/ServerHTML.js

    [..]

    const bodyElements = removeNil([
        // Binds the client configuration object to the window object so
        // that we can safely expose some configuration values to the
        // client bundle that gets executed in the browser.
        <ClientConfig nonce={nonce} />,
        onlyIf(process.env.NODE_ENV === 'production', () => scriptTag('//cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-with-addons.min.js')),
        onlyIf(process.env.NODE_ENV === 'production', () => scriptTag('//cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.min.js')),

    [...]

**Comment by birkir** [comment]
Maybe add a defer attribute to your client bundle script tag.

But it could also be that react-router imports Component via `import Component from 'react/lib/Component'` or something.

**Comment by mschipperheyn** [comment]
Thanks for the reply. 

Using `defer` for the client script didn't help. 

There also doesn't seem to be an import statement like that in the code. The weird thing is, if I "Pause on Exception", React.Component seems to be available.

**Comment by mschipperheyn** [comment]
The problem *seems* to be resolved by using 

`libraryTarget: ifNode('commonjs2', 'umd'),` in stead of `libraryTarget: ifNode('commonjs2', 'var'),`

**Comment by birkir** [comment]
Good to know 👍
