### ISSUE TITLE
[v13] recommend using transform-react-remove-prop-types (and transform-react-pure-class-to-function) (babel) 

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#402]
the plugins used to optimize react production code don't do a number of possible optimizations, such as removing PropTypes. 

- babel-plugin-transform-react-remove-prop-types
- babel-plugin-transform-react-pure-class-to-function

There is also a preset that combines these actions: https://github.com/thejameskyle/babel-react-optimize

Currently I have added `ifOptimize('transform-react-remove-prop-types'),` myself, which, curiously, does not seem to result in proptypes being removed from the resulting optimized bundle.

**Comment by ctrlplusb** [comment]
Hey @mschipperheyn 

Thanks for this!

Yeah, I have come across Jame's library before.  I remember at the time there were some strange issues that were coming out as side effects.  James has decided to disable issues on his repo's at the moment so I can't bring them up right now.  I think as a good litmus we should see if `create-react-app` adopts any of them.  They have a much larger community and value stability, so anything that makes its way in there should be good for us too.  :)

**Comment by ctrlplusb** [comment]
I am going to close this for now.  If any of them come up solid from `create-react-app` let's reconsider adding them. :)
