### ISSUE TITLE
Usage With child_process.fork(...)

### ISSUE THREAD

**Issue by Braden1996** [ctrlplusb/react-universally#403]
Hey, over the past few months I've been working on a project which uses this starter kit. Thus far, it's been very pleasant to work with.

However, I need to perform some fairly CPU heavy tasks and have chosen to use Node's child_process API. Now, my issue is that when I call `child_process.fork()` I am just given a bunch of syntax errors because that file is never transpiled. Any ideas on how to best work around this?

**EDIT**
If it is of any help, the project I am working on is a multiplayer game. The child process is to compute the best move for an AI player, by running many simulations - so expensive. However, as my game is in ES6 I am unable to import it into my child process.

**Comment by Braden1996** [comment]
Just a little update:
I've managed to achieve this by extending the `additionalNodeBundles` to contain a `isNodeSever` property. I have modified `HotDevelopment` to prevent bundles - who have this new property `false` - from having their own node process spun off.

This commit shows what I have done: https://github.com/Braden1996/tron.io/commit/77c09e2059d2abaf031bccff268ee7586bf86c43

Does this seem like an appropriate solution? Also, I would like to associate the webpack's compiledEntryFile path to the child process bundles - to make it easier to reference elsewhere. However, I am not sure how to tackle this. I experimented by getting the file path from the compiler and storing this in the config values object, but couldn't get it to work, then gave up because it seemed 'hacky'.

Any advise would be greatly appreciated!

**Comment by ctrlplusb** [comment]
Very interesting @Braden1996 

I only had a quick parse but it looks like you have gone down an effective route.  It's a very specific feature you are implementing.  

I am gonna leave this issue up as a helpful go-to for anyone else who may be trying something similar.

**Comment by ctrlplusb** [comment]
Sorry, closing for now as trying to clean up the issues and make the project feel a bit more alive again. :)
