### ISSUE TITLE
readme / getting started

### ISSUE THREAD

**Issue by stephanMettler** [ctrlplusb/react-universally#410]
Hi,

the Readme says:
```
git clone https://github.com/ctrlplusb/react-universally my-project
cd my-project
yarn
yarn run development
```

which gives me:
```
yarn run v0.21.3
error Command "development" not found.
```

...made it run with:
```
git clone https://github.com/ctrlplusb/react-universally my-project
cd my-project
yarn build
yarn start
```
cheers

**Comment by kennethtruong** [comment]
If you look at the package.json `yarn development` has been changed to `yarn develop`.

**Comment by ctrlplusb** [comment]
Hey @stephanMettler 

Thanks for raising this.  I have corrected the readme to use the correct value of `develop` as highlighted by @kennethtruong 

👍
