### ISSUE TITLE
Latest commits break heroku

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#416]
I have just upgraded my v13 installation to include the latest commits, and I found that deploying on Heroku no longer works.

Currently, start is configured as follows `"start": "NODE_ENV=production node build/server",`

But on Heroku the build packages can no longer be found

    Error: Cannot find module '/app/build/server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

The solution is to add a postinstall step to package.json

`"postinstall": "npm run build",` 

I recommend that this is added

**Comment by birkir** [comment]
The problem is that every time you install a module via npm or yarn, you build the app.

I have a hacky way of doing this, I know a better solutions but I don't care at the moment 😸 
```js
"postinstall": "if [ \"x$NODE_ENV\" != \"x\" ] && [ \"$NODE_ENV\" != \"development\" ]; then (npm run heroku-yarn && npm run build); fi;",
```

**Comment by heyfrench** [comment]
In case anybody else comes across this, Heroku has custom hooks for these things that will include the results in the built image your dyno instances are started with:
```js
"scripts": {
  "heroku-prebuild": "echo This runs before Heroku installs your dependencies.",
  "heroku-postbuild": "echo This runs afterwards."
}
```
So, add your `npm run build` to `heroku-postbuild` and your compiled assets will get baked in. After that, `npm start` should work assuming nothing in the build process is silly enough to use absolute paths in the output (lookin' at you react-server).

**Comment by oyeanuj** [comment]
@mschipperheyn @heyfrench @birkir  Just to confirm, to deploy to Heroku - did you have to do anything else other than add those scripts in the comment above?

**Comment by heyfrench** [comment]
@oyeanuj not that I can remember. Is it not working for you?

**Comment by oyeanuj** [comment]
@heyfrench I am getting the errors below in the logs, and then 'Application Error' when I try to actually access the site.

```sh
 ERROR in ./node_modules/normalize.css/normalize.css
       Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open '/tmp/build_10ea8f7ac61712cf97701a5c7370f549/oyeanuj-react-universally-164c8bb/node_modules/svgo/lib/svgo/../../.svgo.yml'
       at Object.fs.openSync (fs.js:653:18)
       at Object.fs.readFileSync (fs.js:554:33)
```

Any ideas?

Also, couple of quick questions - 

1. What is your `start` script set to? Using the current start script makes Heroku run it on the port and given `HOST` as the environment variable, rather than the Heroku url.

2. It seems like the page is being refreshed on each link click. Is that something that you also saw?

**Comment by oyeanuj** [comment]
@heyfrench Actually, I figured out my error. I had tied myself in a knot with the `prebuild` and `postbuild` commands and messing with `yarn clean`. Ultimately, all I had to do was add the following to the `scripts` section in `package.json`:
```json
"heroku-postbuild": "npm run build"
```

Thanks for your help, and sorry for the noise!
