### ISSUE TITLE
favicons not included in bundle using Windows build 

### ISSUE THREAD

**Issue by renatonmendes** [ctrlplusb/react-universally#420]
I'm using Windows 10.

I just downloaded the project and need to use it on a windows computer. After installing cross-env to solve the Windows environment variable (from this issue](https://github.com/ctrlplusb/react-universally/issues/412), I could call:

`npm run develop` or `npm run start`

Unfortulnatelly the icons are not being shown. Looking at the `bundle\client` folder  I can't see the icons being built from webpack. 

I need help to build the bundle in my Windows 10 environment and make it run. Thanks for the support.

SOLVED:

In fact nothing to do with the bundle. I have to change the following parameter:

`  // The host on which the server should run.

  host: EnvVars.string('HOST', '0.0.0.0'),`

to

`  // The host on which the server should run.

  host: EnvVars.string('HOST', 'localhost'),`

**Comment by birkir** [comment]
Or just set HOST=127.0.0.1 to your dotenv file.

**Comment by brietsparks** [comment]
Got this problem too, along with the counter increment demo app being broken, showing `Failed to load resource: net::ERR_ADDRESS_INVALID` in the console. The EnvVars fix solved it.
