### ISSUE TITLE
Not updading browser when code changes using react-hot-loader@next (3.0)

### ISSUE THREAD

**Issue by renatonmendes** [ctrlplusb/react-universally#421]
I've installed a fresh new `react-hot-loader` in the bundle, version 3.0. 

When I update some file (ex: change text in the `AsyncHomeRoute.js` file), `react-hot-loader` is upding the browser, but the changes are not being shown in screen directly - I need to reload the page so that I can see the changes.

In the console, all seens to work fine:
```
`Client has support for "picture".
client.js?d8a7:67 [HMR] connected
client.js?d8a7:199 [HMR] bundle rebuilding
client.js?d8a7:207 [HMR] bundle rebuilt in 696ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:100 [HMR] Updated modules:
process-update.js:102 [HMR]  - ./src/shared/components/DemoApp/AsyncHomeRoute/HomeRoute.js
process-update.js:102 [HMR]  - ./src/shared/components/DemoApp/AsyncHomeRoute/index.js
process-update.js:102 [HMR]  - ./src/shared/components/DemoApp/index.js
process-update.js:107 [HMR] App is up to date.
client.js?d8a7:199 [HMR] bundle rebuilding
client.js?d8a7:207 [HMR] bundle rebuilt in 499ms`

```
Also, from the network tab I can see the changed bundled being downloaded with the correct changes:

Network Log:
```

    7m8l7TlFO-S3VkhHuR0at44P5ICox8Kq3LLUNMylGO4.woff2
    baf98b7a-7c2f-4368-bdb5-e2c28ff9d89d
    a6225531-895e-4e59-942f-8499eb24369d
    0-d14a03b6e2a1447a7c0d.js
    __webpack_hmr
    72d2517bed43ee951701.hot-update.json
    0.72d2517bed43ee951701.hot-update.js <<--- IT CONTAINS MY CHANGES IN THE CODE

    17 requests ❘ 1.0 MB transferred ❘ Finish: 5.4 min ❘ DOMContentLoaded: 690 ms ❘ Load: 721 ms


Preserve log

client.js?d8a7:207 [HMR] bundle rebuilt in 499ms

```

According to the [,react-hot-loader 3.0 migration guide](https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30) I've changed the following with no success:

```
// The following is needed so that we can support hot reloading our application.
if (process.env.BUILD_FLAG_IS_DEV === 'true' && module.hot) {
  // Accept changes to this file for hot reloading.
  module.hot.accept('./index.js');
  // Any changes to our App will cause a hotload re-render.
  module.hot.accept('../shared/components/DemoApp', () => {
    renderApp(DemoApp);
  });
}

```
No success at all. I still cannot see the chages on screen without a refresh. 
I appreacite some help to solve that.

**Comment by diondirza** [comment]
the code in `client/index.js` should be like this:
```
if (process.env.BUILD_FLAG_IS_DEV === 'true' && module.hot) {
  // Accept changes to this file for hot reloading.
  module.hot.accept('./index.js');
  // Any changes to our App will cause a hotload re-render.
  module.hot.accept('../shared/components/DemoApp', () => {
    renderApp(require('../shared/components/DemoApp').default);
  });
}
```

I have tested this issue with master branch and cannot reproduce it, could you make a branch so I could take a look on it?

**Comment by renatonmendes** [comment]
@diondirza Sorry, but I can't create a new branch as GitHub does not show me that option... Maybe I'm not a contributor for this page.

**Comment by diondirza** [comment]
@renatonmendes you could fork this repo then create your own branch in your own repo, then you can link them here.

**Comment by renatonmendes** [comment]
Did it. Check if enough. [https://github.com/renatonmendes/react-universally](Link here.)

**Comment by renatonmendes** [comment]
Sorry. I closed the issue accidentally. Now reopened as this is not yet solved.

**Comment by diondirza** [comment]
@renatonmendes I don't see behaviour like you describe above, it works as expected update DOM without page refresh.

**Comment by renatonmendes** [comment]
Not for me. Are you using the same environment: Windows 10, Chrome  57.0.2987.133.
Changing the `HomeRoute.js` file inside the `<p></p>` element.

**Comment by strues** [comment]
@renatonmendes Try adding https://github.com/Yaffle/EventSource as a polyfill. I'm pretty sure this only affects IE/Edge, but give it a shot.

**Comment by renatonmendes** [comment]
@strues no advance using EventSource. Still not working.

**Comment by diondirza** [comment]
@renatonmendes just tried this on Windows 10 Chrome 58.0.3029.81 and works perfectly fine

**Comment by aga5tya** [comment]
@diondirza This is the scenario when it can be replicated. I'm on osx latest.

1) Run the development server, make changes hot reload works initially.
2) Now when i Ctrl-C to kill the process, the node process stays in the background(Browser refresh still serves the app 😕 ), further calls to spin off dev server creates a new node process.
3) When this scenario is met, hot reloading doesn't work until i kill all node processes.

Also sometimes step 2 doesn't happen, but when hot reload stops working on launch, the node processes are piled up in the background.

I'm thinking something to do with way server is exited on kill signal
https://github.com/ctrlplusb/react-universally/blob/next/internal/development/index.js#L42

**Comment by birkir** [comment]
It does not for me, which node version do you have? There was a problem with old node and the spawned child processes not quitting properly.

**Comment by aga5tya** [comment]
@birkir Node v8.1.2 and npm 5.0.3

**Comment by mherodev** [comment]
I am also not seeing HMR work correctly.

Node v6.10.1
1. `yarn`
1. `yarn develop`
1. Open `http://0.0.0.0:1337/counter`
1. Make a change to `CounterRoute.js`
1. See `[HMR] App is up to date.` in the console.
1. Do NOT see changes visible in the browser.

:(

Note: Seeing an error in console as well, although I expect it's unrelated.

```
index.js:26 Uncaught (in promise) TypeError: iterable[Symbol.iterator] is not a function
    at index.js:26
    ...
```

**Comment by dariobanfi** [comment]
Same here, using react-universally latest version with node `8.2.1` and npm `5.3.0`.
Bundle is rebuilt, but I need to manually refresh the page to see the changes.

**Comment by dariobanfi** [comment]
Seems to be a problem with csp: XMLHttpRequest cannot load http://0.0.0.0:4000/client/a6327a7aabc6c2e2aaa5.hot-update.json. The 'Access-Control-Allow-Origin' header has a value 'http://0.0.0.0:3000' that is not equal to the supplied origin. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by diondirza** [comment]
@dariobanfi that error tells you that you open the app in browser with url http://0.0.0.0:4000, and CSP only allow hot reload from http://localhost:3000. You should open the app from localhost:3000, and don't forget to add `.env` file in your project which you can clone its content from `.env_example`

**Comment by dariobanfi** [comment]
That's not the problem I think. I have this issue also on vanilla latest react-universally:
- open the app at localhost:1337
- change code
- hot-update.json served from localhost:7331 is blocked due to CORS
