### ISSUE TITLE
Error polyfill.io with es6 features

### ISSUE THREAD

**Issue by diondirza** [ctrlplusb/react-universally#423]
@ctrlplusb seems polyfill.io with `es6` parameter broke all routes in mobile device.
Here is the screen shot:
<img width="1440" alt="screen shot 2017-04-18 at 10 58 21 am" src="https://cloud.githubusercontent.com/assets/10954870/25114098/4048ceca-2426-11e7-9a2b-f21d881d06e1.png">
 I tried to add `Symbol` and `Symbol.iterator` in parameter yet still cannot solve the error unless I remove `es6` from features parameter and leave only `default`.

**Comment by birkir** [comment]
Do you by any chance have a custom user agent string in your devtools? can you reproduce this on a actual device?

**Comment by diondirza** [comment]
@birkir no custom user agent, I tick select automatically option for that, and I have had this error in the past before and solved it without parameter. I tried this new approach, I thought this would work smoothly without test in actual device instead the error already happened when inspecting with mobile simulator in devtools. It does happen in your local, doesn't it?

**Comment by diondirza** [comment]
#422 will solve this issue.

**Comment by ctrlplusb** [comment]
Done 🎉

**Comment by ctrlplusb** [comment]
Argh, I may have jumped the gun here.  @birkir we had to add the `es6` setting to polyfill IO for older browsers right?  

@diondirza this change may actually cause this issue to reoccur.  I've only just noticed that you commented out the `es6` setting completely.

Any advice/insight @birkir?

**Comment by birkir** [comment]
Ok, so now we're back to https://github.com/ctrlplusb/react-universally/issues/374 right?

**Comment by ctrlplusb** [comment]
Yes, I may reverse the removal of the `es6` feature flag though, as it had a wider effect not having it.  @diondirza can you please give us more insight into the nature of the problems experienced on mobile.  What mobile device and OS was it?

**Comment by birkir** [comment]
I'm not really sure about skipping es6, because if you check out the feature list there is a huuuge difference (and both have `Symbol.iterator`):

https://cdn.polyfill.io/v2/polyfill.js?features=default&flags=always
https://cdn.polyfill.io/v2/polyfill.js?features=default,es6&flags=always

**Comment by diondirza** [comment]
So this error occured in chrome dev tools, when I activated toggle device toolbar. While I was investigating some weird style for my production app I noticed this error, I know this is because es6 param that I just added. That errors makes my app malfunction everytime I open devtools with mobile device simulation. I thought at the first time this was only happened on my app, yet even barebone template like react-universally also experienced it. 
@ctrlplusb @birkir Does this happen on your local? or it is just me?

**Comment by diondirza** [comment]
@birkir it might be duplicate Symbol.Iterator from default and es6 parameter, makes this error occured. Yet I tried to use es6 feature alone, yet the error still occured.

**Comment by birkir** [comment]
What mobile device do you have?

**Comment by birkir** [comment]
Ok, I looked at your picture again and it seems that you're talking about emulated devices (which does not have a different javascript engine than your browser).

**Comment by ctrlplusb** [comment]
@birkir  i am away from computer at the moment. Do you mind rolling back that change.

@diondirza we can try and investigate emulated device seperately. But the change breaks older browsers, so it's best to roll it back for now.

**Comment by diondirza** [comment]
@ctrlplusb no problem. I'll do further investigation for this.

**Comment by alexanderfrey** [comment]
@diondirza Same problem here. In simulator mode on chrome the app does not load.

**Comment by diondirza** [comment]
@alexanderfrey try change polyfill.io script url by adding this parameter `flags=gated,always` at the end

`https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6&flags=gated,always`
