### ISSUE TITLE
Receive default props from server

### ISSUE THREAD

**Issue by rohmanhm** [ctrlplusb/react-universally#424]
`getInitialProps` in `next.js` very helpful to get default props from server. How can I get default props from server such as `query`, `req`, `res` and etc with `react-universally`?

**Comment by ctrlplusb** [comment]
A biased recommendation: `react-jobs`. I built it to have compatibility with `react-async-component`. 😀

**Comment by ctrlplusb** [comment]
Feeding request data in my recommendation should be done via react router route definitions

**Comment by rohmanhm** [comment]
I had a look `feature/react-jobs` branch, I thought that `react-jobs` have different functionality compared what `next.js` does with [`getInitialProps`](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle).

Could you update the example? It's more helps

**Comment by ctrlplusb** [comment]
I may introduce a feature branch with this in the feature.
