### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by renatonmendes** [ctrlplusb/react-universally#425]
Is there a central location to change the whole application font to a different google font ? 

I cannot find it on `config/values.js`

If not, what is the best component to setup the font for the whole application ?

**Comment by ctrlplusb** [comment]
Check out the `App/index.js`.  I bind google roboto font and add a css framework there, which are commented.  I recommend you remove these and use your own.

**Comment by renatonmendes** [comment]
For some reason the font I've choose for testing (Tangerine) is being overwritten by `_reboot.scs`s and `_type.scss`. See below:

![image](https://cloud.githubusercontent.com/assets/10373990/25192745/d408135c-250a-11e7-9bfd-d5a7fa2a8d9a.png)

My config at DemoApp/index:

```
        {/*
          NOTE: This is simply for quick and easy styling on the demo. Remove
          this and the related items from the Content Security Policy in the
          global config if you have no intention of using milligram.
        */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine"
        />
        <link
          rel="stylesheet"
          href="/scripts/css/bootstrap.css"
        />

```
globals.css

```
html {
  box-sizing: border-box;
  font-family: 'Tangerine', serif;
}

*,
*:before,
*:after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

/* Inline our ul for our menu */
ul {
  margin: 0;
  padding: 0;
  list-style-type: none;
}

ul li { display: inline; margin: 0 .5rem; }

```

Help appreciated.

**Comment by strues** [comment]
Hey @renatonmendes try adding this

```css
:global {
   html {
    font-family: 'Tangerine', serif;
   }
}
```
You might have css modules enabled in some form or another. I cant say for sure without seeing the webpack config

**Comment by diondirza** [comment]
@renatonmendes you should reorder your custom global style at the latest position. You could follow my example of `app.scss` file below

``` scss
import 'variables'; // add variables value from _variables.scss
import 'mixins'; // add helpers from _mixins.scss
import '[theme]'; // add theme style from your css framework e.g bootstrap theme
import 'global'; // add global style here from _global.scss 
```

**Comment by ctrlplusb** [comment]
@renatonmendes I hope you managed to solve this.

I am going to close this for now as it is not directly related to the project.  Feel free to keep on commenting here though if you like. :)

**Comment by birkir** [comment]
Also remember to update your content security protocol (CSP) list in config/values.js, otherwise it will get blocked.
