### ISSUE TITLE
Webpack Develop - Build times slow

### ISSUE THREAD

**Issue by maximblack** [ctrlplusb/react-universally#426]
On each file change, webpack is building the whole project again. With **happy-pack** and **dll** is much faster, but the server is restarting on **shared** files changes, too. My question is, can webpack delimit client and server files, and restart server only if "server specific" modules was changed?

**Comment by smirea** [comment]
hey @maximblack , we touched on this quite a bit in: https://github.com/ctrlplusb/react-universally/issues/330

**Comment by ctrlplusb** [comment]
Closing this in favour of #330 as highlighted by @smirea 

I have renamed the issue too.  This will be a big focus for the next big release IMO.  I'd like to rework the dev tooling as they haven't received any attention in ages.
