### ISSUE TITLE
Separate configuration for asset hostname in dev

### ISSUE THREAD

**Issue by kdavh** [ctrlplusb/react-universally#430]
In a situation where I need to make my dev server available on a service like ngrok.io, or just anything outside of my local computer, I'm having trouble finding the correct configs.  Is there something I'm missing, or is there a change / PR needed to add that ability?

**Comment by birkir** [comment]
I have this in my own fork of react-universally.

I also wanted the react-hot-loader to run within a single port, so it's a little more complex, but have you tried to just do something like `HOST=0.1.2.3 yarn run develop`

**Comment by kdavh** [comment]
Hi @birkir thanks for having a look at this.  I'll have a look at your fork.

If I just change the HOST, I get this error:
```
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v7.3.0
npm info lifecycle react-universally@13.0.0~predevelop: react-universally@13.0.0
npm info lifecycle react-universally@13.0.0~develop: react-universally@13.0.0

> react-universally@13.0.0 develop /project
> DEPLOYMENT=development babel-node internal/development

==> Registering environment variables from: /project/.env
==> VENDORDLL -> No changes to existing "client" vendor dependencies. Using the existing vendor dll.
==> Creating a development bundle configuration for the "client"
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL {my.ip.address.here}:7331
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Function.Module.runMain (module.js:607:11)
    at Object.<anonymous> (/project/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

I think because it's trying to start both the local server and the dev server on port on the public ip address I provide, not 0.0.0.0, which doesn't make sense for starting a local server.

**Comment by kdavh** [comment]
Okay, I've figured it out.  It looks like I just needed to remove the `host` parameter here, so that the dev server would always start up on 0.0.0.0:
```
diff --git a/internal/development/hotClientServer.js b/internal/development/hotClientServer.js
index b7395a7..9c806a1 100644
--- a/internal/development/hotClientServer.js
+++ b/internal/development/hotClientServer.js
@@ -34,7 +34,7 @@ class HotClientServer {
     app.use(this.webpackDevMiddleware);
     app.use(createWebpackHotMiddleware(compiler));

-    const listener = app.listen(port, host);
+    const listener = app.listen(port);

     this.listenerManager = new ListenerManager(listener, 'client');
```

That is similar to this change that was recently merged to master: https://github.com/ctrlplusb/react-universally/commit/7c5338b6e4d213ec828979534af25dcbd40acc61

**Comment by kdavh** [comment]
I'm going to close this issue, but before I do, would anyone be interested seeing this change on `next`?

**Comment by ctrlplusb** [comment]
Thanks @kdavh, I think I want to keep this out of the main branch for now as I don't feel like its a common enough requirement for us to maintain. The repo is meant to be a base for deep customisation towards needs such as yours. 👍
