### ISSUE TITLE
css-loader error?

### ISSUE THREAD

**Issue by saniko** [ctrlplusb/react-universally#435]
Hi Guys,
When I'm running the yarn build command I get this error:
`
    ERROR in ./~/css-loader!./shared/components/DemoApp/globals.css
    Module build failed: Error: ENOENT: no such file or directory, open 'C:\**\**\**\**r\node_modules\svgo\.svgo.yml'

`
I'm not sure it's a css-loader error, my project does not depend on SVGO, but it appears in node-modules folder.
All works fine in develop mode.

Any ideas?
I'm running on windows 10 with the latest code.

Thanks.

**Comment by birkir** [comment]
If you run the command `yarn why csso` we get the result `css-loader#cssnano#postcss-svgo`.

So css-loader is in fact depending on svgo.

This seems to fix the problem: https://github.com/svg/svgo/issues/622

**Comment by strues** [comment]
@saniko like @birkir said, the problem you're encountering is due to `yarn clean` https://github.com/yarnpkg/yarn/issues/1051 

Delete your node_modules. Manually create a .yarncean file and create a filter !.svgo.yml

**Comment by saniko** [comment]
Thanks.
