### ISSUE TITLE
Implement A/B test

### ISSUE THREAD

**Issue by diondirza** [ctrlplusb/react-universally#439]
@ctrlplusb @birkir @strues This is not an issue, I just want to ask if you ever have implemented A/B test with isomorphic react app before? Any suggestion which library and how to persist the result in server and client?

**Comment by sergiokopplin** [comment]
+ 1

**Comment by birkir** [comment]
Hi, we're not a lot into testing, but it's pretty related to showing random things.

If you try to show a random thing on the server and the client, you'll get two different results, so here are some options to choose from:

a) pick the random item on the server and pass it to the client.
b) pick a random number on the server and select item based on that number on both the client and server.
c) have an api endpoint give the same random item for both client and server for a limited amount of time or by a token that can be reused (User agent, ip, etc.)

This usually only applies to data, so we keep the same view components and only alter the data. If we want to alter the views based on the data, I think we have to have the client include all possible view scenarios, or use a redirect based approach.

**Comment by diondirza** [comment]
@birkir thanks for the insight bro. Meanwhile I found this [react-ab-test](https://github.com/pushtell/react-ab-test) it's really useful for implementing A/B test. Yet its support for SSR is still buggy. Maybe I'll make my own component for doing this based on your explanation. Anyway thanks alot.

**Comment by oyeanuj** [comment]
@diondirza Curious where you ended up here? Did you end up creating your own component?
