### ISSUE TITLE
Any interest in a material-ui implementation example?

### ISSUE THREAD

**Issue by brianfeister** [ctrlplusb/react-universally#440]
Not sure if this is of any interest to you guys, but I grabbed the fork from https://github.com/ctrlplusb/react-universally/pull/366#issuecomment-298662808 and added `material-ui` which was a bit difficult for me, being my second day on the job as a React developer. No idea if this aligns with your goals in maintaining branches with other ingredients in the recipe.

Went down a rabbit hole with the `material-ui` folks due to the complexity in the redux-opinionated fork:
https://github.com/nathanmarks/jss-theme-reactor/issues/41#issuecomment-298260293

https://github.com/brianfeister/react-universally/commit/2e80248a2c46b68fe38fa7c022dad33fd07a84de

/cc @ctrlplusb @sergiokopplin

**Comment by birkir** [comment]
Hey Brian, we're trying to keep the project as lean as possible, so I think we have to pass on that, and other UI libraries. This project is not meant to solve UI.

I get that you're new to react, keep up the good work and you'll get there.

**Comment by brianfeister** [comment]
Cool, no worries
