### ISSUE TITLE
Trouble setting up Babel preset used by Create React App

### ISSUE THREAD

**Issue by ChrisWiles** [ctrlplusb/react-universally#446]
https://www.npmjs.com/package/babel-preset-react-app

Steps
install babel-preset-react-app
add 'react-app' to presets in internal\webpack\configFactory
add 'react-app' to presets in .babelrc

I can't seem to get this working, getting syntax errors saying I am missing the proper transform.

**Comment by ctrlplusb** [comment]
Yeah, I am not sure this will ever work. If you do ever get it working please let us know 👍
