### ISSUE TITLE
Debugging VSCode error

### ISSUE THREAD

**Issue by saniko** [ctrlplusb/react-universally#449]
Hi,
I'm getting the **Error: listen EADDRINUSE :::1337**
when running the build in VSCode node debugger.

I have followed @lucianlature instructions here [347](https://github.com/ctrlplusb/react-universally/issues/347)
`{
     "type": "node",
     "request": "launch",
     "name": "Launch ReactUniversally",
     "program": "${workspaceRoot}/build/server/index.js",
     "cwd": "${workspaceRoot}"
}`

What am I doing wrong?

Thanks.

**Comment by elektronik2k5** [comment]
@saniko `EADDRINUSE` is node's way of telling you the port you are trying to bind to (listen to) is already in use. Make sure to kill any conflicting processes listening on the same port.

**Comment by saniko** [comment]
Had to add this to debug configuration:
`  "configurations": [

            {     "type": "node",
                "request": "launch",
                "name": "Launch siteBuilder",
                "program": "${workspaceRoot}/build/server/index.js",
                "protocol": "inspector",
                "cwd": "${workspaceRoot}"
            },
             {
            "name": "Attach",
            "type": "node",
            // Port to attach to.
            "port": 5858
        }`

**Comment by ctrlplusb** [comment]
Thanks for reporting back with the fix @saniko ❤️
