### ISSUE TITLE
NPM script to generate components

### ISSUE THREAD

**Issue by diegohaz** [ctrlplusb/react-universally#455]
Hey, guys.

I'm working on a project that helps developers to generate new components on any project no matter file structure they have.

That being said, I want to know if is it desirable here to have a `npm run component` script  (or something like that) that does the job so I can also test if it fits in this project. :)

**Comment by birkir** [comment]
I just have a plugin in my editor to create components. I can just select some options like class based or functional component. If it should include styles and then select which one (css,scss,less).

Creates folder and files.

https://github.com/ueno-llc/ueno-atom-menu

**Comment by diegohaz** [comment]
Finally, I think it's done: https://github.com/diegohaz/generact

**Comment by oyeanuj** [comment]
@diegohaz This looks really cool, I'd like to try it out with `react-universally`.  How best do I go about integrating this with my fork to test it out?

**Comment by diegohaz** [comment]
@oyeanuj Just do this:
```
npm i -g generact
cd path/to/my/react-universally/app
generact
```
https://github.com/diegohaz/generact

**Comment by ctrlplusb** [comment]
For those interested, I have been using this package recently:

https://bitsrc.io/

Super cool 👍
