### ISSUE TITLE
Infinite loops with react-async-component

### ISSUE THREAD

**Issue by mschipperheyn** [ctrlplusb/react-universally#457]
I've been trying to deal with infinite loops and other issues on react-async-component, which is also referenced on their issue list: https://github.com/ctrlplusb/react-async-component/issues/42 (another one is here: https://github.com/styled-components/styled-components/issues/762).

They are very difficult to diagnose, but I wanted to share one issue that might be common on react-universally. If you reference a config value inside an async component and that value references a process.env.variable, you will get an infinite loop. I'm not a 100% if this applies to all cases, since I had to run to fix this and redeploy to production.

In my case, this does not show up during development, but does show on deployment to a Dokku container. Kinda tricky to deal with.

**Comment by sergiokopplin** [comment]
I'm having the same issue.
Sometimes it happens in my machine, but with a reload is resolves. But it's still a problem!

Haven't found any solution yet.

**Comment by ctrlplusb** [comment]
New versions are being released. Please let me know if it is still an issue 👍
