### ISSUE TITLE
Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by saniko** [ctrlplusb/react-universally#474]
Hi,
After merging the last PR, got this error message:
`Module not found: Error: Can't resolve 'fs'`

came across this [post](https://github.com/webpack-contrib/css-loader/issues/447)
After adding the` fs: 'empty',` to configFactory.js, it did solve the issue
But now I'm getting errors about config values.

Full error after running yarn:
```

ERROR in ./config/utils/envVars.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\**\config\utils'
 @ ./config/utils/envVars.js 22:10-23
 @ ./config/values.js
 @ ./config/index.js
 @ ./shared/components/DemoApp/index.js
 @ ./client/index.js
 @ multi regenerator-runtime/runtime ./client/index.js
```
Running latest node: 8.1.4
Any Idea?

**Comment by saniko** [comment]
In addition, I'm getting this error as well:

`ERROR in OfflinePlugin: Plugin's runtime wasn't added to one of your bundle entries. See this https://goo.gl/YwewYp for details.`

**Comment by saniko** [comment]
I have rolled back the webpack related code (the version upgrades and the configFactory.js modifications)
And now all is OK.

Does anyone have an idea why this error occurred?

**Comment by diondirza** [comment]
In my experience sometimes in Linux if RAM really limited and I have other node instance running this error will show up and I solve it by stop the process and re run.

**Comment by saniko** [comment]
Running on windows.
