### ISSUE TITLE
Accessing variables from config on client side

### ISSUE THREAD

**Issue by Ancinek** [ctrlplusb/react-universally#483]
Is it possible?

I want to set for example an API base URL as env var and pass it down. When I try to `console.log` it from anywhere using the `config` method I get undefined (as it seems that how the `config` method works).

**Comment by jordmccord** [comment]
Yes, you need to add the key that you want to expose to the `clientConfigFilter` key in the `config/values.js` file, you'll see some examples like `polyfillIO` and `htmlPage`.

**Comment by Ancinek** [comment]
Thanks. It was a stupid question as I noticed that the boilerplate comes with env vars used to display hello message.
