### ISSUE TITLE
Is the ReactHotLoader component still necessary?

### ISSUE THREAD

**Issue by codepunkt** [ctrlplusb/react-universally#486]
When importing `AppContainer` directly from `react-hot-loader/lib/AppContainer`, this is imported:

```
if (!module.hot || process.env.NODE_ENV === 'production') {
  module.exports = require('./AppContainer.prod');
} else {
  module.exports = require('./AppContainer.dev');
}
```

`AppContainer.prod` is more or less what the prod version of our `ReactHotLoader` component is. Can the `ReactHotLoader` component be removed?

**Comment by ctrlplusb** [comment]
Yep, thanks for this @codepunkt
