### ISSUE TITLE
Upgraded Styled Components branch/example

### ISSUE THREAD

**Issue by oyeanuj** [ctrlplusb/react-universally#492]
Hi folks! I noticed that the `styled-components` feature branch is still on v1 of the library. I've had some trouble upgrading but I figured some other folks here might have already upgraded. 

Is there an example fork/branch somewhere that one could look at, and maybe PR back to upgrade that feature branch?

**Comment by strues** [comment]
Updated the styled-components branch with version 2.

**Comment by oyeanuj** [comment]
@strues Thank you!

**Comment by oyeanuj** [comment]
@strues Noticed that the `styled-components` feature branch that you merged has two issues noted in the [`FEATURE_STYLED_COMPONENTS` document](https://github.com/ctrlplusb/react-universally/blob/feature/styled-components/docs/FEATURE_STYLED_COMPONENTS.md). But both those issues seem to have been resolved in the original SC repo.

Do you know if the Feature Document is out of date or if those still need to be implemented in feature branch?

**Comment by strues** [comment]
It's out of date @oyeanuj. Last time it was updated was against v12. I'll get around to updating those docs in the morning.

**Comment by oyeanuj** [comment]
@strues thanks. I also noticed that in [the code here](https://github.com/ctrlplusb/react-universally/blob/feature/styled-components/server/middleware/reactApplication/index.js#L34-L35), when SSR is disabled, we are using the `sheet` to collect styles but not retrieving `styleTags` from there.

It seems like either we should be doing that (like we do for SSR below), or not need to call `sheet.collectStyles` when not doing SSR. Thoughts?

**Comment by oyeanuj** [comment]
@strues Also, I removed one of the notes as part of #505. I'm not sure about what the first one is referring to `import` vs `require`.
