### ISSUE TITLE
taskRoutes && prefetchData

### ISSUE THREAD

**Issue by Gregcop1** [ctrlplusb/react-universally#494]
Hi, first: thanks for your awesome work. Excuse me for the stupid question but I'm an old user of react-universally, I've recently upgrade and I can't find taskRoutes and prefetchData anymore. How are we supposed to wait for API response to render the html on client side now ?

**Comment by Gregcop1** [comment]
My bad, we have to use 'react-jobs'

**Comment by ctrlplusb** [comment]
Hey @Gregcop1, yeah, you don't _have_ to. It's just an option. :)
