### ISSUE TITLE
Is there a need for tough-cookie dependancy?

### ISSUE THREAD

**Issue by kresent** [ctrlplusb/react-universally#495]
Is there a need for tough-cookie dependancy? It is the largest js file in dependancy list, and doesn't seem to solve that much. How can I get rid of it?

**Comment by ctrlplusb** [comment]
I'm not sure off hand but perhaps it came with one of the security packages? i.e. helmet/?

**Comment by kresent** [comment]
Hm, it seems as some deep dependancy that is rooted im some library. If someone knows the exact dependancy, please let me know
