### ISSUE TITLE
Clarifying polyfill setup

### ISSUE THREAD

**Issue by oyeanuj** [ctrlplusb/react-universally#509]
Hi folks! Quick question - it seems like we use `polyfill.io` on one hand and also have `babel-polyfill` package on the other hand? I'd love to understand the how's and why's!

Also, would happy to PR to the docs if we so feel the need!

Thank you!

**Comment by strues** [comment]
Looks like `babel-polyfill` is included in the dev deps, but isnt actually used anywhere.

**Comment by sergiokopplin** [comment]
I'm also having this doubt

**Comment by oyeanuj** [comment]
@sergiokopplin @strues So safe to take it out?

**Comment by sergiokopplin** [comment]
Not sure. I'm having a doubt about the use of both

**Comment by ctrlplusb** [comment]
I think it is used by Jest... but worthwhile checking :)

**Comment by strues** [comment]
Quick check shows `babel-polyfill` is only used by babel-cli, which installs the polyfill automatically and behind the scenes.

```
info Has been hoisted to "babel-polyfill"
info Reasons this module exists
   - "babel-cli" depends on it
   - Specified in "devDependencies"
```

It's save to remove from the devDeps IMO.

**Comment by oyeanuj** [comment]
Closing this issue since the [PR](https://github.com/ctrlplusb/react-universally/pull/510) is in `next`.
