### ISSUE TITLE
[Clarification] on now deployment source code

### ISSUE THREAD

**Issue by howardya** [ctrlplusb/react-universally#520]
For deployment to now.sh, the OSS plan by default exposes the code. Anyone can look at the source code by adding /_src behind the links.

The configuration done in this boilerplate has this feature as well? Meaning that when I run npm run deploy, the code that I pushed to now.sh will be exposed to everyone?

I tried to add /_src to the link from now.sh after running npm run deploy but it does not expose the code. So I want to clarify this. 

Cheers

**Comment by ctrlplusb** [comment]
Hi, this question may be better served on StackOverflow. Thanks
