### ISSUE TITLE
no live reload on the browser

### ISSUE THREAD

**Issue by sahaam** [ctrlplusb/react-universally#533]
Hi,

I ran the application in dev mode using command "npm run develop". When I make changes in the file shared/components/DemoApp/AsyncAboutRoute/AboutRoute.js or shared/components/DemoApp/AsyncCounterRoute/CounterRoute.js I don't see the Client(in the browser) getting the changes .

Any particular reason behind this? or this is designed in this way. When I refresh the browser(http://localhost:1337) I can see my changes.

**Comment by ctrlplusb** [comment]
See #506
