### ISSUE TITLE
Maintainence

### ISSUE THREAD

**Issue by snaerth** [ctrlplusb/react-universally#562]
Is this starter slowly getting outdated? Have main contributors stop maintaining? By the way thank you for a awesome starter

**Comment by sergiokopplin** [comment]
I guess we're trying to maintain updated, we have some open pr's. Is there any special part that you feel outdated?

**Comment by snaerth** [comment]
Maybe it's just minor. React related needs to update. And maybe you could consider to move to webpack 4 soon, when plugins like extract-text-webpack-plugin get updated to be compatible to webpack 4. But maybe just update packages in general. The longer you wait the longer it will take to make changes. But maybe I should just make a pull request for some changes :) and stop complaining!

**Comment by sergiokopplin** [comment]
Some dependencies update: https://github.com/ctrlplusb/react-universally/pull/561
Webpack 4: https://github.com/ctrlplusb/react-universally/pull/560
React 16: https://github.com/ctrlplusb/react-universally/issues/479

**Comment by snaerth** [comment]
Or just check out open pull request :)

**Comment by sergiokopplin** [comment]
Your issue is still valid. We should always ask and contribute!

**Comment by birkir** [comment]
`next` branch has now been updated with all the new things!

**Comment by snaerth** [comment]
Awesome! Thanks
