### ISSUE TITLE
Error walking react tree

### ISSUE THREAD

**Issue by birkir** [ctrlplusb/react-universally#563]
Awaiting npm release for `react-tree-walker` to remove the following error on **next** branch:

> Error walking react tree

Once released we can update the dependency and move on!

**Comment by ctrlplusb** [comment]
Shall do soon apologies! Great stuff organising all of this @birkir! 👍

**Comment by williamoliveira** [comment]
There is also an error if you update something then refresh the page

```
index.29ccfdb764425feead6f.hot-update.js:1 Uncaught ReferenceError: webpackHotUpdate is not defined
```

**Comment by ctrlplusb** [comment]
The react tree walker release has occurred.

Not sure about that error @williamoliveira - needs some more looking into.

**Comment by birkir** [comment]
Okay, now next is stable.

Even more stable than before, I added port detection, so bye bye "Error: listen EADDRINUSE :::7331".

Thanks, @ctrlplusb for making it happen!

**Comment by ctrlplusb** [comment]
Awesome work @birkir - you pushed this forward ⭐️

**Comment by ctrlplusb** [comment]
Let's give it a couple of days then move it to master 👍
