### ISSUE TITLE
[next] Uncaught ReferenceError: webpackHotUpdate is not defined

### ISSUE THREAD

**Issue by williamoliveira** [ctrlplusb/react-universally#565]
Steps to reproduce:

clean clone on last commit
yarn develop
change something in a component
manually refresh the page

**Comment by birkir** [comment]
This should be fixed with [`5dc8d`](https://github.com/ctrlplusb/react-universally/commit/5dc8d521a60f302dd6dae60e09621162ecbea00b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R81), just to make sure, remove node_modules and do npm/yarn install again.

**Comment by williamoliveira** [comment]
Did that but unfortunately the problem continues

**Comment by birkir** [comment]
Fixed with #566
