### ISSUE TITLE
Why do you still use fake style loader?

### ISSUE THREAD

**Issue by giltig** [ctrlplusb/react-universally#59]
fake-style-loader can be replaced by using css-loader/locals as explained in fake-style-loader#3. So, do not use the fake module family anymore. It is recommended to use css-loader, file-loader and url-loader directly instead.

**Comment by ctrlplusb** [comment]
I honestly had no idea! Thanks for bringing this to my attention. :-)

**Comment by ctrlplusb** [comment]
Thanks for this!

I also optimised the `url-loader` to only emit files for the client bundle.  👍
