### ISSUE TITLE
eslint-plugin-import module version seems to be invalid

### ISSUE THREAD

**Issue by hudakdidit** [ctrlplusb/react-universally#6]
`eslint-plugin-import` version seems to be wrong? I changed to `1.10.2` and installed fine.

Using node 6.2.1

Error I received after running `npm install` after cloning this repo:
```shell
npm ERR! No compatible version found: eslint-plugin-import@1.10.1
npm ERR! Valid install targets:
npm ERR! 1.10.2, 1.10.0, 1.9.2, 1.9.1, 1.9.0, 1.8.1, 1.8.0, 1.7.0, 1.6.1, 1.6.0, 1.5.0, 1.4.0, 1.3.0, 1.2.0, 1.1.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-beta.0, 0.13.0, 0.12.1, 0.12.0, 0.11.0, 0.10.1, 0.10.0, 0.9.1, 0.8.1, 0.8.0, 0.7.9, 0.7.8, 0.7.7, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.0, 0.5.2, 0.5.1, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.13, 0.3.12, 0.3.11, 0.3.10, 0.3.9, 0.3.8, 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.0
```

**Comment by ctrlplusb** [comment]
Very peculiar!

Thanks for the heads up.  I shall take a look and update soonest. x

**Comment by ctrlplusb** [comment]
They may have removed that revision due to a bug.  Feel like the carpet has been pulled from under me. 😮 

https://github.com/benmosher/eslint-plugin-import/issues/415

Patching now...

**Comment by ctrlplusb** [comment]
@hudakdidit 😘
