### ISSUE TITLE
nulls in html when not using SSR

### ISSUE THREAD

**Issue by omerts** [ctrlplusb/react-universally#70]
Hey,

We disabling SSR, I am getting nulls in the html output:
```
       null
       null
       null
       null


     </head>
     <body>
       <div id='app'>null</div>

       <script type='text/javascript'></script>
```

**Comment by omerts** [comment]
created PR https://github.com/ctrlplusb/react-universally/pull/71

**Comment by ctrlplusb** [comment]
Thanks, just got back from holiday, shall review when I have regathered myself. :-)
Appreciate the help.

**Comment by ctrlplusb** [comment]
Hi @omerts I've made a comment on your PR. Thanks.
