### ISSUE TITLE
Whenever i run development and change anything i get this warning

### ISSUE THREAD

**Issue by yanivkalfa** [ctrlplusb/react-universally#79]
When running npm run development.
Every thing i change in component fire this warning.

browser.js:49 Warning: [react-router] You cannot change <Router history>; it will be ignored

**Comment by ctrlplusb** [comment]
If you reference the [Troubleshooting](https://github.com/ctrlplusb/react-universally#troubleshooting) section you will see a question/answer that discusses this.
