### ISSUE TITLE
Question: Do I need dynamic routing to make react-hot-loader work?

### ISSUE THREAD

**Issue by cloud-walker** [ctrlplusb/react-universally#92]
In my project, where I've used your boilerplate, my hot reload seems to not work.

NOTE I'm not using dynamic routes for now, but I know I will need them, maybe in the future for code split the bundle. Maybe is that difference?

**Comment by ctrlplusb** [comment]
Hey @cloud-walker 

Sorry for my delayed responses - I am on a family holiday in the Scottish mountains.

Hmmm, you def don't require dynamic routes for the hot loading to work. Make sure you remove the workaround I put in the routes file though.

If it still doesn't work see if you can share a configuration with me and I would be happy to help you debug it.

**Comment by ctrlplusb** [comment]
Hey @cloud-walker 

Did you have any luck?  I am going to close this for now.  Let me know how it went for you.

**Comment by ckken** [comment]
function resolveModuleComponent(location, cb) {
    System.import(`../components/${location.params.module||'Home'}`)
        .then(module => cb(null, module.default))
        .catch(handleError);
}

<Route path=":module" getComponent={resolveModuleComponent} />

I use it for dynamic but it throw error not find fire
